In [1304]:
# Imports
from datetime import datetime
import pandas as pd
import os
from pathlib import Path

In [1305]:
# anlegen der Listen zum zwischenspeichern der Daten
zeitraum = []
bruehler_straße = []
estermannufer = []
kennedybruecke = []
nordbruecke = []
suedbruecke = []
rhenusallee = []
von_sandt_ufer = []
weg_auf_dem_damm = []
wilhelm_spiritus_ufer = []

# anlegen des fertigen Dataframes
df_gesamt = pd.DataFrame()

In [1306]:
# Daten laden Brühler_Straße_2015/17
df = pd.read_csv("../Projektdatensaetze_angepasst/2015-2017/Bruehler_Straße2015_2017.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')



# Index setzen
df = df.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()

# slicen
df = df['2016-01-16':]
df.index = df.index.tz_convert(None)


# korrekt benennen
df['Bruehler Straße'] = df['Bruehler Straße ']

# in Liste speichern
zeitraum = df.index.tolist()
bruehler_straße = df['Bruehler Straße'].values.tolist()
print(zeitraum)

[Timestamp('2016-01-16 00:00:00'), Timestamp('2016-01-16 01:00:00'), Timestamp('2016-01-16 02:00:00'), Timestamp('2016-01-16 03:00:00'), Timestamp('2016-01-16 04:00:00'), Timestamp('2016-01-16 05:00:00'), Timestamp('2016-01-16 06:00:00'), Timestamp('2016-01-16 07:00:00'), Timestamp('2016-01-16 08:00:00'), Timestamp('2016-01-16 09:00:00'), Timestamp('2016-01-16 10:00:00'), Timestamp('2016-01-16 11:00:00'), Timestamp('2016-01-16 12:00:00'), Timestamp('2016-01-16 13:00:00'), Timestamp('2016-01-16 14:00:00'), Timestamp('2016-01-16 15:00:00'), Timestamp('2016-01-16 16:00:00'), Timestamp('2016-01-16 17:00:00'), Timestamp('2016-01-16 18:00:00'), Timestamp('2016-01-16 19:00:00'), Timestamp('2016-01-16 20:00:00'), Timestamp('2016-01-16 21:00:00'), Timestamp('2016-01-16 22:00:00'), Timestamp('2016-01-16 23:00:00'), Timestamp('2016-01-17 00:00:00'), Timestamp('2016-01-17 01:00:00'), Timestamp('2016-01-17 02:00:00'), Timestamp('2016-01-17 03:00:00'), Timestamp('2016-01-17 04:00:00'), Timestamp('2016-01-17 05:00:00'), Timestamp('2016-01-17 06:00:00'), Timestamp('2016-01-17 07:00:00'), Timestamp('2016-01-17 08:00:00'), Timestamp('2016-01-17 09:00:00'), Timestamp('2016-01-17 10:00:00'), Timestamp('2016-01-17 11:00:00'), Timestamp('2016-01-17 12:00:00'), Timestamp('2016-01-17 13:00:00'), Timestamp('2016-01-17 14:00:00'), Timestamp('2016-01-17 15:00:00'), Timestamp('2016-01-17 16:00:00'), Timestamp('2016-01-17 17:00:00'), Timestamp('2016-01-17 18:00:00'), Timestamp('2016-01-17 19:00:00'), Timestamp('2016-01-17 20:00:00'), Timestamp('2016-01-17 21:00:00'), Timestamp('2016-01-17 22:00:00'), Timestamp('2016-01-17 23:00:00'), Timestamp('2016-01-18 00:00:00'), Timestamp('2016-01-18 01:00:00'), Timestamp('2016-01-18 02:00:00'), Timestamp('2016-01-18 03:00:00'), Timestamp('2016-01-18 04:00:00'), Timestamp('2016-01-18 05:00:00'), Timestamp('2016-01-18 06:00:00'), Timestamp('2016-01-18 07:00:00'), Timestamp('2016-01-18 08:00:00'), Timestamp('2016-01-18 09:00:00'), Timestamp('2016-01-18 10:00:00'), Timestamp('2016-01-18 11:00:00'), Timestamp('2016-01-18 12:00:00'), Timestamp('2016-01-18 13:00:00'), Timestamp('2016-01-18 14:00:00'), Timestamp('2016-01-18 15:00:00'), Timestamp('2016-01-18 16:00:00'), Timestamp('2016-01-18 17:00:00'), Timestamp('2016-01-18 18:00:00'), Timestamp('2016-01-18 19:00:00'), Timestamp('2016-01-18 20:00:00'), Timestamp('2016-01-18 21:00:00'), Timestamp('2016-01-18 22:00:00'), Timestamp('2016-01-18 23:00:00'), Timestamp('2016-01-19 00:00:00'), Timestamp('2016-01-19 01:00:00'), Timestamp('2016-01-19 02:00:00'), Timestamp('2016-01-19 03:00:00'), Timestamp('2016-01-19 04:00:00'), Timestamp('2016-01-19 05:00:00'), Timestamp('2016-01-19 06:00:00'), Timestamp('2016-01-19 07:00:00'), Timestamp('2016-01-19 08:00:00'), Timestamp('2016-01-19 09:00:00'), Timestamp('2016-01-19 10:00:00'), Timestamp('2016-01-19 11:00:00'), Timestamp('2016-01-19 12:00:00'), Timestamp('2016-01-19 13:00:00'), Timestamp('2016-01-19 14:00:00'), Timestamp('2016-01-19 15:00:00'), Timestamp('2016-01-19 16:00:00'), Timestamp('2016-01-19 17:00:00'), Timestamp('2016-01-19 18:00:00'), Timestamp('2016-01-19 19:00:00'), Timestamp('2016-01-19 20:00:00'), Timestamp('2016-01-19 21:00:00'), Timestamp('2016-01-19 22:00:00'), Timestamp('2016-01-19 23:00:00'), Timestamp('2016-01-20 00:00:00'), Timestamp('2016-01-20 01:00:00'), Timestamp('2016-01-20 02:00:00'), Timestamp('2016-01-20 03:00:00'), Timestamp('2016-01-20 04:00:00'), Timestamp('2016-01-20 05:00:00'), Timestamp('2016-01-20 06:00:00'), Timestamp('2016-01-20 07:00:00'), Timestamp('2016-01-20 08:00:00'), Timestamp('2016-01-20 09:00:00'), Timestamp('2016-01-20 10:00:00'), Timestamp('2016-01-20 11:00:00'), Timestamp('2016-01-20 12:00:00'), Timestamp('2016-01-20 13:00:00'), Timestamp('2016-01-20 14:00:00'), Timestamp('2016-01-20 15:00:00'), Timestamp('2016-01-20 16:00:00'), Timestamp('2016-01-20 17:00:00'), Timestamp('2016-01-20 18:00:00'), Timestamp('2016-01-20 19:00:00'), Timestamp('2016-01-20 20:00:00'), Timestamp('2016-01-20 21:00:00'), Timestamp('2016-01-20 22:00:00'), Timestamp('2016-01-20 23:00:00'), Timestamp('2016-01-21 00:00:00'), Timestamp('2016-01-21 01:00:00'), Timestamp('2016-01-21 02:00:00'), Timestamp('2016-01-21 03:00:00'), Timestamp('2016-01-21 04:00:00'), Timestamp('2016-01-21 05:00:00'), Timestamp('2016-01-21 06:00:00'), Timestamp('2016-01-21 07:00:00'), Timestamp('2016-01-21 08:00:00'), Timestamp('2016-01-21 09:00:00'), Timestamp('2016-01-21 10:00:00'), Timestamp('2016-01-21 11:00:00'), Timestamp('2016-01-21 12:00:00'), Timestamp('2016-01-21 13:00:00'), Timestamp('2016-01-21 14:00:00'), Timestamp('2016-01-21 15:00:00'), Timestamp('2016-01-21 16:00:00'), Timestamp('2016-01-21 17:00:00'), Timestamp('2016-01-21 18:00:00'), Timestamp('2016-01-21 19:00:00'), Timestamp('2016-01-21 20:00:00'), Timestamp('2016-01-21 21:00:00'), Timestamp('2016-01-21 22:00:00'), Timestamp('2016-01-21 23:00:00'), Timestamp('2016-01-22 00:00:00'), Timestamp('2016-01-22 01:00:00'), Timestamp('2016-01-22 02:00:00'), Timestamp('2016-01-22 03:00:00'), Timestamp('2016-01-22 04:00:00'), Timestamp('2016-01-22 05:00:00'), Timestamp('2016-01-22 06:00:00'), Timestamp('2016-01-22 07:00:00'), Timestamp('2016-01-22 08:00:00'), Timestamp('2016-01-22 09:00:00'), Timestamp('2016-01-22 10:00:00'), Timestamp('2016-01-22 11:00:00'), Timestamp('2016-01-22 12:00:00'), Timestamp('2016-01-22 13:00:00'), Timestamp('2016-01-22 14:00:00'), Timestamp('2016-01-22 15:00:00'), Timestamp('2016-01-22 16:00:00'), Timestamp('2016-01-22 17:00:00'), Timestamp('2016-01-22 18:00:00'), Timestamp('2016-01-22 19:00:00'), Timestamp('2016-01-22 20:00:00'), Timestamp('2016-01-22 21:00:00'), Timestamp('2016-01-22 22:00:00'), Timestamp('2016-01-22 23:00:00'), Timestamp('2016-01-23 00:00:00'), Timestamp('2016-01-23 01:00:00'), Timestamp('2016-01-23 02:00:00'), Timestamp('2016-01-23 03:00:00'), Timestamp('2016-01-23 04:00:00'), Timestamp('2016-01-23 05:00:00'), Timestamp('2016-01-23 06:00:00'), Timestamp('2016-01-23 07:00:00'), Timestamp('2016-01-23 08:00:00'), Timestamp('2016-01-23 09:00:00'), Timestamp('2016-01-23 10:00:00'), Timestamp('2016-01-23 11:00:00'), Timestamp('2016-01-23 12:00:00'), Timestamp('2016-01-23 13:00:00'), Timestamp('2016-01-23 14:00:00'), Timestamp('2016-01-23 15:00:00'), Timestamp('2016-01-23 16:00:00'), Timestamp('2016-01-23 17:00:00'), Timestamp('2016-01-23 18:00:00'), Timestamp('2016-01-23 19:00:00'), Timestamp('2016-01-23 20:00:00'), Timestamp('2016-01-23 21:00:00'), Timestamp('2016-01-23 22:00:00'), Timestamp('2016-01-23 23:00:00'), Timestamp('2016-01-24 00:00:00'), Timestamp('2016-01-24 01:00:00'), Timestamp('2016-01-24 02:00:00'), Timestamp('2016-01-24 03:00:00'), Timestamp('2016-01-24 04:00:00'), Timestamp('2016-01-24 05:00:00'), Timestamp('2016-01-24 06:00:00'), Timestamp('2016-01-24 07:00:00'), Timestamp('2016-01-24 08:00:00'), Timestamp('2016-01-24 09:00:00'), Timestamp('2016-01-24 10:00:00'), Timestamp('2016-01-24 11:00:00'), Timestamp('2016-01-24 12:00:00'), Timestamp('2016-01-24 13:00:00'), Timestamp('2016-01-24 14:00:00'), Timestamp('2016-01-24 15:00:00'), Timestamp('2016-01-24 16:00:00'), Timestamp('2016-01-24 17:00:00'), Timestamp('2016-01-24 18:00:00'), Timestamp('2016-01-24 19:00:00'), Timestamp('2016-01-24 20:00:00'), Timestamp('2016-01-24 21:00:00'), Timestamp('2016-01-24 22:00:00'), Timestamp('2016-01-24 23:00:00'), Timestamp('2016-01-25 00:00:00'), Timestamp('2016-01-25 01:00:00'), Timestamp('2016-01-25 02:00:00'), Timestamp('2016-01-25 03:00:00'), Timestamp('2016-01-25 04:00:00'), Timestamp('2016-01-25 05:00:00'), Timestamp('2016-01-25 06:00:00'), Timestamp('2016-01-25 07:00:00'), Timestamp('2016-01-25 08:00:00'), Timestamp('2016-01-25 09:00:00'), Timestamp('2016-01-25 10:00:00'), Timestamp('2016-01-25 11:00:00'), Timestamp('2016-01-25 12:00:00'), Timestamp('2016-01-25 13:00:00'), Timestamp('2016-01-25 14:00:00'), Timestamp('2016-01-25 15:00:00'), Timestamp('2016-01-25 16:00:00'), Timestamp('2016-01-25 17:00:00'), Timestamp('2016-01-25 18:00:00'), Timestamp('2016-01-25 19:00:00'), Timestamp('2016-01-25 20:00:00'), Timestamp('2016-01-25 21:00:00'), Timestamp('2016-01-25 22:00:00'), Timestamp('2016-01-25 23:00:00'), Timestamp('2016-01-26 00:00:00'), Timestamp('2016-01-26 01:00:00'), Timestamp('2016-01-26 02:00:00'), Timestamp('2016-01-26 03:00:00'), Timestamp('2016-01-26 04:00:00'), Timestamp('2016-01-26 05:00:00'), Timestamp('2016-01-26 06:00:00'), Timestamp('2016-01-26 07:00:00'), Timestamp('2016-01-26 08:00:00'), Timestamp('2016-01-26 09:00:00'), Timestamp('2016-01-26 10:00:00'), Timestamp('2016-01-26 11:00:00'), Timestamp('2016-01-26 12:00:00'), Timestamp('2016-01-26 13:00:00'), Timestamp('2016-01-26 14:00:00'), Timestamp('2016-01-26 15:00:00'), Timestamp('2016-01-26 16:00:00'), Timestamp('2016-01-26 17:00:00'), Timestamp('2016-01-26 18:00:00'), Timestamp('2016-01-26 19:00:00'), Timestamp('2016-01-26 20:00:00'), Timestamp('2016-01-26 21:00:00'), Timestamp('2016-01-26 22:00:00'), Timestamp('2016-01-26 23:00:00'), Timestamp('2016-01-27 00:00:00'), Timestamp('2016-01-27 01:00:00'), Timestamp('2016-01-27 02:00:00'), Timestamp('2016-01-27 03:00:00'), Timestamp('2016-01-27 04:00:00'), Timestamp('2016-01-27 05:00:00'), Timestamp('2016-01-27 06:00:00'), Timestamp('2016-01-27 07:00:00'), Timestamp('2016-01-27 08:00:00'), Timestamp('2016-01-27 09:00:00'), Timestamp('2016-01-27 10:00:00'), Timestamp('2016-01-27 11:00:00'), Timestamp('2016-01-27 12:00:00'), Timestamp('2016-01-27 13:00:00'), Timestamp('2016-01-27 14:00:00'), Timestamp('2016-01-27 15:00:00'), Timestamp('2016-01-27 16:00:00'), Timestamp('2016-01-27 17:00:00'), Timestamp('2016-01-27 18:00:00'), Timestamp('2016-01-27 19:00:00'), Timestamp('2016-01-27 20:00:00'), Timestamp('2016-01-27 21:00:00'), Timestamp('2016-01-27 22:00:00'), Timestamp('2016-01-27 23:00:00'), Timestamp('2016-01-28 00:00:00'), Timestamp('2016-01-28 01:00:00'), Timestamp('2016-01-28 02:00:00'), Timestamp('2016-01-28 03:00:00'), Timestamp('2016-01-28 04:00:00'), Timestamp('2016-01-28 05:00:00'), Timestamp('2016-01-28 06:00:00'), Timestamp('2016-01-28 07:00:00'), Timestamp('2016-01-28 08:00:00'), Timestamp('2016-01-28 09:00:00'), Timestamp('2016-01-28 10:00:00'), Timestamp('2016-01-28 11:00:00'), Timestamp('2016-01-28 12:00:00'), Timestamp('2016-01-28 13:00:00'), Timestamp('2016-01-28 14:00:00'), Timestamp('2016-01-28 15:00:00'), Timestamp('2016-01-28 16:00:00'), Timestamp('2016-01-28 17:00:00'), Timestamp('2016-01-28 18:00:00'), Timestamp('2016-01-28 19:00:00'), Timestamp('2016-01-28 20:00:00'), Timestamp('2016-01-28 21:00:00'), Timestamp('2016-01-28 22:00:00'), Timestamp('2016-01-28 23:00:00'), Timestamp('2016-01-29 00:00:00'), Timestamp('2016-01-29 01:00:00'), Timestamp('2016-01-29 02:00:00'), Timestamp('2016-01-29 03:00:00'), Timestamp('2016-01-29 04:00:00'), Timestamp('2016-01-29 05:00:00'), Timestamp('2016-01-29 06:00:00'), Timestamp('2016-01-29 07:00:00'), Timestamp('2016-01-29 08:00:00'), Timestamp('2016-01-29 09:00:00'), Timestamp('2016-01-29 10:00:00'), Timestamp('2016-01-29 11:00:00'), Timestamp('2016-01-29 12:00:00'), Timestamp('2016-01-29 13:00:00'), Timestamp('2016-01-29 14:00:00'), Timestamp('2016-01-29 15:00:00'), Timestamp('2016-01-29 16:00:00'), Timestamp('2016-01-29 17:00:00'), Timestamp('2016-01-29 18:00:00'), Timestamp('2016-01-29 19:00:00'), Timestamp('2016-01-29 20:00:00'), Timestamp('2016-01-29 21:00:00'), Timestamp('2016-01-29 22:00:00'), Timestamp('2016-01-29 23:00:00'), Timestamp('2016-01-30 00:00:00'), Timestamp('2016-01-30 01:00:00'), Timestamp('2016-01-30 02:00:00'), Timestamp('2016-01-30 03:00:00'), Timestamp('2016-01-30 04:00:00'), Timestamp('2016-01-30 05:00:00'), Timestamp('2016-01-30 06:00:00'), Timestamp('2016-01-30 07:00:00'), Timestamp('2016-01-30 08:00:00'), Timestamp('2016-01-30 09:00:00'), Timestamp('2016-01-30 10:00:00'), Timestamp('2016-01-30 11:00:00'), Timestamp('2016-01-30 12:00:00'), Timestamp('2016-01-30 13:00:00'), Timestamp('2016-01-30 14:00:00'), Timestamp('2016-01-30 15:00:00'), Timestamp('2016-01-30 16:00:00'), Timestamp('2016-01-30 17:00:00'), Timestamp('2016-01-30 18:00:00'), Timestamp('2016-01-30 19:00:00'), Timestamp('2016-01-30 20:00:00'), Timestamp('2016-01-30 21:00:00'), Timestamp('2016-01-30 22:00:00'), Timestamp('2016-01-30 23:00:00'), Timestamp('2016-01-31 00:00:00'), Timestamp('2016-01-31 01:00:00'), Timestamp('2016-01-31 02:00:00'), Timestamp('2016-01-31 03:00:00'), Timestamp('2016-01-31 04:00:00'), Timestamp('2016-01-31 05:00:00'), Timestamp('2016-01-31 06:00:00'), Timestamp('2016-01-31 07:00:00'), Timestamp('2016-01-31 08:00:00'), Timestamp('2016-01-31 09:00:00'), Timestamp('2016-01-31 10:00:00'), Timestamp('2016-01-31 11:00:00'), Timestamp('2016-01-31 12:00:00'), Timestamp('2016-01-31 13:00:00'), Timestamp('2016-01-31 14:00:00'), Timestamp('2016-01-31 15:00:00'), Timestamp('2016-01-31 16:00:00'), Timestamp('2016-01-31 17:00:00'), Timestamp('2016-01-31 18:00:00'), Timestamp('2016-01-31 19:00:00'), Timestamp('2016-01-31 20:00:00'), Timestamp('2016-01-31 21:00:00'), Timestamp('2016-01-31 22:00:00'), Timestamp('2016-01-31 23:00:00'), Timestamp('2016-02-01 00:00:00'), Timestamp('2016-02-01 01:00:00'), Timestamp('2016-02-01 02:00:00'), Timestamp('2016-02-01 03:00:00'), Timestamp('2016-02-01 04:00:00'), Timestamp('2016-02-01 05:00:00'), Timestamp('2016-02-01 06:00:00'), Timestamp('2016-02-01 07:00:00'), Timestamp('2016-02-01 08:00:00'), Timestamp('2016-02-01 09:00:00'), Timestamp('2016-02-01 10:00:00'), Timestamp('2016-02-01 11:00:00'), Timestamp('2016-02-01 12:00:00'), Timestamp('2016-02-01 13:00:00'), Timestamp('2016-02-01 14:00:00'), Timestamp('2016-02-01 15:00:00'), Timestamp('2016-02-01 16:00:00'), Timestamp('2016-02-01 17:00:00'), Timestamp('2016-02-01 18:00:00'), Timestamp('2016-02-01 19:00:00'), Timestamp('2016-02-01 20:00:00'), Timestamp('2016-02-01 21:00:00'), Timestamp('2016-02-01 22:00:00'), Timestamp('2016-02-01 23:00:00'), Timestamp('2016-02-02 00:00:00'), Timestamp('2016-02-02 01:00:00'), Timestamp('2016-02-02 02:00:00'), Timestamp('2016-02-02 03:00:00'), Timestamp('2016-02-02 04:00:00'), Timestamp('2016-02-02 05:00:00'), Timestamp('2016-02-02 06:00:00'), Timestamp('2016-02-02 07:00:00'), Timestamp('2016-02-02 08:00:00'), Timestamp('2016-02-02 09:00:00'), Timestamp('2016-02-02 10:00:00'), Timestamp('2016-02-02 11:00:00'), Timestamp('2016-02-02 12:00:00'), Timestamp('2016-02-02 13:00:00'), Timestamp('2016-02-02 14:00:00'), Timestamp('2016-02-02 15:00:00'), Timestamp('2016-02-02 16:00:00'), Timestamp('2016-02-02 17:00:00'), Timestamp('2016-02-02 18:00:00'), Timestamp('2016-02-02 19:00:00'), Timestamp('2016-02-02 20:00:00'), Timestamp('2016-02-02 21:00:00'), Timestamp('2016-02-02 22:00:00'), Timestamp('2016-02-02 23:00:00'), Timestamp('2016-02-03 00:00:00'), Timestamp('2016-02-03 01:00:00'), Timestamp('2016-02-03 02:00:00'), Timestamp('2016-02-03 03:00:00'), Timestamp('2016-02-03 04:00:00'), Timestamp('2016-02-03 05:00:00'), Timestamp('2016-02-03 06:00:00'), Timestamp('2016-02-03 07:00:00'), Timestamp('2016-02-03 08:00:00'), Timestamp('2016-02-03 09:00:00'), Timestamp('2016-02-03 10:00:00'), Timestamp('2016-02-03 11:00:00'), Timestamp('2016-02-03 12:00:00'), Timestamp('2016-02-03 13:00:00'), Timestamp('2016-02-03 14:00:00'), Timestamp('2016-02-03 15:00:00'), Timestamp('2016-02-03 16:00:00'), Timestamp('2016-02-03 17:00:00'), Timestamp('2016-02-03 18:00:00'), Timestamp('2016-02-03 19:00:00'), Timestamp('2016-02-03 20:00:00'), Timestamp('2016-02-03 21:00:00'), Timestamp('2016-02-03 22:00:00'), Timestamp('2016-02-03 23:00:00'), Timestamp('2016-02-04 00:00:00'), Timestamp('2016-02-04 01:00:00'), Timestamp('2016-02-04 02:00:00'), Timestamp('2016-02-04 03:00:00'), Timestamp('2016-02-04 04:00:00'), Timestamp('2016-02-04 05:00:00'), Timestamp('2016-02-04 06:00:00'), Timestamp('2016-02-04 07:00:00'), Timestamp('2016-02-04 08:00:00'), Timestamp('2016-02-04 09:00:00'), Timestamp('2016-02-04 10:00:00'), Timestamp('2016-02-04 11:00:00'), Timestamp('2016-02-04 12:00:00'), Timestamp('2016-02-04 13:00:00'), Timestamp('2016-02-04 14:00:00'), Timestamp('2016-02-04 15:00:00'), Timestamp('2016-02-04 16:00:00'), Timestamp('2016-02-04 17:00:00'), Timestamp('2016-02-04 18:00:00'), Timestamp('2016-02-04 19:00:00'), Timestamp('2016-02-04 20:00:00'), Timestamp('2016-02-04 21:00:00'), Timestamp('2016-02-04 22:00:00'), Timestamp('2016-02-04 23:00:00'), Timestamp('2016-02-05 00:00:00'), Timestamp('2016-02-05 01:00:00'), Timestamp('2016-02-05 02:00:00'), Timestamp('2016-02-05 03:00:00'), Timestamp('2016-02-05 04:00:00'), Timestamp('2016-02-05 05:00:00'), Timestamp('2016-02-05 06:00:00'), Timestamp('2016-02-05 07:00:00'), Timestamp('2016-02-05 08:00:00'), Timestamp('2016-02-05 09:00:00'), Timestamp('2016-02-05 10:00:00'), Timestamp('2016-02-05 11:00:00'), Timestamp('2016-02-05 12:00:00'), Timestamp('2016-02-05 13:00:00'), Timestamp('2016-02-05 14:00:00'), Timestamp('2016-02-05 15:00:00'), Timestamp('2016-02-05 16:00:00'), Timestamp('2016-02-05 17:00:00'), Timestamp('2016-02-05 18:00:00'), Timestamp('2016-02-05 19:00:00'), Timestamp('2016-02-05 20:00:00'), Timestamp('2016-02-05 21:00:00'), Timestamp('2016-02-05 22:00:00'), Timestamp('2016-02-05 23:00:00'), Timestamp('2016-02-06 00:00:00'), Timestamp('2016-02-06 01:00:00'), Timestamp('2016-02-06 02:00:00'), Timestamp('2016-02-06 03:00:00'), Timestamp('2016-02-06 04:00:00'), Timestamp('2016-02-06 05:00:00'), Timestamp('2016-02-06 06:00:00'), Timestamp('2016-02-06 07:00:00'), Timestamp('2016-02-06 08:00:00'), Timestamp('2016-02-06 09:00:00'), Timestamp('2016-02-06 10:00:00'), Timestamp('2016-02-06 11:00:00'), Timestamp('2016-02-06 12:00:00'), Timestamp('2016-02-06 13:00:00'), Timestamp('2016-02-06 14:00:00'), Timestamp('2016-02-06 15:00:00'), Timestamp('2016-02-06 16:00:00'), Timestamp('2016-02-06 17:00:00'), Timestamp('2016-02-06 18:00:00'), Timestamp('2016-02-06 19:00:00'), Timestamp('2016-02-06 20:00:00'), Timestamp('2016-02-06 21:00:00'), Timestamp('2016-02-06 22:00:00'), Timestamp('2016-02-06 23:00:00'), Timestamp('2016-02-07 00:00:00'), Timestamp('2016-02-07 01:00:00'), Timestamp('2016-02-07 02:00:00'), Timestamp('2016-02-07 03:00:00'), Timestamp('2016-02-07 04:00:00'), Timestamp('2016-02-07 05:00:00'), Timestamp('2016-02-07 06:00:00'), Timestamp('2016-02-07 07:00:00'), Timestamp('2016-02-07 08:00:00'), Timestamp('2016-02-07 09:00:00'), Timestamp('2016-02-07 10:00:00'), Timestamp('2016-02-07 11:00:00'), Timestamp('2016-02-07 12:00:00'), Timestamp('2016-02-07 13:00:00'), Timestamp('2016-02-07 14:00:00'), Timestamp('2016-02-07 15:00:00'), Timestamp('2016-02-07 16:00:00'), Timestamp('2016-02-07 17:00:00'), Timestamp('2016-02-07 18:00:00'), Timestamp('2016-02-07 19:00:00'), Timestamp('2016-02-07 20:00:00'), Timestamp('2016-02-07 21:00:00'), Timestamp('2016-02-07 22:00:00'), Timestamp('2016-02-07 23:00:00'), Timestamp('2016-02-08 00:00:00'), Timestamp('2016-02-08 01:00:00'), Timestamp('2016-02-08 02:00:00'), Timestamp('2016-02-08 03:00:00'), Timestamp('2016-02-08 04:00:00'), Timestamp('2016-02-08 05:00:00'), Timestamp('2016-02-08 06:00:00'), Timestamp('2016-02-08 07:00:00'), Timestamp('2016-02-08 08:00:00'), Timestamp('2016-02-08 09:00:00'), Timestamp('2016-02-08 10:00:00'), Timestamp('2016-02-08 11:00:00'), Timestamp('2016-02-08 12:00:00'), Timestamp('2016-02-08 13:00:00'), Timestamp('2016-02-08 14:00:00'), Timestamp('2016-02-08 15:00:00'), Timestamp('2016-02-08 16:00:00'), Timestamp('2016-02-08 17:00:00'), Timestamp('2016-02-08 18:00:00'), Timestamp('2016-02-08 19:00:00'), Timestamp('2016-02-08 20:00:00'), Timestamp('2016-02-08 21:00:00'), Timestamp('2016-02-08 22:00:00'), Timestamp('2016-02-08 23:00:00'), Timestamp('2016-02-09 00:00:00'), Timestamp('2016-02-09 01:00:00'), Timestamp('2016-02-09 02:00:00'), Timestamp('2016-02-09 03:00:00'), Timestamp('2016-02-09 04:00:00'), Timestamp('2016-02-09 05:00:00'), Timestamp('2016-02-09 06:00:00'), Timestamp('2016-02-09 07:00:00'), Timestamp('2016-02-09 08:00:00'), Timestamp('2016-02-09 09:00:00'), Timestamp('2016-02-09 10:00:00'), Timestamp('2016-02-09 11:00:00'), Timesta

In [1307]:
# Daten laden Estermannufer_2015/17
df = pd.read_csv("../Projektdatensaetze_angepasst/2015-2017/Estermannufer2015_2017.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')


# Index setzen
df = df.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()

# slicen
df = df['2016-01-16':]

# korrekt benennen
df['Estermannufer'] = df['Estermannufer ']

# in Liste speichern
estermannufer = df['Estermannufer'].values.tolist()

In [1308]:
# Daten laden Kennedybrücke_2015/17
df  = pd.read_csv("../Projektdatensaetze_angepasst/2015-2017/Kennedybruecke(Nord)2015_2017.csv")
df1 = pd.read_csv("../Projektdatensaetze_angepasst/2015-2017/Kennedybruecke(Sued)Barometer2015_2017.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')
df1['time'] = pd.to_datetime(df1['time'])
df1['time'] = pd.to_datetime(df1['time'], format = '%Y-%m-%d %H:%M:%S')



# Index setzen
df = df.set_index('time')
df1 = df1.set_index('time')


# auf Stunden umrechnen
df = df.resample('h').sum()
df1 = df1.resample('h').sum()

# slicen
df = df['2016-01-16':]
df1 = df1['2016-01-16':]

# korrekt benennen
df['Kennedybruecke'] = df['Kennedybruecke (Nord) '] + df1['Kennedybruecke (Sued) Barometer ']

# in Liste speichern
kennedybruecke = df['Kennedybruecke'].values.tolist()

In [1309]:
# Daten laden Nordbrücke_2015/17
df  = pd.read_csv("../Projektdatensaetze_angepasst/2015-2017/Nordbruecke(Nord)2015_2017.csv")
df1 = pd.read_csv("../Projektdatensaetze_angepasst/2015-2017/Nordbruecke(Sued)2015_2017.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')
df1['time'] = pd.to_datetime(df1['time'])
df1['time'] = pd.to_datetime(df1['time'], format = '%Y-%m-%d %H:%M:%S')



# Index setzen
df = df.set_index('time')
df1 = df1.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()
df1 = df1.resample('h').sum()

# slicen
df = df['2016-01-16':]
df1 = df1['2016-01-16':]

# korrekt benennen
df['Nordbruecke'] = df['Nordbruecke (Nord) '] + df1['Nordbruecke (Sued) ']

# in Liste speichern
nordbruecke = df['Nordbruecke'].values.tolist()

In [1310]:
# Daten laden Rhenusallee_2015/2017
df  = pd.read_csv("../Projektdatensaetze_angepasst/2015-2017/Rhenusallee2015_2017.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')


# Index setzen
df = df.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()

# slicen
df = df['2016-01-16':]

# korrekt benennen
df['Rhenusallee'] = df['Rhenusallee ']

# in Liste speichern
rhenusallee = df['Rhenusallee'].values.tolist()

In [1311]:
# Daten laden Suedbruecke_2015/2017
df  = pd.read_csv("../Projektdatensaetze_angepasst/2015-2017/Suedbruecke(Nord)2015_2017.csv")
df1 = pd.read_csv("../Projektdatensaetze_angepasst/2015-2017/Suedbruecke(Sued)2015_2017.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')
df1['time'] = pd.to_datetime(df1['time'])
df1['time'] = pd.to_datetime(df1['time'], format = '%Y-%m-%d %H:%M:%S')


# Index setzen
df = df.set_index('time')
df1 = df1.set_index('time')


# auf Stunden umrechnen
df = df.resample('h').sum()
df1 = df1.resample('h').sum()

# slicen
df = df['2016-01-16':]
df1 = df1['2016-01-16':]

# korrekt benennen
df['Suedbruecke'] = df['Suedbruecke (Nord) '] + df1['Suedbruecke (Sued) ']

# in Liste speichern
suedbruecke = df['Suedbruecke'].values.tolist()

In [1312]:
# Daten laden vonSandtUfer_2015/2017
df  = pd.read_csv("../Projektdatensaetze_angepasst/2015-2017/vonSandtUfer2015_2017.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')

# Index setzen
df = df.set_index('time')


# auf Stunden umrechnen
df = df.resample('h').sum()

# slicen
df = df['2016-01-16':]

# korrekt benennen
df['vonSandtUfer'] = df['Von-Sandt-Ufer ']

# in Liste speichern
von_sandt_ufer = df['vonSandtUfer'].values.tolist()

In [1313]:
# Daten laden WegDammUfer_2015/2017
df  = pd.read_csv("../Projektdatensaetze_angepasst/2015-2017/WegDammBonnBeuel2015_2017.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')


# Index setzen
df = df.set_index('time')


# auf Stunden umrechnen
df = df.resample('h').sum()

# slicen
df = df['2016-01-16':]

# korrekt benennen
df['WegDammBonnBeuel'] = df['Weg auf Damm Neil ']

# in Liste speichern
weg_auf_dem_damm = df['WegDammBonnBeuel'].values.tolist()

In [1314]:
# Daten laden WegDammUfer_2015/2017
df  = pd.read_csv("../Projektdatensaetze_angepasst/2015-2017/WilhelmSpiritusUfer2015_2017.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')



# Index setzen
df = df.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()

# slicen
df = df['2016-01-16':]

# korrekt benennen
df['WilhelmSpiritusUfer'] = df['Wilhelm-Spiritus-Ufer ']

# in Liste speichern
wilhelm_spiritus_ufer = df['WilhelmSpiritusUfer'].values.tolist()

In [1315]:
# Ausgabe der Listen um auf Länge zu testen 2015-2017
print(len(zeitraum))
print(len(bruehler_straße))
print(len(estermannufer))
print(len(kennedybruecke))
print(len(nordbruecke))
print(len(suedbruecke))
print(len(rhenusallee))
print(len(von_sandt_ufer))
print(len(weg_auf_dem_damm))
print(len(wilhelm_spiritus_ufer))

17184
17184
17184
17184
17184
17184
17184
17184
17184
17184

In [1316]:
# Daten laden Brühler_Straße_2018
df = pd.read_csv("../Projektdatensaetze_angepasst/2018/BruehlerStraße2018.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')



# Index setzen
df = df.set_index('time')


# auf Stunden umrechnen
df = df.resample('h').sum()

# in Liste speichern
zeitraum = zeitraum + df.index.tolist()
bruehler_straße = bruehler_straße + df['Bruehler Straße'].values.tolist()
print(zeitraum)

[Timestamp('2016-01-16 00:00:00'), Timestamp('2016-01-16 01:00:00'), Timestamp('2016-01-16 02:00:00'), Timestamp('2016-01-16 03:00:00'), Timestamp('2016-01-16 04:00:00'), Timestamp('2016-01-16 05:00:00'), Timestamp('2016-01-16 06:00:00'), Timestamp('2016-01-16 07:00:00'), Timestamp('2016-01-16 08:00:00'), Timestamp('2016-01-16 09:00:00'), Timestamp('2016-01-16 10:00:00'), Timestamp('2016-01-16 11:00:00'), Timestamp('2016-01-16 12:00:00'), Timestamp('2016-01-16 13:00:00'), Timestamp('2016-01-16 14:00:00'), Timestamp('2016-01-16 15:00:00'), Timestamp('2016-01-16 16:00:00'), Timestamp('2016-01-16 17:00:00'), Timestamp('2016-01-16 18:00:00'), Timestamp('2016-01-16 19:00:00'), Timestamp('2016-01-16 20:00:00'), Timestamp('2016-01-16 21:00:00'), Timestamp('2016-01-16 22:00:00'), Timestamp('2016-01-16 23:00:00'), Timestamp('2016-01-17 00:00:00'), Timestamp('2016-01-17 01:00:00'), Timestamp('2016-01-17 02:00:00'), Timestamp('2016-01-17 03:00:00'), Timestamp('2016-01-17 04:00:00'), Timestamp('2016-01-17 05:00:00'), Timestamp('2016-01-17 06:00:00'), Timestamp('2016-01-17 07:00:00'), Timestamp('2016-01-17 08:00:00'), Timestamp('2016-01-17 09:00:00'), Timestamp('2016-01-17 10:00:00'), Timestamp('2016-01-17 11:00:00'), Timestamp('2016-01-17 12:00:00'), Timestamp('2016-01-17 13:00:00'), Timestamp('2016-01-17 14:00:00'), Timestamp('2016-01-17 15:00:00'), Timestamp('2016-01-17 16:00:00'), Timestamp('2016-01-17 17:00:00'), Timestamp('2016-01-17 18:00:00'), Timestamp('2016-01-17 19:00:00'), Timestamp('2016-01-17 20:00:00'), Timestamp('2016-01-17 21:00:00'), Timestamp('2016-01-17 22:00:00'), Timestamp('2016-01-17 23:00:00'), Timestamp('2016-01-18 00:00:00'), Timestamp('2016-01-18 01:00:00'), Timestamp('2016-01-18 02:00:00'), Timestamp('2016-01-18 03:00:00'), Timestamp('2016-01-18 04:00:00'), Timestamp('2016-01-18 05:00:00'), Timestamp('2016-01-18 06:00:00'), Timestamp('2016-01-18 07:00:00'), Timestamp('2016-01-18 08:00:00'), Timestamp('2016-01-18 09:00:00'), Timestamp('2016-01-18 10:00:00'), Timestamp('2016-01-18 11:00:00'), Timestamp('2016-01-18 12:00:00'), Timestamp('2016-01-18 13:00:00'), Timestamp('2016-01-18 14:00:00'), Timestamp('2016-01-18 15:00:00'), Timestamp('2016-01-18 16:00:00'), Timestamp('2016-01-18 17:00:00'), Timestamp('2016-01-18 18:00:00'), Timestamp('2016-01-18 19:00:00'), Timestamp('2016-01-18 20:00:00'), Timestamp('2016-01-18 21:00:00'), Timestamp('2016-01-18 22:00:00'), Timestamp('2016-01-18 23:00:00'), Timestamp('2016-01-19 00:00:00'), Timestamp('2016-01-19 01:00:00'), Timestamp('2016-01-19 02:00:00'), Timestamp('2016-01-19 03:00:00'), Timestamp('2016-01-19 04:00:00'), Timestamp('2016-01-19 05:00:00'), Timestamp('2016-01-19 06:00:00'), Timestamp('2016-01-19 07:00:00'), Timestamp('2016-01-19 08:00:00'), Timestamp('2016-01-19 09:00:00'), Timestamp('2016-01-19 10:00:00'), Timestamp('2016-01-19 11:00:00'), Timestamp('2016-01-19 12:00:00'), Timestamp('2016-01-19 13:00:00'), Timestamp('2016-01-19 14:00:00'), Timestamp('2016-01-19 15:00:00'), Timestamp('2016-01-19 16:00:00'), Timestamp('2016-01-19 17:00:00'), Timestamp('2016-01-19 18:00:00'), Timestamp('2016-01-19 19:00:00'), Timestamp('2016-01-19 20:00:00'), Timestamp('2016-01-19 21:00:00'), Timestamp('2016-01-19 22:00:00'), Timestamp('2016-01-19 23:00:00'), Timestamp('2016-01-20 00:00:00'), Timestamp('2016-01-20 01:00:00'), Timestamp('2016-01-20 02:00:00'), Timestamp('2016-01-20 03:00:00'), Timestamp('2016-01-20 04:00:00'), Timestamp('2016-01-20 05:00:00'), Timestamp('2016-01-20 06:00:00'), Timestamp('2016-01-20 07:00:00'), Timestamp('2016-01-20 08:00:00'), Timestamp('2016-01-20 09:00:00'), Timestamp('2016-01-20 10:00:00'), Timestamp('2016-01-20 11:00:00'), Timestamp('2016-01-20 12:00:00'), Timestamp('2016-01-20 13:00:00'), Timestamp('2016-01-20 14:00:00'), Timestamp('2016-01-20 15:00:00'), Timestamp('2016-01-20 16:00:00'), Timestamp('2016-01-20 17:00:00'), Timestamp('2016-01-20 18:00:00'), Timestamp('2016-01-20 19:00:00'), Timestamp('2016-01-20 20:00:00'), Timestamp('2016-01-20 21:00:00'), Timestamp('2016-01-20 22:00:00'), Timestamp('2016-01-20 23:00:00'), Timestamp('2016-01-21 00:00:00'), Timestamp('2016-01-21 01:00:00'), Timestamp('2016-01-21 02:00:00'), Timestamp('2016-01-21 03:00:00'), Timestamp('2016-01-21 04:00:00'), Timestamp('2016-01-21 05:00:00'), Timestamp('2016-01-21 06:00:00'), Timestamp('2016-01-21 07:00:00'), Timestamp('2016-01-21 08:00:00'), Timestamp('2016-01-21 09:00:00'), Timestamp('2016-01-21 10:00:00'), Timestamp('2016-01-21 11:00:00'), Timestamp('2016-01-21 12:00:00'), Timestamp('2016-01-21 13:00:00'), Timestamp('2016-01-21 14:00:00'), Timestamp('2016-01-21 15:00:00'), Timestamp('2016-01-21 16:00:00'), Timestamp('2016-01-21 17:00:00'), Timestamp('2016-01-21 18:00:00'), Timestamp('2016-01-21 19:00:00'), Timestamp('2016-01-21 20:00:00'), Timestamp('2016-01-21 21:00:00'), Timestamp('2016-01-21 22:00:00'), Timestamp('2016-01-21 23:00:00'), Timestamp('2016-01-22 00:00:00'), Timestamp('2016-01-22 01:00:00'), Timestamp('2016-01-22 02:00:00'), Timestamp('2016-01-22 03:00:00'), Timestamp('2016-01-22 04:00:00'), Timestamp('2016-01-22 05:00:00'), Timestamp('2016-01-22 06:00:00'), Timestamp('2016-01-22 07:00:00'), Timestamp('2016-01-22 08:00:00'), Timestamp('2016-01-22 09:00:00'), Timestamp('2016-01-22 10:00:00'), Timestamp('2016-01-22 11:00:00'), Timestamp('2016-01-22 12:00:00'), Timestamp('2016-01-22 13:00:00'), Timestamp('2016-01-22 14:00:00'), Timestamp('2016-01-22 15:00:00'), Timestamp('2016-01-22 16:00:00'), Timestamp('2016-01-22 17:00:00'), Timestamp('2016-01-22 18:00:00'), Timestamp('2016-01-22 19:00:00'), Timestamp('2016-01-22 20:00:00'), Timestamp('2016-01-22 21:00:00'), Timestamp('2016-01-22 22:00:00'), Timestamp('2016-01-22 23:00:00'), Timestamp('2016-01-23 00:00:00'), Timestamp('2016-01-23 01:00:00'), Timestamp('2016-01-23 02:00:00'), Timestamp('2016-01-23 03:00:00'), Timestamp('2016-01-23 04:00:00'), Timestamp('2016-01-23 05:00:00'), Timestamp('2016-01-23 06:00:00'), Timestamp('2016-01-23 07:00:00'), Timestamp('2016-01-23 08:00:00'), Timestamp('2016-01-23 09:00:00'), Timestamp('2016-01-23 10:00:00'), Timestamp('2016-01-23 11:00:00'), Timestamp('2016-01-23 12:00:00'), Timestamp('2016-01-23 13:00:00'), Timestamp('2016-01-23 14:00:00'), Timestamp('2016-01-23 15:00:00'), Timestamp('2016-01-23 16:00:00'), Timestamp('2016-01-23 17:00:00'), Timestamp('2016-01-23 18:00:00'), Timestamp('2016-01-23 19:00:00'), Timestamp('2016-01-23 20:00:00'), Timestamp('2016-01-23 21:00:00'), Timestamp('2016-01-23 22:00:00'), Timestamp('2016-01-23 23:00:00'), Timestamp('2016-01-24 00:00:00'), Timestamp('2016-01-24 01:00:00'), Timestamp('2016-01-24 02:00:00'), Timestamp('2016-01-24 03:00:00'), Timestamp('2016-01-24 04:00:00'), Timestamp('2016-01-24 05:00:00'), Timestamp('2016-01-24 06:00:00'), Timestamp('2016-01-24 07:00:00'), Timestamp('2016-01-24 08:00:00'), Timestamp('2016-01-24 09:00:00'), Timestamp('2016-01-24 10:00:00'), Timestamp('2016-01-24 11:00:00'), Timestamp('2016-01-24 12:00:00'), Timestamp('2016-01-24 13:00:00'), Timestamp('2016-01-24 14:00:00'), Timestamp('2016-01-24 15:00:00'), Timestamp('2016-01-24 16:00:00'), Timestamp('2016-01-24 17:00:00'), Timestamp('2016-01-24 18:00:00'), Timestamp('2016-01-24 19:00:00'), Timestamp('2016-01-24 20:00:00'), Timestamp('2016-01-24 21:00:00'), Timestamp('2016-01-24 22:00:00'), Timestamp('2016-01-24 23:00:00'), Timestamp('2016-01-25 00:00:00'), Timestamp('2016-01-25 01:00:00'), Timestamp('2016-01-25 02:00:00'), Timestamp('2016-01-25 03:00:00'), Timestamp('2016-01-25 04:00:00'), Timestamp('2016-01-25 05:00:00'), Timestamp('2016-01-25 06:00:00'), Timestamp('2016-01-25 07:00:00'), Timestamp('2016-01-25 08:00:00'), Timestamp('2016-01-25 09:00:00'), Timestamp('2016-01-25 10:00:00'), Timestamp('2016-01-25 11:00:00'), Timestamp('2016-01-25 12:00:00'), Timestamp('2016-01-25 13:00:00'), Timestamp('2016-01-25 14:00:00'), Timestamp('2016-01-25 15:00:00'), Timestamp('2016-01-25 16:00:00'), Timestamp('2016-01-25 17:00:00'), Timestamp('2016-01-25 18:00:00'), Timestamp('2016-01-25 19:00:00'), Timestamp('2016-01-25 20:00:00'), Timestamp('2016-01-25 21:00:00'), Timestamp('2016-01-25 22:00:00'), Timestamp('2016-01-25 23:00:00'), Timestamp('2016-01-26 00:00:00'), Timestamp('2016-01-26 01:00:00'), Timestamp('2016-01-26 02:00:00'), Timestamp('2016-01-26 03:00:00'), Timestamp('2016-01-26 04:00:00'), Timestamp('2016-01-26 05:00:00'), Timestamp('2016-01-26 06:00:00'), Timestamp('2016-01-26 07:00:00'), Timestamp('2016-01-26 08:00:00'), Timestamp('2016-01-26 09:00:00'), Timestamp('2016-01-26 10:00:00'), Timestamp('2016-01-26 11:00:00'), Timestamp('2016-01-26 12:00:00'), Timestamp('2016-01-26 13:00:00'), Timestamp('2016-01-26 14:00:00'), Timestamp('2016-01-26 15:00:00'), Timestamp('2016-01-26 16:00:00'), Timestamp('2016-01-26 17:00:00'), Timestamp('2016-01-26 18:00:00'), Timestamp('2016-01-26 19:00:00'), Timestamp('2016-01-26 20:00:00'), Timestamp('2016-01-26 21:00:00'), Timestamp('2016-01-26 22:00:00'), Timestamp('2016-01-26 23:00:00'), Timestamp('2016-01-27 00:00:00'), Timestamp('2016-01-27 01:00:00'), Timestamp('2016-01-27 02:00:00'), Timestamp('2016-01-27 03:00:00'), Timestamp('2016-01-27 04:00:00'), Timestamp('2016-01-27 05:00:00'), Timestamp('2016-01-27 06:00:00'), Timestamp('2016-01-27 07:00:00'), Timestamp('2016-01-27 08:00:00'), Timestamp('2016-01-27 09:00:00'), Timestamp('2016-01-27 10:00:00'), Timestamp('2016-01-27 11:00:00'), Timestamp('2016-01-27 12:00:00'), Timestamp('2016-01-27 13:00:00'), Timestamp('2016-01-27 14:00:00'), Timestamp('2016-01-27 15:00:00'), Timestamp('2016-01-27 16:00:00'), Timestamp('2016-01-27 17:00:00'), Timestamp('2016-01-27 18:00:00'), Timestamp('2016-01-27 19:00:00'), Timestamp('2016-01-27 20:00:00'), Timestamp('2016-01-27 21:00:00'), Timestamp('2016-01-27 22:00:00'), Timestamp('2016-01-27 23:00:00'), Timestamp('2016-01-28 00:00:00'), Timestamp('2016-01-28 01:00:00'), Timestamp('2016-01-28 02:00:00'), Timestamp('2016-01-28 03:00:00'), Timestamp('2016-01-28 04:00:00'), Timestamp('2016-01-28 05:00:00'), Timestamp('2016-01-28 06:00:00'), Timestamp('2016-01-28 07:00:00'), Timestamp('2016-01-28 08:00:00'), Timestamp('2016-01-28 09:00:00'), Timestamp('2016-01-28 10:00:00'), Timestamp('2016-01-28 11:00:00'), Timestamp('2016-01-28 12:00:00'), Timestamp('2016-01-28 13:00:00'), Timestamp('2016-01-28 14:00:00'), Timestamp('2016-01-28 15:00:00'), Timestamp('2016-01-28 16:00:00'), Timestamp('2016-01-28 17:00:00'), Timestamp('2016-01-28 18:00:00'), Timestamp('2016-01-28 19:00:00'), Timestamp('2016-01-28 20:00:00'), Timestamp('2016-01-28 21:00:00'), Timestamp('2016-01-28 22:00:00'), Timestamp('2016-01-28 23:00:00'), Timestamp('2016-01-29 00:00:00'), Timestamp('2016-01-29 01:00:00'), Timestamp('2016-01-29 02:00:00'), Timestamp('2016-01-29 03:00:00'), Timestamp('2016-01-29 04:00:00'), Timestamp('2016-01-29 05:00:00'), Timestamp('2016-01-29 06:00:00'), Timestamp('2016-01-29 07:00:00'), Timestamp('2016-01-29 08:00:00'), Timestamp('2016-01-29 09:00:00'), Timestamp('2016-01-29 10:00:00'), Timestamp('2016-01-29 11:00:00'), Timestamp('2016-01-29 12:00:00'), Timestamp('2016-01-29 13:00:00'), Timestamp('2016-01-29 14:00:00'), Timestamp('2016-01-29 15:00:00'), Timestamp('2016-01-29 16:00:00'), Timestamp('2016-01-29 17:00:00'), Timestamp('2016-01-29 18:00:00'), Timestamp('2016-01-29 19:00:00'), Timestamp('2016-01-29 20:00:00'), Timestamp('2016-01-29 21:00:00'), Timestamp('2016-01-29 22:00:00'), Timestamp('2016-01-29 23:00:00'), Timestamp('2016-01-30 00:00:00'), Timestamp('2016-01-30 01:00:00'), Timestamp('2016-01-30 02:00:00'), Timestamp('2016-01-30 03:00:00'), Timestamp('2016-01-30 04:00:00'), Timestamp('2016-01-30 05:00:00'), Timestamp('2016-01-30 06:00:00'), Timestamp('2016-01-30 07:00:00'), Timestamp('2016-01-30 08:00:00'), Timestamp('2016-01-30 09:00:00'), Timestamp('2016-01-30 10:00:00'), Timestamp('2016-01-30 11:00:00'), Timestamp('2016-01-30 12:00:00'), Timestamp('2016-01-30 13:00:00'), Timestamp('2016-01-30 14:00:00'), Timestamp('2016-01-30 15:00:00'), Timestamp('2016-01-30 16:00:00'), Timestamp('2016-01-30 17:00:00'), Timestamp('2016-01-30 18:00:00'), Timestamp('2016-01-30 19:00:00'), Timestamp('2016-01-30 20:00:00'), Timestamp('2016-01-30 21:00:00'), Timestamp('2016-01-30 22:00:00'), Timestamp('2016-01-30 23:00:00'), Timestamp('2016-01-31 00:00:00'), Timestamp('2016-01-31 01:00:00'), Timestamp('2016-01-31 02:00:00'), Timestamp('2016-01-31 03:00:00'), Timestamp('2016-01-31 04:00:00'), Timestamp('2016-01-31 05:00:00'), Timestamp('2016-01-31 06:00:00'), Timestamp('2016-01-31 07:00:00'), Timestamp('2016-01-31 08:00:00'), Timestamp('2016-01-31 09:00:00'), Timestamp('2016-01-31 10:00:00'), Timestamp('2016-01-31 11:00:00'), Timestamp('2016-01-31 12:00:00'), Timestamp('2016-01-31 13:00:00'), Timestamp('2016-01-31 14:00:00'), Timestamp('2016-01-31 15:00:00'), Timestamp('2016-01-31 16:00:00'), Timestamp('2016-01-31 17:00:00'), Timestamp('2016-01-31 18:00:00'), Timestamp('2016-01-31 19:00:00'), Timestamp('2016-01-31 20:00:00'), Timestamp('2016-01-31 21:00:00'), Timestamp('2016-01-31 22:00:00'), Timestamp('2016-01-31 23:00:00'), Timestamp('2016-02-01 00:00:00'), Timestamp('2016-02-01 01:00:00'), Timestamp('2016-02-01 02:00:00'), Timestamp('2016-02-01 03:00:00'), Timestamp('2016-02-01 04:00:00'), Timestamp('2016-02-01 05:00:00'), Timestamp('2016-02-01 06:00:00'), Timestamp('2016-02-01 07:00:00'), Timestamp('2016-02-01 08:00:00'), Timestamp('2016-02-01 09:00:00'), Timestamp('2016-02-01 10:00:00'), Timestamp('2016-02-01 11:00:00'), Timestamp('2016-02-01 12:00:00'), Timestamp('2016-02-01 13:00:00'), Timestamp('2016-02-01 14:00:00'), Timestamp('2016-02-01 15:00:00'), Timestamp('2016-02-01 16:00:00'), Timestamp('2016-02-01 17:00:00'), Timestamp('2016-02-01 18:00:00'), Timestamp('2016-02-01 19:00:00'), Timestamp('2016-02-01 20:00:00'), Timestamp('2016-02-01 21:00:00'), Timestamp('2016-02-01 22:00:00'), Timestamp('2016-02-01 23:00:00'), Timestamp('2016-02-02 00:00:00'), Timestamp('2016-02-02 01:00:00'), Timestamp('2016-02-02 02:00:00'), Timestamp('2016-02-02 03:00:00'), Timestamp('2016-02-02 04:00:00'), Timestamp('2016-02-02 05:00:00'), Timestamp('2016-02-02 06:00:00'), Timestamp('2016-02-02 07:00:00'), Timestamp('2016-02-02 08:00:00'), Timestamp('2016-02-02 09:00:00'), Timestamp('2016-02-02 10:00:00'), Timestamp('2016-02-02 11:00:00'), Timestamp('2016-02-02 12:00:00'), Timestamp('2016-02-02 13:00:00'), Timestamp('2016-02-02 14:00:00'), Timestamp('2016-02-02 15:00:00'), Timestamp('2016-02-02 16:00:00'), Timestamp('2016-02-02 17:00:00'), Timestamp('2016-02-02 18:00:00'), Timestamp('2016-02-02 19:00:00'), Timestamp('2016-02-02 20:00:00'), Timestamp('2016-02-02 21:00:00'), Timestamp('2016-02-02 22:00:00'), Timestamp('2016-02-02 23:00:00'), Timestamp('2016-02-03 00:00:00'), Timestamp('2016-02-03 01:00:00'), Timestamp('2016-02-03 02:00:00'), Timestamp('2016-02-03 03:00:00'), Timestamp('2016-02-03 04:00:00'), Timestamp('2016-02-03 05:00:00'), Timestamp('2016-02-03 06:00:00'), Timestamp('2016-02-03 07:00:00'), Timestamp('2016-02-03 08:00:00'), Timestamp('2016-02-03 09:00:00'), Timestamp('2016-02-03 10:00:00'), Timestamp('2016-02-03 11:00:00'), Timestamp('2016-02-03 12:00:00'), Timestamp('2016-02-03 13:00:00'), Timestamp('2016-02-03 14:00:00'), Timestamp('2016-02-03 15:00:00'), Timestamp('2016-02-03 16:00:00'), Timestamp('2016-02-03 17:00:00'), Timestamp('2016-02-03 18:00:00'), Timestamp('2016-02-03 19:00:00'), Timestamp('2016-02-03 20:00:00'), Timestamp('2016-02-03 21:00:00'), Timestamp('2016-02-03 22:00:00'), Timestamp('2016-02-03 23:00:00'), Timestamp('2016-02-04 00:00:00'), Timestamp('2016-02-04 01:00:00'), Timestamp('2016-02-04 02:00:00'), Timestamp('2016-02-04 03:00:00'), Timestamp('2016-02-04 04:00:00'), Timestamp('2016-02-04 05:00:00'), Timestamp('2016-02-04 06:00:00'), Timestamp('2016-02-04 07:00:00'), Timestamp('2016-02-04 08:00:00'), Timestamp('2016-02-04 09:00:00'), Timestamp('2016-02-04 10:00:00'), Timestamp('2016-02-04 11:00:00'), Timestamp('2016-02-04 12:00:00'), Timestamp('2016-02-04 13:00:00'), Timestamp('2016-02-04 14:00:00'), Timestamp('2016-02-04 15:00:00'), Timestamp('2016-02-04 16:00:00'), Timestamp('2016-02-04 17:00:00'), Timestamp('2016-02-04 18:00:00'), Timestamp('2016-02-04 19:00:00'), Timestamp('2016-02-04 20:00:00'), Timestamp('2016-02-04 21:00:00'), Timestamp('2016-02-04 22:00:00'), Timestamp('2016-02-04 23:00:00'), Timestamp('2016-02-05 00:00:00'), Timestamp('2016-02-05 01:00:00'), Timestamp('2016-02-05 02:00:00'), Timestamp('2016-02-05 03:00:00'), Timestamp('2016-02-05 04:00:00'), Timestamp('2016-02-05 05:00:00'), Timestamp('2016-02-05 06:00:00'), Timestamp('2016-02-05 07:00:00'), Timestamp('2016-02-05 08:00:00'), Timestamp('2016-02-05 09:00:00'), Timestamp('2016-02-05 10:00:00'), Timestamp('2016-02-05 11:00:00'), Timestamp('2016-02-05 12:00:00'), Timestamp('2016-02-05 13:00:00'), Timestamp('2016-02-05 14:00:00'), Timestamp('2016-02-05 15:00:00'), Timestamp('2016-02-05 16:00:00'), Timestamp('2016-02-05 17:00:00'), Timestamp('2016-02-05 18:00:00'), Timestamp('2016-02-05 19:00:00'), Timestamp('2016-02-05 20:00:00'), Timestamp('2016-02-05 21:00:00'), Timestamp('2016-02-05 22:00:00'), Timestamp('2016-02-05 23:00:00'), Timestamp('2016-02-06 00:00:00'), Timestamp('2016-02-06 01:00:00'), Timestamp('2016-02-06 02:00:00'), Timestamp('2016-02-06 03:00:00'), Timestamp('2016-02-06 04:00:00'), Timestamp('2016-02-06 05:00:00'), Timestamp('2016-02-06 06:00:00'), Timestamp('2016-02-06 07:00:00'), Timestamp('2016-02-06 08:00:00'), Timestamp('2016-02-06 09:00:00'), Timestamp('2016-02-06 10:00:00'), Timestamp('2016-02-06 11:00:00'), Timestamp('2016-02-06 12:00:00'), Timestamp('2016-02-06 13:00:00'), Timestamp('2016-02-06 14:00:00'), Timestamp('2016-02-06 15:00:00'), Timestamp('2016-02-06 16:00:00'), Timestamp('2016-02-06 17:00:00'), Timestamp('2016-02-06 18:00:00'), Timestamp('2016-02-06 19:00:00'), Timestamp('2016-02-06 20:00:00'), Timestamp('2016-02-06 21:00:00'), Timestamp('2016-02-06 22:00:00'), Timestamp('2016-02-06 23:00:00'), Timestamp('2016-02-07 00:00:00'), Timestamp('2016-02-07 01:00:00'), Timestamp('2016-02-07 02:00:00'), Timestamp('2016-02-07 03:00:00'), Timestamp('2016-02-07 04:00:00'), Timestamp('2016-02-07 05:00:00'), Timestamp('2016-02-07 06:00:00'), Timestamp('2016-02-07 07:00:00'), Timestamp('2016-02-07 08:00:00'), Timestamp('2016-02-07 09:00:00'), Timestamp('2016-02-07 10:00:00'), Timestamp('2016-02-07 11:00:00'), Timestamp('2016-02-07 12:00:00'), Timestamp('2016-02-07 13:00:00'), Timestamp('2016-02-07 14:00:00'), Timestamp('2016-02-07 15:00:00'), Timestamp('2016-02-07 16:00:00'), Timestamp('2016-02-07 17:00:00'), Timestamp('2016-02-07 18:00:00'), Timestamp('2016-02-07 19:00:00'), Timestamp('2016-02-07 20:00:00'), Timestamp('2016-02-07 21:00:00'), Timestamp('2016-02-07 22:00:00'), Timestamp('2016-02-07 23:00:00'), Timestamp('2016-02-08 00:00:00'), Timestamp('2016-02-08 01:00:00'), Timestamp('2016-02-08 02:00:00'), Timestamp('2016-02-08 03:00:00'), Timestamp('2016-02-08 04:00:00'), Timestamp('2016-02-08 05:00:00'), Timestamp('2016-02-08 06:00:00'), Timestamp('2016-02-08 07:00:00'), Timestamp('2016-02-08 08:00:00'), Timestamp('2016-02-08 09:00:00'), Timestamp('2016-02-08 10:00:00'), Timestamp('2016-02-08 11:00:00'), Timestamp('2016-02-08 12:00:00'), Timestamp('2016-02-08 13:00:00'), Timestamp('2016-02-08 14:00:00'), Timestamp('2016-02-08 15:00:00'), Timestamp('2016-02-08 16:00:00'), Timestamp('2016-02-08 17:00:00'), Timestamp('2016-02-08 18:00:00'), Timestamp('2016-02-08 19:00:00'), Timestamp('2016-02-08 20:00:00'), Timestamp('2016-02-08 21:00:00'), Timestamp('2016-02-08 22:00:00'), Timestamp('2016-02-08 23:00:00'), Timestamp('2016-02-09 00:00:00'), Timestamp('2016-02-09 01:00:00'), Timestamp('2016-02-09 02:00:00'), Timestamp('2016-02-09 03:00:00'), Timestamp('2016-02-09 04:00:00'), Timestamp('2016-02-09 05:00:00'), Timestamp('2016-02-09 06:00:00'), Timestamp('2016-02-09 07:00:00'), Timestamp('2016-02-09 08:00:00'), Timestamp('2016-02-09 09:00:00'), Timestamp('2016-02-09 10:00:00'), Timestamp('2016-02-09 11:00:00'), Timesta

In [1317]:
# Daten laden Estermannufer_2018
df = pd.read_csv("../Projektdatensaetze_angepasst/2018/Estermannufer2018.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')



# Index setzen
df = df.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()

# in Liste speichern
estermannufer = estermannufer + df[('Estermannufer')].values.tolist()

In [1318]:
# Daten laden Kennedybrücke_2018
df  = pd.read_csv("../Projektdatensaetze_angepasst/2018/Kennedybruecke(Nord)2018.csv")
df1 = pd.read_csv("../Projektdatensaetze_angepasst/2018/Kennedybruecke(Sued)2018.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')
df1['time'] = pd.to_datetime(df1['time'])
df1['time'] = pd.to_datetime(df1['time'], format = '%Y-%m-%d %H:%M:%S')


# Index setzen
df = df.set_index('time')
df1 = df1.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()
df1 = df1.resample('h').sum()


# korrekt benennen
df['Kennedybruecke'] = df['Kennedybruecke (Nord) Ri. Beuel'] + df['Kennedybruecke (Nord) Ri. Innenstadt'] + df1['Kennedybruecke (Sued) Barometer']

# in Liste speichern
kennedybruecke = kennedybruecke + df['Kennedybruecke'].values.tolist()

In [1319]:
# Daten laden Nordbruecke_2018
df  = pd.read_csv("../Projektdatensaetze_angepasst/2018/Nordbruecke(Nord)2018.csv")
df1 = pd.read_csv("../Projektdatensaetze_angepasst/2018/Nordbruecke(Sued)2018.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')
df1['time'] = pd.to_datetime(df1['time'])
df1['time'] = pd.to_datetime(df1['time'], format = '%Y-%m-%d %H:%M:%S')


# Index setzen
df = df.set_index('time')
df1 = df1.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()
df1 = df1.resample('h').sum()


# korrekt benennen
df['Nordbruecke'] = df['Nordbruecke (Nord)'] + df1['Nordbruecke (Sued)']

# in Liste speichern
nordbruecke = nordbruecke + df['Nordbruecke'].values.tolist()

In [1320]:
# Daten laden Suedbruecke_2018
df  = pd.read_csv("../Projektdatensaetze_angepasst/2018/Suedbruecke(Nord)2018.csv")
df1 = pd.read_csv("../Projektdatensaetze_angepasst/2018/Suedbruecke(Sued)2018.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')
df1['time'] = pd.to_datetime(df1['time'])
df1['time'] = pd.to_datetime(df1['time'], format = '%Y-%m-%d %H:%M:%S')



# Index setzen
df = df.set_index('time')
df1 = df1.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()
df1 = df1.resample('h').sum()


# korrekt benennen
df['Suedbruecke'] = df['Suedbruecke (Nord)'] + df1['Suedbruecke (Sued)']

# in Liste speichern
suedbruecke = suedbruecke + df['Suedbruecke'].values.tolist()

In [1321]:
# Daten laden Rhenusallee_2018
df = pd.read_csv("../Projektdatensaetze_angepasst/2018/Rhenusallee2018.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')


# Index setzen
df = df.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()

# in Liste speichern
rhenusallee = rhenusallee + df[('Rhenusallee')].values.tolist()

In [1322]:
# Daten laden VonSandtUfer_2018
df = pd.read_csv("../Projektdatensaetze_angepasst/2018/VonSandtufer2018.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')


# Index setzen
df = df.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()

# in Liste speichern
von_sandt_ufer = von_sandt_ufer + df[('Von-Sandt-Ufer')].values.tolist()

In [1323]:
# Daten laden WegDammBonnBeuel_2018
df = pd.read_csv("../Projektdatensaetze_angepasst/2018/WegDammBonnBeuel2018.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')



# Index setzen
df = df.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()

# in Liste speichern
weg_auf_dem_damm = weg_auf_dem_damm + df[('Weg auf Damm Neil')].values.tolist()

In [1324]:
# Daten laden WilhelmSpiritusUfer_2018
df = pd.read_csv("../Projektdatensaetze_angepasst/2018/WilhelmSpiritusUfer2018.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')



# Index setzen
df = df.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()

# in Liste speichern
wilhelm_spiritus_ufer = wilhelm_spiritus_ufer + df[('Wilhelm-Spiritus-Ufer')].values.tolist()

In [1325]:
# Ausgabe der Listen um auf Länge zu testen 2018
print(len(zeitraum))
print(len(bruehler_straße))
print(len(estermannufer))
print(len(kennedybruecke))
print(len(nordbruecke))
print(len(suedbruecke))
print(len(rhenusallee))
print(len(von_sandt_ufer))
print(len(weg_auf_dem_damm))
print(len(wilhelm_spiritus_ufer))

25944
25944
25944
25944
25944
25944
25944
25944
25944
25944

In [1326]:
# Daten laden 2019
df = pd.read_csv("../Projektdatensaetze_angepasst/2019/FahrradmessstellenBonn2019.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')


# Index setzen
df = df.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()

# in Liste speichern
zeitraum = zeitraum + df.index.tolist()
bruehler_straße = bruehler_straße + df[('Bruehler Straße')].values.tolist()
estermannufer = estermannufer + df[('Estermannufer')].values.tolist()
kennedybruecke = kennedybruecke + df[('Kennedybruecke')].values.tolist()
nordbruecke = nordbruecke + df[('Nordbruecke')].values.tolist()
suedbruecke = suedbruecke + df[('Suedbruecke')].values.tolist()
rhenusallee = rhenusallee + df[('Rhenusallee')].values.tolist()
von_sandt_ufer = von_sandt_ufer + df[('Von-Sandt-Ufer')].values.tolist()
weg_auf_dem_damm = weg_auf_dem_damm + df[('Weg auf Damm Neil')].values.tolist()
wilhelm_spiritus_ufer = wilhelm_spiritus_ufer + df[('Wilhelm-Spiritus-Ufer')].values.tolist()
print(zeitraum)

[Timestamp('2016-01-16 00:00:00'), Timestamp('2016-01-16 01:00:00'), Timestamp('2016-01-16 02:00:00'), Timestamp('2016-01-16 03:00:00'), Timestamp('2016-01-16 04:00:00'), Timestamp('2016-01-16 05:00:00'), Timestamp('2016-01-16 06:00:00'), Timestamp('2016-01-16 07:00:00'), Timestamp('2016-01-16 08:00:00'), Timestamp('2016-01-16 09:00:00'), Timestamp('2016-01-16 10:00:00'), Timestamp('2016-01-16 11:00:00'), Timestamp('2016-01-16 12:00:00'), Timestamp('2016-01-16 13:00:00'), Timestamp('2016-01-16 14:00:00'), Timestamp('2016-01-16 15:00:00'), Timestamp('2016-01-16 16:00:00'), Timestamp('2016-01-16 17:00:00'), Timestamp('2016-01-16 18:00:00'), Timestamp('2016-01-16 19:00:00'), Timestamp('2016-01-16 20:00:00'), Timestamp('2016-01-16 21:00:00'), Timestamp('2016-01-16 22:00:00'), Timestamp('2016-01-16 23:00:00'), Timestamp('2016-01-17 00:00:00'), Timestamp('2016-01-17 01:00:00'), Timestamp('2016-01-17 02:00:00'), Timestamp('2016-01-17 03:00:00'), Timestamp('2016-01-17 04:00:00'), Timestamp('2016-01-17 05:00:00'), Timestamp('2016-01-17 06:00:00'), Timestamp('2016-01-17 07:00:00'), Timestamp('2016-01-17 08:00:00'), Timestamp('2016-01-17 09:00:00'), Timestamp('2016-01-17 10:00:00'), Timestamp('2016-01-17 11:00:00'), Timestamp('2016-01-17 12:00:00'), Timestamp('2016-01-17 13:00:00'), Timestamp('2016-01-17 14:00:00'), Timestamp('2016-01-17 15:00:00'), Timestamp('2016-01-17 16:00:00'), Timestamp('2016-01-17 17:00:00'), Timestamp('2016-01-17 18:00:00'), Timestamp('2016-01-17 19:00:00'), Timestamp('2016-01-17 20:00:00'), Timestamp('2016-01-17 21:00:00'), Timestamp('2016-01-17 22:00:00'), Timestamp('2016-01-17 23:00:00'), Timestamp('2016-01-18 00:00:00'), Timestamp('2016-01-18 01:00:00'), Timestamp('2016-01-18 02:00:00'), Timestamp('2016-01-18 03:00:00'), Timestamp('2016-01-18 04:00:00'), Timestamp('2016-01-18 05:00:00'), Timestamp('2016-01-18 06:00:00'), Timestamp('2016-01-18 07:00:00'), Timestamp('2016-01-18 08:00:00'), Timestamp('2016-01-18 09:00:00'), Timestamp('2016-01-18 10:00:00'), Timestamp('2016-01-18 11:00:00'), Timestamp('2016-01-18 12:00:00'), Timestamp('2016-01-18 13:00:00'), Timestamp('2016-01-18 14:00:00'), Timestamp('2016-01-18 15:00:00'), Timestamp('2016-01-18 16:00:00'), Timestamp('2016-01-18 17:00:00'), Timestamp('2016-01-18 18:00:00'), Timestamp('2016-01-18 19:00:00'), Timestamp('2016-01-18 20:00:00'), Timestamp('2016-01-18 21:00:00'), Timestamp('2016-01-18 22:00:00'), Timestamp('2016-01-18 23:00:00'), Timestamp('2016-01-19 00:00:00'), Timestamp('2016-01-19 01:00:00'), Timestamp('2016-01-19 02:00:00'), Timestamp('2016-01-19 03:00:00'), Timestamp('2016-01-19 04:00:00'), Timestamp('2016-01-19 05:00:00'), Timestamp('2016-01-19 06:00:00'), Timestamp('2016-01-19 07:00:00'), Timestamp('2016-01-19 08:00:00'), Timestamp('2016-01-19 09:00:00'), Timestamp('2016-01-19 10:00:00'), Timestamp('2016-01-19 11:00:00'), Timestamp('2016-01-19 12:00:00'), Timestamp('2016-01-19 13:00:00'), Timestamp('2016-01-19 14:00:00'), Timestamp('2016-01-19 15:00:00'), Timestamp('2016-01-19 16:00:00'), Timestamp('2016-01-19 17:00:00'), Timestamp('2016-01-19 18:00:00'), Timestamp('2016-01-19 19:00:00'), Timestamp('2016-01-19 20:00:00'), Timestamp('2016-01-19 21:00:00'), Timestamp('2016-01-19 22:00:00'), Timestamp('2016-01-19 23:00:00'), Timestamp('2016-01-20 00:00:00'), Timestamp('2016-01-20 01:00:00'), Timestamp('2016-01-20 02:00:00'), Timestamp('2016-01-20 03:00:00'), Timestamp('2016-01-20 04:00:00'), Timestamp('2016-01-20 05:00:00'), Timestamp('2016-01-20 06:00:00'), Timestamp('2016-01-20 07:00:00'), Timestamp('2016-01-20 08:00:00'), Timestamp('2016-01-20 09:00:00'), Timestamp('2016-01-20 10:00:00'), Timestamp('2016-01-20 11:00:00'), Timestamp('2016-01-20 12:00:00'), Timestamp('2016-01-20 13:00:00'), Timestamp('2016-01-20 14:00:00'), Timestamp('2016-01-20 15:00:00'), Timestamp('2016-01-20 16:00:00'), Timestamp('2016-01-20 17:00:00'), Timestamp('2016-01-20 18:00:00'), Timestamp('2016-01-20 19:00:00'), Timestamp('2016-01-20 20:00:00'), Timestamp('2016-01-20 21:00:00'), Timestamp('2016-01-20 22:00:00'), Timestamp('2016-01-20 23:00:00'), Timestamp('2016-01-21 00:00:00'), Timestamp('2016-01-21 01:00:00'), Timestamp('2016-01-21 02:00:00'), Timestamp('2016-01-21 03:00:00'), Timestamp('2016-01-21 04:00:00'), Timestamp('2016-01-21 05:00:00'), Timestamp('2016-01-21 06:00:00'), Timestamp('2016-01-21 07:00:00'), Timestamp('2016-01-21 08:00:00'), Timestamp('2016-01-21 09:00:00'), Timestamp('2016-01-21 10:00:00'), Timestamp('2016-01-21 11:00:00'), Timestamp('2016-01-21 12:00:00'), Timestamp('2016-01-21 13:00:00'), Timestamp('2016-01-21 14:00:00'), Timestamp('2016-01-21 15:00:00'), Timestamp('2016-01-21 16:00:00'), Timestamp('2016-01-21 17:00:00'), Timestamp('2016-01-21 18:00:00'), Timestamp('2016-01-21 19:00:00'), Timestamp('2016-01-21 20:00:00'), Timestamp('2016-01-21 21:00:00'), Timestamp('2016-01-21 22:00:00'), Timestamp('2016-01-21 23:00:00'), Timestamp('2016-01-22 00:00:00'), Timestamp('2016-01-22 01:00:00'), Timestamp('2016-01-22 02:00:00'), Timestamp('2016-01-22 03:00:00'), Timestamp('2016-01-22 04:00:00'), Timestamp('2016-01-22 05:00:00'), Timestamp('2016-01-22 06:00:00'), Timestamp('2016-01-22 07:00:00'), Timestamp('2016-01-22 08:00:00'), Timestamp('2016-01-22 09:00:00'), Timestamp('2016-01-22 10:00:00'), Timestamp('2016-01-22 11:00:00'), Timestamp('2016-01-22 12:00:00'), Timestamp('2016-01-22 13:00:00'), Timestamp('2016-01-22 14:00:00'), Timestamp('2016-01-22 15:00:00'), Timestamp('2016-01-22 16:00:00'), Timestamp('2016-01-22 17:00:00'), Timestamp('2016-01-22 18:00:00'), Timestamp('2016-01-22 19:00:00'), Timestamp('2016-01-22 20:00:00'), Timestamp('2016-01-22 21:00:00'), Timestamp('2016-01-22 22:00:00'), Timestamp('2016-01-22 23:00:00'), Timestamp('2016-01-23 00:00:00'), Timestamp('2016-01-23 01:00:00'), Timestamp('2016-01-23 02:00:00'), Timestamp('2016-01-23 03:00:00'), Timestamp('2016-01-23 04:00:00'), Timestamp('2016-01-23 05:00:00'), Timestamp('2016-01-23 06:00:00'), Timestamp('2016-01-23 07:00:00'), Timestamp('2016-01-23 08:00:00'), Timestamp('2016-01-23 09:00:00'), Timestamp('2016-01-23 10:00:00'), Timestamp('2016-01-23 11:00:00'), Timestamp('2016-01-23 12:00:00'), Timestamp('2016-01-23 13:00:00'), Timestamp('2016-01-23 14:00:00'), Timestamp('2016-01-23 15:00:00'), Timestamp('2016-01-23 16:00:00'), Timestamp('2016-01-23 17:00:00'), Timestamp('2016-01-23 18:00:00'), Timestamp('2016-01-23 19:00:00'), Timestamp('2016-01-23 20:00:00'), Timestamp('2016-01-23 21:00:00'), Timestamp('2016-01-23 22:00:00'), Timestamp('2016-01-23 23:00:00'), Timestamp('2016-01-24 00:00:00'), Timestamp('2016-01-24 01:00:00'), Timestamp('2016-01-24 02:00:00'), Timestamp('2016-01-24 03:00:00'), Timestamp('2016-01-24 04:00:00'), Timestamp('2016-01-24 05:00:00'), Timestamp('2016-01-24 06:00:00'), Timestamp('2016-01-24 07:00:00'), Timestamp('2016-01-24 08:00:00'), Timestamp('2016-01-24 09:00:00'), Timestamp('2016-01-24 10:00:00'), Timestamp('2016-01-24 11:00:00'), Timestamp('2016-01-24 12:00:00'), Timestamp('2016-01-24 13:00:00'), Timestamp('2016-01-24 14:00:00'), Timestamp('2016-01-24 15:00:00'), Timestamp('2016-01-24 16:00:00'), Timestamp('2016-01-24 17:00:00'), Timestamp('2016-01-24 18:00:00'), Timestamp('2016-01-24 19:00:00'), Timestamp('2016-01-24 20:00:00'), Timestamp('2016-01-24 21:00:00'), Timestamp('2016-01-24 22:00:00'), Timestamp('2016-01-24 23:00:00'), Timestamp('2016-01-25 00:00:00'), Timestamp('2016-01-25 01:00:00'), Timestamp('2016-01-25 02:00:00'), Timestamp('2016-01-25 03:00:00'), Timestamp('2016-01-25 04:00:00'), Timestamp('2016-01-25 05:00:00'), Timestamp('2016-01-25 06:00:00'), Timestamp('2016-01-25 07:00:00'), Timestamp('2016-01-25 08:00:00'), Timestamp('2016-01-25 09:00:00'), Timestamp('2016-01-25 10:00:00'), Timestamp('2016-01-25 11:00:00'), Timestamp('2016-01-25 12:00:00'), Timestamp('2016-01-25 13:00:00'), Timestamp('2016-01-25 14:00:00'), Timestamp('2016-01-25 15:00:00'), Timestamp('2016-01-25 16:00:00'), Timestamp('2016-01-25 17:00:00'), Timestamp('2016-01-25 18:00:00'), Timestamp('2016-01-25 19:00:00'), Timestamp('2016-01-25 20:00:00'), Timestamp('2016-01-25 21:00:00'), Timestamp('2016-01-25 22:00:00'), Timestamp('2016-01-25 23:00:00'), Timestamp('2016-01-26 00:00:00'), Timestamp('2016-01-26 01:00:00'), Timestamp('2016-01-26 02:00:00'), Timestamp('2016-01-26 03:00:00'), Timestamp('2016-01-26 04:00:00'), Timestamp('2016-01-26 05:00:00'), Timestamp('2016-01-26 06:00:00'), Timestamp('2016-01-26 07:00:00'), Timestamp('2016-01-26 08:00:00'), Timestamp('2016-01-26 09:00:00'), Timestamp('2016-01-26 10:00:00'), Timestamp('2016-01-26 11:00:00'), Timestamp('2016-01-26 12:00:00'), Timestamp('2016-01-26 13:00:00'), Timestamp('2016-01-26 14:00:00'), Timestamp('2016-01-26 15:00:00'), Timestamp('2016-01-26 16:00:00'), Timestamp('2016-01-26 17:00:00'), Timestamp('2016-01-26 18:00:00'), Timestamp('2016-01-26 19:00:00'), Timestamp('2016-01-26 20:00:00'), Timestamp('2016-01-26 21:00:00'), Timestamp('2016-01-26 22:00:00'), Timestamp('2016-01-26 23:00:00'), Timestamp('2016-01-27 00:00:00'), Timestamp('2016-01-27 01:00:00'), Timestamp('2016-01-27 02:00:00'), Timestamp('2016-01-27 03:00:00'), Timestamp('2016-01-27 04:00:00'), Timestamp('2016-01-27 05:00:00'), Timestamp('2016-01-27 06:00:00'), Timestamp('2016-01-27 07:00:00'), Timestamp('2016-01-27 08:00:00'), Timestamp('2016-01-27 09:00:00'), Timestamp('2016-01-27 10:00:00'), Timestamp('2016-01-27 11:00:00'), Timestamp('2016-01-27 12:00:00'), Timestamp('2016-01-27 13:00:00'), Timestamp('2016-01-27 14:00:00'), Timestamp('2016-01-27 15:00:00'), Timestamp('2016-01-27 16:00:00'), Timestamp('2016-01-27 17:00:00'), Timestamp('2016-01-27 18:00:00'), Timestamp('2016-01-27 19:00:00'), Timestamp('2016-01-27 20:00:00'), Timestamp('2016-01-27 21:00:00'), Timestamp('2016-01-27 22:00:00'), Timestamp('2016-01-27 23:00:00'), Timestamp('2016-01-28 00:00:00'), Timestamp('2016-01-28 01:00:00'), Timestamp('2016-01-28 02:00:00'), Timestamp('2016-01-28 03:00:00'), Timestamp('2016-01-28 04:00:00'), Timestamp('2016-01-28 05:00:00'), Timestamp('2016-01-28 06:00:00'), Timestamp('2016-01-28 07:00:00'), Timestamp('2016-01-28 08:00:00'), Timestamp('2016-01-28 09:00:00'), Timestamp('2016-01-28 10:00:00'), Timestamp('2016-01-28 11:00:00'), Timestamp('2016-01-28 12:00:00'), Timestamp('2016-01-28 13:00:00'), Timestamp('2016-01-28 14:00:00'), Timestamp('2016-01-28 15:00:00'), Timestamp('2016-01-28 16:00:00'), Timestamp('2016-01-28 17:00:00'), Timestamp('2016-01-28 18:00:00'), Timestamp('2016-01-28 19:00:00'), Timestamp('2016-01-28 20:00:00'), Timestamp('2016-01-28 21:00:00'), Timestamp('2016-01-28 22:00:00'), Timestamp('2016-01-28 23:00:00'), Timestamp('2016-01-29 00:00:00'), Timestamp('2016-01-29 01:00:00'), Timestamp('2016-01-29 02:00:00'), Timestamp('2016-01-29 03:00:00'), Timestamp('2016-01-29 04:00:00'), Timestamp('2016-01-29 05:00:00'), Timestamp('2016-01-29 06:00:00'), Timestamp('2016-01-29 07:00:00'), Timestamp('2016-01-29 08:00:00'), Timestamp('2016-01-29 09:00:00'), Timestamp('2016-01-29 10:00:00'), Timestamp('2016-01-29 11:00:00'), Timestamp('2016-01-29 12:00:00'), Timestamp('2016-01-29 13:00:00'), Timestamp('2016-01-29 14:00:00'), Timestamp('2016-01-29 15:00:00'), Timestamp('2016-01-29 16:00:00'), Timestamp('2016-01-29 17:00:00'), Timestamp('2016-01-29 18:00:00'), Timestamp('2016-01-29 19:00:00'), Timestamp('2016-01-29 20:00:00'), Timestamp('2016-01-29 21:00:00'), Timestamp('2016-01-29 22:00:00'), Timestamp('2016-01-29 23:00:00'), Timestamp('2016-01-30 00:00:00'), Timestamp('2016-01-30 01:00:00'), Timestamp('2016-01-30 02:00:00'), Timestamp('2016-01-30 03:00:00'), Timestamp('2016-01-30 04:00:00'), Timestamp('2016-01-30 05:00:00'), Timestamp('2016-01-30 06:00:00'), Timestamp('2016-01-30 07:00:00'), Timestamp('2016-01-30 08:00:00'), Timestamp('2016-01-30 09:00:00'), Timestamp('2016-01-30 10:00:00'), Timestamp('2016-01-30 11:00:00'), Timestamp('2016-01-30 12:00:00'), Timestamp('2016-01-30 13:00:00'), Timestamp('2016-01-30 14:00:00'), Timestamp('2016-01-30 15:00:00'), Timestamp('2016-01-30 16:00:00'), Timestamp('2016-01-30 17:00:00'), Timestamp('2016-01-30 18:00:00'), Timestamp('2016-01-30 19:00:00'), Timestamp('2016-01-30 20:00:00'), Timestamp('2016-01-30 21:00:00'), Timestamp('2016-01-30 22:00:00'), Timestamp('2016-01-30 23:00:00'), Timestamp('2016-01-31 00:00:00'), Timestamp('2016-01-31 01:00:00'), Timestamp('2016-01-31 02:00:00'), Timestamp('2016-01-31 03:00:00'), Timestamp('2016-01-31 04:00:00'), Timestamp('2016-01-31 05:00:00'), Timestamp('2016-01-31 06:00:00'), Timestamp('2016-01-31 07:00:00'), Timestamp('2016-01-31 08:00:00'), Timestamp('2016-01-31 09:00:00'), Timestamp('2016-01-31 10:00:00'), Timestamp('2016-01-31 11:00:00'), Timestamp('2016-01-31 12:00:00'), Timestamp('2016-01-31 13:00:00'), Timestamp('2016-01-31 14:00:00'), Timestamp('2016-01-31 15:00:00'), Timestamp('2016-01-31 16:00:00'), Timestamp('2016-01-31 17:00:00'), Timestamp('2016-01-31 18:00:00'), Timestamp('2016-01-31 19:00:00'), Timestamp('2016-01-31 20:00:00'), Timestamp('2016-01-31 21:00:00'), Timestamp('2016-01-31 22:00:00'), Timestamp('2016-01-31 23:00:00'), Timestamp('2016-02-01 00:00:00'), Timestamp('2016-02-01 01:00:00'), Timestamp('2016-02-01 02:00:00'), Timestamp('2016-02-01 03:00:00'), Timestamp('2016-02-01 04:00:00'), Timestamp('2016-02-01 05:00:00'), Timestamp('2016-02-01 06:00:00'), Timestamp('2016-02-01 07:00:00'), Timestamp('2016-02-01 08:00:00'), Timestamp('2016-02-01 09:00:00'), Timestamp('2016-02-01 10:00:00'), Timestamp('2016-02-01 11:00:00'), Timestamp('2016-02-01 12:00:00'), Timestamp('2016-02-01 13:00:00'), Timestamp('2016-02-01 14:00:00'), Timestamp('2016-02-01 15:00:00'), Timestamp('2016-02-01 16:00:00'), Timestamp('2016-02-01 17:00:00'), Timestamp('2016-02-01 18:00:00'), Timestamp('2016-02-01 19:00:00'), Timestamp('2016-02-01 20:00:00'), Timestamp('2016-02-01 21:00:00'), Timestamp('2016-02-01 22:00:00'), Timestamp('2016-02-01 23:00:00'), Timestamp('2016-02-02 00:00:00'), Timestamp('2016-02-02 01:00:00'), Timestamp('2016-02-02 02:00:00'), Timestamp('2016-02-02 03:00:00'), Timestamp('2016-02-02 04:00:00'), Timestamp('2016-02-02 05:00:00'), Timestamp('2016-02-02 06:00:00'), Timestamp('2016-02-02 07:00:00'), Timestamp('2016-02-02 08:00:00'), Timestamp('2016-02-02 09:00:00'), Timestamp('2016-02-02 10:00:00'), Timestamp('2016-02-02 11:00:00'), Timestamp('2016-02-02 12:00:00'), Timestamp('2016-02-02 13:00:00'), Timestamp('2016-02-02 14:00:00'), Timestamp('2016-02-02 15:00:00'), Timestamp('2016-02-02 16:00:00'), Timestamp('2016-02-02 17:00:00'), Timestamp('2016-02-02 18:00:00'), Timestamp('2016-02-02 19:00:00'), Timestamp('2016-02-02 20:00:00'), Timestamp('2016-02-02 21:00:00'), Timestamp('2016-02-02 22:00:00'), Timestamp('2016-02-02 23:00:00'), Timestamp('2016-02-03 00:00:00'), Timestamp('2016-02-03 01:00:00'), Timestamp('2016-02-03 02:00:00'), Timestamp('2016-02-03 03:00:00'), Timestamp('2016-02-03 04:00:00'), Timestamp('2016-02-03 05:00:00'), Timestamp('2016-02-03 06:00:00'), Timestamp('2016-02-03 07:00:00'), Timestamp('2016-02-03 08:00:00'), Timestamp('2016-02-03 09:00:00'), Timestamp('2016-02-03 10:00:00'), Timestamp('2016-02-03 11:00:00'), Timestamp('2016-02-03 12:00:00'), Timestamp('2016-02-03 13:00:00'), Timestamp('2016-02-03 14:00:00'), Timestamp('2016-02-03 15:00:00'), Timestamp('2016-02-03 16:00:00'), Timestamp('2016-02-03 17:00:00'), Timestamp('2016-02-03 18:00:00'), Timestamp('2016-02-03 19:00:00'), Timestamp('2016-02-03 20:00:00'), Timestamp('2016-02-03 21:00:00'), Timestamp('2016-02-03 22:00:00'), Timestamp('2016-02-03 23:00:00'), Timestamp('2016-02-04 00:00:00'), Timestamp('2016-02-04 01:00:00'), Timestamp('2016-02-04 02:00:00'), Timestamp('2016-02-04 03:00:00'), Timestamp('2016-02-04 04:00:00'), Timestamp('2016-02-04 05:00:00'), Timestamp('2016-02-04 06:00:00'), Timestamp('2016-02-04 07:00:00'), Timestamp('2016-02-04 08:00:00'), Timestamp('2016-02-04 09:00:00'), Timestamp('2016-02-04 10:00:00'), Timestamp('2016-02-04 11:00:00'), Timestamp('2016-02-04 12:00:00'), Timestamp('2016-02-04 13:00:00'), Timestamp('2016-02-04 14:00:00'), Timestamp('2016-02-04 15:00:00'), Timestamp('2016-02-04 16:00:00'), Timestamp('2016-02-04 17:00:00'), Timestamp('2016-02-04 18:00:00'), Timestamp('2016-02-04 19:00:00'), Timestamp('2016-02-04 20:00:00'), Timestamp('2016-02-04 21:00:00'), Timestamp('2016-02-04 22:00:00'), Timestamp('2016-02-04 23:00:00'), Timestamp('2016-02-05 00:00:00'), Timestamp('2016-02-05 01:00:00'), Timestamp('2016-02-05 02:00:00'), Timestamp('2016-02-05 03:00:00'), Timestamp('2016-02-05 04:00:00'), Timestamp('2016-02-05 05:00:00'), Timestamp('2016-02-05 06:00:00'), Timestamp('2016-02-05 07:00:00'), Timestamp('2016-02-05 08:00:00'), Timestamp('2016-02-05 09:00:00'), Timestamp('2016-02-05 10:00:00'), Timestamp('2016-02-05 11:00:00'), Timestamp('2016-02-05 12:00:00'), Timestamp('2016-02-05 13:00:00'), Timestamp('2016-02-05 14:00:00'), Timestamp('2016-02-05 15:00:00'), Timestamp('2016-02-05 16:00:00'), Timestamp('2016-02-05 17:00:00'), Timestamp('2016-02-05 18:00:00'), Timestamp('2016-02-05 19:00:00'), Timestamp('2016-02-05 20:00:00'), Timestamp('2016-02-05 21:00:00'), Timestamp('2016-02-05 22:00:00'), Timestamp('2016-02-05 23:00:00'), Timestamp('2016-02-06 00:00:00'), Timestamp('2016-02-06 01:00:00'), Timestamp('2016-02-06 02:00:00'), Timestamp('2016-02-06 03:00:00'), Timestamp('2016-02-06 04:00:00'), Timestamp('2016-02-06 05:00:00'), Timestamp('2016-02-06 06:00:00'), Timestamp('2016-02-06 07:00:00'), Timestamp('2016-02-06 08:00:00'), Timestamp('2016-02-06 09:00:00'), Timestamp('2016-02-06 10:00:00'), Timestamp('2016-02-06 11:00:00'), Timestamp('2016-02-06 12:00:00'), Timestamp('2016-02-06 13:00:00'), Timestamp('2016-02-06 14:00:00'), Timestamp('2016-02-06 15:00:00'), Timestamp('2016-02-06 16:00:00'), Timestamp('2016-02-06 17:00:00'), Timestamp('2016-02-06 18:00:00'), Timestamp('2016-02-06 19:00:00'), Timestamp('2016-02-06 20:00:00'), Timestamp('2016-02-06 21:00:00'), Timestamp('2016-02-06 22:00:00'), Timestamp('2016-02-06 23:00:00'), Timestamp('2016-02-07 00:00:00'), Timestamp('2016-02-07 01:00:00'), Timestamp('2016-02-07 02:00:00'), Timestamp('2016-02-07 03:00:00'), Timestamp('2016-02-07 04:00:00'), Timestamp('2016-02-07 05:00:00'), Timestamp('2016-02-07 06:00:00'), Timestamp('2016-02-07 07:00:00'), Timestamp('2016-02-07 08:00:00'), Timestamp('2016-02-07 09:00:00'), Timestamp('2016-02-07 10:00:00'), Timestamp('2016-02-07 11:00:00'), Timestamp('2016-02-07 12:00:00'), Timestamp('2016-02-07 13:00:00'), Timestamp('2016-02-07 14:00:00'), Timestamp('2016-02-07 15:00:00'), Timestamp('2016-02-07 16:00:00'), Timestamp('2016-02-07 17:00:00'), Timestamp('2016-02-07 18:00:00'), Timestamp('2016-02-07 19:00:00'), Timestamp('2016-02-07 20:00:00'), Timestamp('2016-02-07 21:00:00'), Timestamp('2016-02-07 22:00:00'), Timestamp('2016-02-07 23:00:00'), Timestamp('2016-02-08 00:00:00'), Timestamp('2016-02-08 01:00:00'), Timestamp('2016-02-08 02:00:00'), Timestamp('2016-02-08 03:00:00'), Timestamp('2016-02-08 04:00:00'), Timestamp('2016-02-08 05:00:00'), Timestamp('2016-02-08 06:00:00'), Timestamp('2016-02-08 07:00:00'), Timestamp('2016-02-08 08:00:00'), Timestamp('2016-02-08 09:00:00'), Timestamp('2016-02-08 10:00:00'), Timestamp('2016-02-08 11:00:00'), Timestamp('2016-02-08 12:00:00'), Timestamp('2016-02-08 13:00:00'), Timestamp('2016-02-08 14:00:00'), Timestamp('2016-02-08 15:00:00'), Timestamp('2016-02-08 16:00:00'), Timestamp('2016-02-08 17:00:00'), Timestamp('2016-02-08 18:00:00'), Timestamp('2016-02-08 19:00:00'), Timestamp('2016-02-08 20:00:00'), Timestamp('2016-02-08 21:00:00'), Timestamp('2016-02-08 22:00:00'), Timestamp('2016-02-08 23:00:00'), Timestamp('2016-02-09 00:00:00'), Timestamp('2016-02-09 01:00:00'), Timestamp('2016-02-09 02:00:00'), Timestamp('2016-02-09 03:00:00'), Timestamp('2016-02-09 04:00:00'), Timestamp('2016-02-09 05:00:00'), Timestamp('2016-02-09 06:00:00'), Timestamp('2016-02-09 07:00:00'), Timestamp('2016-02-09 08:00:00'), Timestamp('2016-02-09 09:00:00'), Timestamp('2016-02-09 10:00:00'), Timestamp('2016-02-09 11:00:00'), Timesta

In [1327]:
# Ausgabe der Listen um auf Länge zu testen 2019
print(len(zeitraum))
print(len(bruehler_straße))
print(len(estermannufer))
print(len(kennedybruecke))
print(len(nordbruecke))
print(len(suedbruecke))
print(len(rhenusallee))
print(len(von_sandt_ufer))
print(len(weg_auf_dem_damm))
print(len(wilhelm_spiritus_ufer))

34704
34704
34704
34704
34704
34704
34704
34704
34704
34704

In [1328]:
# Daten laden 2020
df = pd.read_csv("../Projektdatensaetze_angepasst/2020/FahrradmessstellenBonn2020_15MinAuswertung.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')



# Index setzen
df = df.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()

# in Liste speichern
zeitraum = zeitraum + df.index.tolist()
bruehler_straße = bruehler_straße + df[('Bruehler Straße')].values.tolist()
estermannufer = estermannufer + df[('Estermannufer')].values.tolist()
kennedybruecke = kennedybruecke + df[('Kennedybruecke')].values.tolist()
nordbruecke = nordbruecke + df[('Nordbruecke')].values.tolist()
suedbruecke = suedbruecke + df[('Suedbruecke')].values.tolist()
rhenusallee = rhenusallee + df[('Rhenusallee')].values.tolist()
von_sandt_ufer = von_sandt_ufer + df[('Von-Sandt-Ufer')].values.tolist()
weg_auf_dem_damm = weg_auf_dem_damm + df[('Weg auf Damm Neil')].values.tolist()
wilhelm_spiritus_ufer = wilhelm_spiritus_ufer + df[('Wilhelm-Spiritus-Ufer')].values.tolist()
print(zeitraum)

[Timestamp('2016-01-16 00:00:00'), Timestamp('2016-01-16 01:00:00'), Timestamp('2016-01-16 02:00:00'), Timestamp('2016-01-16 03:00:00'), Timestamp('2016-01-16 04:00:00'), Timestamp('2016-01-16 05:00:00'), Timestamp('2016-01-16 06:00:00'), Timestamp('2016-01-16 07:00:00'), Timestamp('2016-01-16 08:00:00'), Timestamp('2016-01-16 09:00:00'), Timestamp('2016-01-16 10:00:00'), Timestamp('2016-01-16 11:00:00'), Timestamp('2016-01-16 12:00:00'), Timestamp('2016-01-16 13:00:00'), Timestamp('2016-01-16 14:00:00'), Timestamp('2016-01-16 15:00:00'), Timestamp('2016-01-16 16:00:00'), Timestamp('2016-01-16 17:00:00'), Timestamp('2016-01-16 18:00:00'), Timestamp('2016-01-16 19:00:00'), Timestamp('2016-01-16 20:00:00'), Timestamp('2016-01-16 21:00:00'), Timestamp('2016-01-16 22:00:00'), Timestamp('2016-01-16 23:00:00'), Timestamp('2016-01-17 00:00:00'), Timestamp('2016-01-17 01:00:00'), Timestamp('2016-01-17 02:00:00'), Timestamp('2016-01-17 03:00:00'), Timestamp('2016-01-17 04:00:00'), Timestamp('2016-01-17 05:00:00'), Timestamp('2016-01-17 06:00:00'), Timestamp('2016-01-17 07:00:00'), Timestamp('2016-01-17 08:00:00'), Timestamp('2016-01-17 09:00:00'), Timestamp('2016-01-17 10:00:00'), Timestamp('2016-01-17 11:00:00'), Timestamp('2016-01-17 12:00:00'), Timestamp('2016-01-17 13:00:00'), Timestamp('2016-01-17 14:00:00'), Timestamp('2016-01-17 15:00:00'), Timestamp('2016-01-17 16:00:00'), Timestamp('2016-01-17 17:00:00'), Timestamp('2016-01-17 18:00:00'), Timestamp('2016-01-17 19:00:00'), Timestamp('2016-01-17 20:00:00'), Timestamp('2016-01-17 21:00:00'), Timestamp('2016-01-17 22:00:00'), Timestamp('2016-01-17 23:00:00'), Timestamp('2016-01-18 00:00:00'), Timestamp('2016-01-18 01:00:00'), Timestamp('2016-01-18 02:00:00'), Timestamp('2016-01-18 03:00:00'), Timestamp('2016-01-18 04:00:00'), Timestamp('2016-01-18 05:00:00'), Timestamp('2016-01-18 06:00:00'), Timestamp('2016-01-18 07:00:00'), Timestamp('2016-01-18 08:00:00'), Timestamp('2016-01-18 09:00:00'), Timestamp('2016-01-18 10:00:00'), Timestamp('2016-01-18 11:00:00'), Timestamp('2016-01-18 12:00:00'), Timestamp('2016-01-18 13:00:00'), Timestamp('2016-01-18 14:00:00'), Timestamp('2016-01-18 15:00:00'), Timestamp('2016-01-18 16:00:00'), Timestamp('2016-01-18 17:00:00'), Timestamp('2016-01-18 18:00:00'), Timestamp('2016-01-18 19:00:00'), Timestamp('2016-01-18 20:00:00'), Timestamp('2016-01-18 21:00:00'), Timestamp('2016-01-18 22:00:00'), Timestamp('2016-01-18 23:00:00'), Timestamp('2016-01-19 00:00:00'), Timestamp('2016-01-19 01:00:00'), Timestamp('2016-01-19 02:00:00'), Timestamp('2016-01-19 03:00:00'), Timestamp('2016-01-19 04:00:00'), Timestamp('2016-01-19 05:00:00'), Timestamp('2016-01-19 06:00:00'), Timestamp('2016-01-19 07:00:00'), Timestamp('2016-01-19 08:00:00'), Timestamp('2016-01-19 09:00:00'), Timestamp('2016-01-19 10:00:00'), Timestamp('2016-01-19 11:00:00'), Timestamp('2016-01-19 12:00:00'), Timestamp('2016-01-19 13:00:00'), Timestamp('2016-01-19 14:00:00'), Timestamp('2016-01-19 15:00:00'), Timestamp('2016-01-19 16:00:00'), Timestamp('2016-01-19 17:00:00'), Timestamp('2016-01-19 18:00:00'), Timestamp('2016-01-19 19:00:00'), Timestamp('2016-01-19 20:00:00'), Timestamp('2016-01-19 21:00:00'), Timestamp('2016-01-19 22:00:00'), Timestamp('2016-01-19 23:00:00'), Timestamp('2016-01-20 00:00:00'), Timestamp('2016-01-20 01:00:00'), Timestamp('2016-01-20 02:00:00'), Timestamp('2016-01-20 03:00:00'), Timestamp('2016-01-20 04:00:00'), Timestamp('2016-01-20 05:00:00'), Timestamp('2016-01-20 06:00:00'), Timestamp('2016-01-20 07:00:00'), Timestamp('2016-01-20 08:00:00'), Timestamp('2016-01-20 09:00:00'), Timestamp('2016-01-20 10:00:00'), Timestamp('2016-01-20 11:00:00'), Timestamp('2016-01-20 12:00:00'), Timestamp('2016-01-20 13:00:00'), Timestamp('2016-01-20 14:00:00'), Timestamp('2016-01-20 15:00:00'), Timestamp('2016-01-20 16:00:00'), Timestamp('2016-01-20 17:00:00'), Timestamp('2016-01-20 18:00:00'), Timestamp('2016-01-20 19:00:00'), Timestamp('2016-01-20 20:00:00'), Timestamp('2016-01-20 21:00:00'), Timestamp('2016-01-20 22:00:00'), Timestamp('2016-01-20 23:00:00'), Timestamp('2016-01-21 00:00:00'), Timestamp('2016-01-21 01:00:00'), Timestamp('2016-01-21 02:00:00'), Timestamp('2016-01-21 03:00:00'), Timestamp('2016-01-21 04:00:00'), Timestamp('2016-01-21 05:00:00'), Timestamp('2016-01-21 06:00:00'), Timestamp('2016-01-21 07:00:00'), Timestamp('2016-01-21 08:00:00'), Timestamp('2016-01-21 09:00:00'), Timestamp('2016-01-21 10:00:00'), Timestamp('2016-01-21 11:00:00'), Timestamp('2016-01-21 12:00:00'), Timestamp('2016-01-21 13:00:00'), Timestamp('2016-01-21 14:00:00'), Timestamp('2016-01-21 15:00:00'), Timestamp('2016-01-21 16:00:00'), Timestamp('2016-01-21 17:00:00'), Timestamp('2016-01-21 18:00:00'), Timestamp('2016-01-21 19:00:00'), Timestamp('2016-01-21 20:00:00'), Timestamp('2016-01-21 21:00:00'), Timestamp('2016-01-21 22:00:00'), Timestamp('2016-01-21 23:00:00'), Timestamp('2016-01-22 00:00:00'), Timestamp('2016-01-22 01:00:00'), Timestamp('2016-01-22 02:00:00'), Timestamp('2016-01-22 03:00:00'), Timestamp('2016-01-22 04:00:00'), Timestamp('2016-01-22 05:00:00'), Timestamp('2016-01-22 06:00:00'), Timestamp('2016-01-22 07:00:00'), Timestamp('2016-01-22 08:00:00'), Timestamp('2016-01-22 09:00:00'), Timestamp('2016-01-22 10:00:00'), Timestamp('2016-01-22 11:00:00'), Timestamp('2016-01-22 12:00:00'), Timestamp('2016-01-22 13:00:00'), Timestamp('2016-01-22 14:00:00'), Timestamp('2016-01-22 15:00:00'), Timestamp('2016-01-22 16:00:00'), Timestamp('2016-01-22 17:00:00'), Timestamp('2016-01-22 18:00:00'), Timestamp('2016-01-22 19:00:00'), Timestamp('2016-01-22 20:00:00'), Timestamp('2016-01-22 21:00:00'), Timestamp('2016-01-22 22:00:00'), Timestamp('2016-01-22 23:00:00'), Timestamp('2016-01-23 00:00:00'), Timestamp('2016-01-23 01:00:00'), Timestamp('2016-01-23 02:00:00'), Timestamp('2016-01-23 03:00:00'), Timestamp('2016-01-23 04:00:00'), Timestamp('2016-01-23 05:00:00'), Timestamp('2016-01-23 06:00:00'), Timestamp('2016-01-23 07:00:00'), Timestamp('2016-01-23 08:00:00'), Timestamp('2016-01-23 09:00:00'), Timestamp('2016-01-23 10:00:00'), Timestamp('2016-01-23 11:00:00'), Timestamp('2016-01-23 12:00:00'), Timestamp('2016-01-23 13:00:00'), Timestamp('2016-01-23 14:00:00'), Timestamp('2016-01-23 15:00:00'), Timestamp('2016-01-23 16:00:00'), Timestamp('2016-01-23 17:00:00'), Timestamp('2016-01-23 18:00:00'), Timestamp('2016-01-23 19:00:00'), Timestamp('2016-01-23 20:00:00'), Timestamp('2016-01-23 21:00:00'), Timestamp('2016-01-23 22:00:00'), Timestamp('2016-01-23 23:00:00'), Timestamp('2016-01-24 00:00:00'), Timestamp('2016-01-24 01:00:00'), Timestamp('2016-01-24 02:00:00'), Timestamp('2016-01-24 03:00:00'), Timestamp('2016-01-24 04:00:00'), Timestamp('2016-01-24 05:00:00'), Timestamp('2016-01-24 06:00:00'), Timestamp('2016-01-24 07:00:00'), Timestamp('2016-01-24 08:00:00'), Timestamp('2016-01-24 09:00:00'), Timestamp('2016-01-24 10:00:00'), Timestamp('2016-01-24 11:00:00'), Timestamp('2016-01-24 12:00:00'), Timestamp('2016-01-24 13:00:00'), Timestamp('2016-01-24 14:00:00'), Timestamp('2016-01-24 15:00:00'), Timestamp('2016-01-24 16:00:00'), Timestamp('2016-01-24 17:00:00'), Timestamp('2016-01-24 18:00:00'), Timestamp('2016-01-24 19:00:00'), Timestamp('2016-01-24 20:00:00'), Timestamp('2016-01-24 21:00:00'), Timestamp('2016-01-24 22:00:00'), Timestamp('2016-01-24 23:00:00'), Timestamp('2016-01-25 00:00:00'), Timestamp('2016-01-25 01:00:00'), Timestamp('2016-01-25 02:00:00'), Timestamp('2016-01-25 03:00:00'), Timestamp('2016-01-25 04:00:00'), Timestamp('2016-01-25 05:00:00'), Timestamp('2016-01-25 06:00:00'), Timestamp('2016-01-25 07:00:00'), Timestamp('2016-01-25 08:00:00'), Timestamp('2016-01-25 09:00:00'), Timestamp('2016-01-25 10:00:00'), Timestamp('2016-01-25 11:00:00'), Timestamp('2016-01-25 12:00:00'), Timestamp('2016-01-25 13:00:00'), Timestamp('2016-01-25 14:00:00'), Timestamp('2016-01-25 15:00:00'), Timestamp('2016-01-25 16:00:00'), Timestamp('2016-01-25 17:00:00'), Timestamp('2016-01-25 18:00:00'), Timestamp('2016-01-25 19:00:00'), Timestamp('2016-01-25 20:00:00'), Timestamp('2016-01-25 21:00:00'), Timestamp('2016-01-25 22:00:00'), Timestamp('2016-01-25 23:00:00'), Timestamp('2016-01-26 00:00:00'), Timestamp('2016-01-26 01:00:00'), Timestamp('2016-01-26 02:00:00'), Timestamp('2016-01-26 03:00:00'), Timestamp('2016-01-26 04:00:00'), Timestamp('2016-01-26 05:00:00'), Timestamp('2016-01-26 06:00:00'), Timestamp('2016-01-26 07:00:00'), Timestamp('2016-01-26 08:00:00'), Timestamp('2016-01-26 09:00:00'), Timestamp('2016-01-26 10:00:00'), Timestamp('2016-01-26 11:00:00'), Timestamp('2016-01-26 12:00:00'), Timestamp('2016-01-26 13:00:00'), Timestamp('2016-01-26 14:00:00'), Timestamp('2016-01-26 15:00:00'), Timestamp('2016-01-26 16:00:00'), Timestamp('2016-01-26 17:00:00'), Timestamp('2016-01-26 18:00:00'), Timestamp('2016-01-26 19:00:00'), Timestamp('2016-01-26 20:00:00'), Timestamp('2016-01-26 21:00:00'), Timestamp('2016-01-26 22:00:00'), Timestamp('2016-01-26 23:00:00'), Timestamp('2016-01-27 00:00:00'), Timestamp('2016-01-27 01:00:00'), Timestamp('2016-01-27 02:00:00'), Timestamp('2016-01-27 03:00:00'), Timestamp('2016-01-27 04:00:00'), Timestamp('2016-01-27 05:00:00'), Timestamp('2016-01-27 06:00:00'), Timestamp('2016-01-27 07:00:00'), Timestamp('2016-01-27 08:00:00'), Timestamp('2016-01-27 09:00:00'), Timestamp('2016-01-27 10:00:00'), Timestamp('2016-01-27 11:00:00'), Timestamp('2016-01-27 12:00:00'), Timestamp('2016-01-27 13:00:00'), Timestamp('2016-01-27 14:00:00'), Timestamp('2016-01-27 15:00:00'), Timestamp('2016-01-27 16:00:00'), Timestamp('2016-01-27 17:00:00'), Timestamp('2016-01-27 18:00:00'), Timestamp('2016-01-27 19:00:00'), Timestamp('2016-01-27 20:00:00'), Timestamp('2016-01-27 21:00:00'), Timestamp('2016-01-27 22:00:00'), Timestamp('2016-01-27 23:00:00'), Timestamp('2016-01-28 00:00:00'), Timestamp('2016-01-28 01:00:00'), Timestamp('2016-01-28 02:00:00'), Timestamp('2016-01-28 03:00:00'), Timestamp('2016-01-28 04:00:00'), Timestamp('2016-01-28 05:00:00'), Timestamp('2016-01-28 06:00:00'), Timestamp('2016-01-28 07:00:00'), Timestamp('2016-01-28 08:00:00'), Timestamp('2016-01-28 09:00:00'), Timestamp('2016-01-28 10:00:00'), Timestamp('2016-01-28 11:00:00'), Timestamp('2016-01-28 12:00:00'), Timestamp('2016-01-28 13:00:00'), Timestamp('2016-01-28 14:00:00'), Timestamp('2016-01-28 15:00:00'), Timestamp('2016-01-28 16:00:00'), Timestamp('2016-01-28 17:00:00'), Timestamp('2016-01-28 18:00:00'), Timestamp('2016-01-28 19:00:00'), Timestamp('2016-01-28 20:00:00'), Timestamp('2016-01-28 21:00:00'), Timestamp('2016-01-28 22:00:00'), Timestamp('2016-01-28 23:00:00'), Timestamp('2016-01-29 00:00:00'), Timestamp('2016-01-29 01:00:00'), Timestamp('2016-01-29 02:00:00'), Timestamp('2016-01-29 03:00:00'), Timestamp('2016-01-29 04:00:00'), Timestamp('2016-01-29 05:00:00'), Timestamp('2016-01-29 06:00:00'), Timestamp('2016-01-29 07:00:00'), Timestamp('2016-01-29 08:00:00'), Timestamp('2016-01-29 09:00:00'), Timestamp('2016-01-29 10:00:00'), Timestamp('2016-01-29 11:00:00'), Timestamp('2016-01-29 12:00:00'), Timestamp('2016-01-29 13:00:00'), Timestamp('2016-01-29 14:00:00'), Timestamp('2016-01-29 15:00:00'), Timestamp('2016-01-29 16:00:00'), Timestamp('2016-01-29 17:00:00'), Timestamp('2016-01-29 18:00:00'), Timestamp('2016-01-29 19:00:00'), Timestamp('2016-01-29 20:00:00'), Timestamp('2016-01-29 21:00:00'), Timestamp('2016-01-29 22:00:00'), Timestamp('2016-01-29 23:00:00'), Timestamp('2016-01-30 00:00:00'), Timestamp('2016-01-30 01:00:00'), Timestamp('2016-01-30 02:00:00'), Timestamp('2016-01-30 03:00:00'), Timestamp('2016-01-30 04:00:00'), Timestamp('2016-01-30 05:00:00'), Timestamp('2016-01-30 06:00:00'), Timestamp('2016-01-30 07:00:00'), Timestamp('2016-01-30 08:00:00'), Timestamp('2016-01-30 09:00:00'), Timestamp('2016-01-30 10:00:00'), Timestamp('2016-01-30 11:00:00'), Timestamp('2016-01-30 12:00:00'), Timestamp('2016-01-30 13:00:00'), Timestamp('2016-01-30 14:00:00'), Timestamp('2016-01-30 15:00:00'), Timestamp('2016-01-30 16:00:00'), Timestamp('2016-01-30 17:00:00'), Timestamp('2016-01-30 18:00:00'), Timestamp('2016-01-30 19:00:00'), Timestamp('2016-01-30 20:00:00'), Timestamp('2016-01-30 21:00:00'), Timestamp('2016-01-30 22:00:00'), Timestamp('2016-01-30 23:00:00'), Timestamp('2016-01-31 00:00:00'), Timestamp('2016-01-31 01:00:00'), Timestamp('2016-01-31 02:00:00'), Timestamp('2016-01-31 03:00:00'), Timestamp('2016-01-31 04:00:00'), Timestamp('2016-01-31 05:00:00'), Timestamp('2016-01-31 06:00:00'), Timestamp('2016-01-31 07:00:00'), Timestamp('2016-01-31 08:00:00'), Timestamp('2016-01-31 09:00:00'), Timestamp('2016-01-31 10:00:00'), Timestamp('2016-01-31 11:00:00'), Timestamp('2016-01-31 12:00:00'), Timestamp('2016-01-31 13:00:00'), Timestamp('2016-01-31 14:00:00'), Timestamp('2016-01-31 15:00:00'), Timestamp('2016-01-31 16:00:00'), Timestamp('2016-01-31 17:00:00'), Timestamp('2016-01-31 18:00:00'), Timestamp('2016-01-31 19:00:00'), Timestamp('2016-01-31 20:00:00'), Timestamp('2016-01-31 21:00:00'), Timestamp('2016-01-31 22:00:00'), Timestamp('2016-01-31 23:00:00'), Timestamp('2016-02-01 00:00:00'), Timestamp('2016-02-01 01:00:00'), Timestamp('2016-02-01 02:00:00'), Timestamp('2016-02-01 03:00:00'), Timestamp('2016-02-01 04:00:00'), Timestamp('2016-02-01 05:00:00'), Timestamp('2016-02-01 06:00:00'), Timestamp('2016-02-01 07:00:00'), Timestamp('2016-02-01 08:00:00'), Timestamp('2016-02-01 09:00:00'), Timestamp('2016-02-01 10:00:00'), Timestamp('2016-02-01 11:00:00'), Timestamp('2016-02-01 12:00:00'), Timestamp('2016-02-01 13:00:00'), Timestamp('2016-02-01 14:00:00'), Timestamp('2016-02-01 15:00:00'), Timestamp('2016-02-01 16:00:00'), Timestamp('2016-02-01 17:00:00'), Timestamp('2016-02-01 18:00:00'), Timestamp('2016-02-01 19:00:00'), Timestamp('2016-02-01 20:00:00'), Timestamp('2016-02-01 21:00:00'), Timestamp('2016-02-01 22:00:00'), Timestamp('2016-02-01 23:00:00'), Timestamp('2016-02-02 00:00:00'), Timestamp('2016-02-02 01:00:00'), Timestamp('2016-02-02 02:00:00'), Timestamp('2016-02-02 03:00:00'), Timestamp('2016-02-02 04:00:00'), Timestamp('2016-02-02 05:00:00'), Timestamp('2016-02-02 06:00:00'), Timestamp('2016-02-02 07:00:00'), Timestamp('2016-02-02 08:00:00'), Timestamp('2016-02-02 09:00:00'), Timestamp('2016-02-02 10:00:00'), Timestamp('2016-02-02 11:00:00'), Timestamp('2016-02-02 12:00:00'), Timestamp('2016-02-02 13:00:00'), Timestamp('2016-02-02 14:00:00'), Timestamp('2016-02-02 15:00:00'), Timestamp('2016-02-02 16:00:00'), Timestamp('2016-02-02 17:00:00'), Timestamp('2016-02-02 18:00:00'), Timestamp('2016-02-02 19:00:00'), Timestamp('2016-02-02 20:00:00'), Timestamp('2016-02-02 21:00:00'), Timestamp('2016-02-02 22:00:00'), Timestamp('2016-02-02 23:00:00'), Timestamp('2016-02-03 00:00:00'), Timestamp('2016-02-03 01:00:00'), Timestamp('2016-02-03 02:00:00'), Timestamp('2016-02-03 03:00:00'), Timestamp('2016-02-03 04:00:00'), Timestamp('2016-02-03 05:00:00'), Timestamp('2016-02-03 06:00:00'), Timestamp('2016-02-03 07:00:00'), Timestamp('2016-02-03 08:00:00'), Timestamp('2016-02-03 09:00:00'), Timestamp('2016-02-03 10:00:00'), Timestamp('2016-02-03 11:00:00'), Timestamp('2016-02-03 12:00:00'), Timestamp('2016-02-03 13:00:00'), Timestamp('2016-02-03 14:00:00'), Timestamp('2016-02-03 15:00:00'), Timestamp('2016-02-03 16:00:00'), Timestamp('2016-02-03 17:00:00'), Timestamp('2016-02-03 18:00:00'), Timestamp('2016-02-03 19:00:00'), Timestamp('2016-02-03 20:00:00'), Timestamp('2016-02-03 21:00:00'), Timestamp('2016-02-03 22:00:00'), Timestamp('2016-02-03 23:00:00'), Timestamp('2016-02-04 00:00:00'), Timestamp('2016-02-04 01:00:00'), Timestamp('2016-02-04 02:00:00'), Timestamp('2016-02-04 03:00:00'), Timestamp('2016-02-04 04:00:00'), Timestamp('2016-02-04 05:00:00'), Timestamp('2016-02-04 06:00:00'), Timestamp('2016-02-04 07:00:00'), Timestamp('2016-02-04 08:00:00'), Timestamp('2016-02-04 09:00:00'), Timestamp('2016-02-04 10:00:00'), Timestamp('2016-02-04 11:00:00'), Timestamp('2016-02-04 12:00:00'), Timestamp('2016-02-04 13:00:00'), Timestamp('2016-02-04 14:00:00'), Timestamp('2016-02-04 15:00:00'), Timestamp('2016-02-04 16:00:00'), Timestamp('2016-02-04 17:00:00'), Timestamp('2016-02-04 18:00:00'), Timestamp('2016-02-04 19:00:00'), Timestamp('2016-02-04 20:00:00'), Timestamp('2016-02-04 21:00:00'), Timestamp('2016-02-04 22:00:00'), Timestamp('2016-02-04 23:00:00'), Timestamp('2016-02-05 00:00:00'), Timestamp('2016-02-05 01:00:00'), Timestamp('2016-02-05 02:00:00'), Timestamp('2016-02-05 03:00:00'), Timestamp('2016-02-05 04:00:00'), Timestamp('2016-02-05 05:00:00'), Timestamp('2016-02-05 06:00:00'), Timestamp('2016-02-05 07:00:00'), Timestamp('2016-02-05 08:00:00'), Timestamp('2016-02-05 09:00:00'), Timestamp('2016-02-05 10:00:00'), Timestamp('2016-02-05 11:00:00'), Timestamp('2016-02-05 12:00:00'), Timestamp('2016-02-05 13:00:00'), Timestamp('2016-02-05 14:00:00'), Timestamp('2016-02-05 15:00:00'), Timestamp('2016-02-05 16:00:00'), Timestamp('2016-02-05 17:00:00'), Timestamp('2016-02-05 18:00:00'), Timestamp('2016-02-05 19:00:00'), Timestamp('2016-02-05 20:00:00'), Timestamp('2016-02-05 21:00:00'), Timestamp('2016-02-05 22:00:00'), Timestamp('2016-02-05 23:00:00'), Timestamp('2016-02-06 00:00:00'), Timestamp('2016-02-06 01:00:00'), Timestamp('2016-02-06 02:00:00'), Timestamp('2016-02-06 03:00:00'), Timestamp('2016-02-06 04:00:00'), Timestamp('2016-02-06 05:00:00'), Timestamp('2016-02-06 06:00:00'), Timestamp('2016-02-06 07:00:00'), Timestamp('2016-02-06 08:00:00'), Timestamp('2016-02-06 09:00:00'), Timestamp('2016-02-06 10:00:00'), Timestamp('2016-02-06 11:00:00'), Timestamp('2016-02-06 12:00:00'), Timestamp('2016-02-06 13:00:00'), Timestamp('2016-02-06 14:00:00'), Timestamp('2016-02-06 15:00:00'), Timestamp('2016-02-06 16:00:00'), Timestamp('2016-02-06 17:00:00'), Timestamp('2016-02-06 18:00:00'), Timestamp('2016-02-06 19:00:00'), Timestamp('2016-02-06 20:00:00'), Timestamp('2016-02-06 21:00:00'), Timestamp('2016-02-06 22:00:00'), Timestamp('2016-02-06 23:00:00'), Timestamp('2016-02-07 00:00:00'), Timestamp('2016-02-07 01:00:00'), Timestamp('2016-02-07 02:00:00'), Timestamp('2016-02-07 03:00:00'), Timestamp('2016-02-07 04:00:00'), Timestamp('2016-02-07 05:00:00'), Timestamp('2016-02-07 06:00:00'), Timestamp('2016-02-07 07:00:00'), Timestamp('2016-02-07 08:00:00'), Timestamp('2016-02-07 09:00:00'), Timestamp('2016-02-07 10:00:00'), Timestamp('2016-02-07 11:00:00'), Timestamp('2016-02-07 12:00:00'), Timestamp('2016-02-07 13:00:00'), Timestamp('2016-02-07 14:00:00'), Timestamp('2016-02-07 15:00:00'), Timestamp('2016-02-07 16:00:00'), Timestamp('2016-02-07 17:00:00'), Timestamp('2016-02-07 18:00:00'), Timestamp('2016-02-07 19:00:00'), Timestamp('2016-02-07 20:00:00'), Timestamp('2016-02-07 21:00:00'), Timestamp('2016-02-07 22:00:00'), Timestamp('2016-02-07 23:00:00'), Timestamp('2016-02-08 00:00:00'), Timestamp('2016-02-08 01:00:00'), Timestamp('2016-02-08 02:00:00'), Timestamp('2016-02-08 03:00:00'), Timestamp('2016-02-08 04:00:00'), Timestamp('2016-02-08 05:00:00'), Timestamp('2016-02-08 06:00:00'), Timestamp('2016-02-08 07:00:00'), Timestamp('2016-02-08 08:00:00'), Timestamp('2016-02-08 09:00:00'), Timestamp('2016-02-08 10:00:00'), Timestamp('2016-02-08 11:00:00'), Timestamp('2016-02-08 12:00:00'), Timestamp('2016-02-08 13:00:00'), Timestamp('2016-02-08 14:00:00'), Timestamp('2016-02-08 15:00:00'), Timestamp('2016-02-08 16:00:00'), Timestamp('2016-02-08 17:00:00'), Timestamp('2016-02-08 18:00:00'), Timestamp('2016-02-08 19:00:00'), Timestamp('2016-02-08 20:00:00'), Timestamp('2016-02-08 21:00:00'), Timestamp('2016-02-08 22:00:00'), Timestamp('2016-02-08 23:00:00'), Timestamp('2016-02-09 00:00:00'), Timestamp('2016-02-09 01:00:00'), Timestamp('2016-02-09 02:00:00'), Timestamp('2016-02-09 03:00:00'), Timestamp('2016-02-09 04:00:00'), Timestamp('2016-02-09 05:00:00'), Timestamp('2016-02-09 06:00:00'), Timestamp('2016-02-09 07:00:00'), Timestamp('2016-02-09 08:00:00'), Timestamp('2016-02-09 09:00:00'), Timestamp('2016-02-09 10:00:00'), Timestamp('2016-02-09 11:00:00'), Timesta

In [1329]:
# Ausgabe der Listen um auf Länge zu testen 2020
print(len(zeitraum))
print(len(bruehler_straße))
print(len(estermannufer))
print(len(kennedybruecke))
print(len(nordbruecke))
print(len(suedbruecke))
print(len(rhenusallee))
print(len(von_sandt_ufer))
print(len(weg_auf_dem_damm))
print(len(wilhelm_spiritus_ufer))

43465
43465
43465
43465
43465
43465
43465
43465
43465
43465

In [1330]:
# Daten laden 2021
df = pd.read_csv("../Projektdatensaetze_angepasst/2021/fahrradzaehlungen2021.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')



# Index setzen
df = df.set_index('time')


# in Liste speichern
zeitraum = zeitraum + df.index.tolist()
bruehler_straße = bruehler_straße + df[('Bruehler Straße')].values.tolist()
estermannufer = estermannufer + df[('Estermannufer')].values.tolist()
kennedybruecke = kennedybruecke + df[('Kennedybruecke')].values.tolist()
nordbruecke = nordbruecke + df[('Nordbruecke')].values.tolist()
suedbruecke = suedbruecke + df[('Suedbruecke')].values.tolist()
rhenusallee = rhenusallee + df[('Rhenusallee')].values.tolist()
von_sandt_ufer = von_sandt_ufer + df[('Von-Sandt-Ufer')].values.tolist()
weg_auf_dem_damm = weg_auf_dem_damm + df[('Weg auf Damm Neil')].values.tolist()
wilhelm_spiritus_ufer = wilhelm_spiritus_ufer + df[('Wilhelm-Spiritus-Ufer')].values.tolist()

In [1331]:
# Ausgabe der Listen um auf Länge zu testen 2021
print(len(zeitraum))
print(len(bruehler_straße))
print(len(estermannufer))
print(len(kennedybruecke))
print(len(nordbruecke))
print(len(suedbruecke))
print(len(rhenusallee))
print(len(von_sandt_ufer))
print(len(weg_auf_dem_damm))
print(len(wilhelm_spiritus_ufer))

52225
52225
52225
52225
52225
52225
52225
52225
52225
52225

In [1332]:
# Daten laden 2022
df = pd.read_csv("../Projektdatensaetze_angepasst/2022/FahrradZaehlungBonn2022.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')



# Index setzen
df = df.set_index('time')

# auf Stunden umrechnen
df = df.resample('h').sum()

# addition der Werte
df['Bruehler Straße'] = df['Bruehler Straße Ri. Sueden'] + df['Bruehler Straße Ri. Norden'] + df['Bruehler Straße [Bike IN]'] + df['Brueler Straße [Bike OUT]']
df['Estermannufer'] = df['Estermannufer Ri. Bonn'] + df['Estermannufer Ri. Koeln'] + df['Estermannufer [Bike IN]'] + df['Estermannufer [Bike OUT]']
df['Kennedybruecke'] = df['Kennedybruecke Ri. Beuel'] + df['Kennedybruecke Ri. Innenstadt']
df['Nordbruecke'] = df['Nordbruecke Ri. Auerberg'] + df['Nordbruecke Ri. Beuel']
df['Suedbruecke'] = df['Suedbruecke Ri. Oberkassel'] + df['Suedbruecke Ri. Rheinaue']
df['Rhenusallee'] = df['Rhenusallee Ri. Beuel'] + df['Rhenusallee Ri. Oberkassel'] + df['Rhenusallee [Bike IN]'] + df['Rhenusallee [Bike IN].1'] + df['Rhenusallee [Bike OUT]'] + df['Rhenusallee [Bike OUT].1']
df['Von-Sandt-Ufer'] = df['Von-Sandt-Ufer Ri. Bad Godesberg'] + df['Von-Sandt-Ufer Ri. Bonn'] + df['Von-Sandt-Ufer [Bike IN]'] + df['Von-Sandt-Ufer [Bike IN].1'] + df['Von-Sandt-Ufer [Bike OUT]'] + df['Von-Sandt-Ufer [Bike OUT].1']
df['Weg auf Damm Neil'] = df['Weg auf Damm Neil Ri. Norden'] + df['Weg auf Damm Neil Ri. Sueden'] + df['Weg auf Damm Neil Ri. Norden.1'] + df['Weg auf Damm Neil Ri. Sueden.1']
df['Wilhelm-Spiritus-Ufer'] = df['Wilhelm-Spiritus-Ufer Ri. Sueden']  + df['Wilhelm-Spiritus-Ufer Ri. Sueden.1'] + df['Wilhelm-Spiritus-Ufer Ri. Norden'] + df['Wilhelm-Spiritus-Ufer Ri. Sueden.1']

# in Liste speichern
zeitraum = zeitraum + df.index.tolist()
bruehler_straße = bruehler_straße + df[('Bruehler Straße')].values.tolist()
estermannufer = estermannufer + df[('Estermannufer')].values.tolist()
kennedybruecke = kennedybruecke + df[('Kennedybruecke')].values.tolist()
nordbruecke = nordbruecke + df[('Nordbruecke')].values.tolist()
suedbruecke = suedbruecke + df[('Suedbruecke')].values.tolist()
rhenusallee = rhenusallee + df[('Rhenusallee')].values.tolist()
von_sandt_ufer = von_sandt_ufer + df[('Von-Sandt-Ufer')].values.tolist()
weg_auf_dem_damm = weg_auf_dem_damm + df[('Weg auf Damm Neil')].values.tolist()
wilhelm_spiritus_ufer = wilhelm_spiritus_ufer + df[('Wilhelm-Spiritus-Ufer')].values.tolist()
print(zeitraum)

[Timestamp('2016-01-16 00:00:00'), Timestamp('2016-01-16 01:00:00'), Timestamp('2016-01-16 02:00:00'), Timestamp('2016-01-16 03:00:00'), Timestamp('2016-01-16 04:00:00'), Timestamp('2016-01-16 05:00:00'), Timestamp('2016-01-16 06:00:00'), Timestamp('2016-01-16 07:00:00'), Timestamp('2016-01-16 08:00:00'), Timestamp('2016-01-16 09:00:00'), Timestamp('2016-01-16 10:00:00'), Timestamp('2016-01-16 11:00:00'), Timestamp('2016-01-16 12:00:00'), Timestamp('2016-01-16 13:00:00'), Timestamp('2016-01-16 14:00:00'), Timestamp('2016-01-16 15:00:00'), Timestamp('2016-01-16 16:00:00'), Timestamp('2016-01-16 17:00:00'), Timestamp('2016-01-16 18:00:00'), Timestamp('2016-01-16 19:00:00'), Timestamp('2016-01-16 20:00:00'), Timestamp('2016-01-16 21:00:00'), Timestamp('2016-01-16 22:00:00'), Timestamp('2016-01-16 23:00:00'), Timestamp('2016-01-17 00:00:00'), Timestamp('2016-01-17 01:00:00'), Timestamp('2016-01-17 02:00:00'), Timestamp('2016-01-17 03:00:00'), Timestamp('2016-01-17 04:00:00'), Timestamp('2016-01-17 05:00:00'), Timestamp('2016-01-17 06:00:00'), Timestamp('2016-01-17 07:00:00'), Timestamp('2016-01-17 08:00:00'), Timestamp('2016-01-17 09:00:00'), Timestamp('2016-01-17 10:00:00'), Timestamp('2016-01-17 11:00:00'), Timestamp('2016-01-17 12:00:00'), Timestamp('2016-01-17 13:00:00'), Timestamp('2016-01-17 14:00:00'), Timestamp('2016-01-17 15:00:00'), Timestamp('2016-01-17 16:00:00'), Timestamp('2016-01-17 17:00:00'), Timestamp('2016-01-17 18:00:00'), Timestamp('2016-01-17 19:00:00'), Timestamp('2016-01-17 20:00:00'), Timestamp('2016-01-17 21:00:00'), Timestamp('2016-01-17 22:00:00'), Timestamp('2016-01-17 23:00:00'), Timestamp('2016-01-18 00:00:00'), Timestamp('2016-01-18 01:00:00'), Timestamp('2016-01-18 02:00:00'), Timestamp('2016-01-18 03:00:00'), Timestamp('2016-01-18 04:00:00'), Timestamp('2016-01-18 05:00:00'), Timestamp('2016-01-18 06:00:00'), Timestamp('2016-01-18 07:00:00'), Timestamp('2016-01-18 08:00:00'), Timestamp('2016-01-18 09:00:00'), Timestamp('2016-01-18 10:00:00'), Timestamp('2016-01-18 11:00:00'), Timestamp('2016-01-18 12:00:00'), Timestamp('2016-01-18 13:00:00'), Timestamp('2016-01-18 14:00:00'), Timestamp('2016-01-18 15:00:00'), Timestamp('2016-01-18 16:00:00'), Timestamp('2016-01-18 17:00:00'), Timestamp('2016-01-18 18:00:00'), Timestamp('2016-01-18 19:00:00'), Timestamp('2016-01-18 20:00:00'), Timestamp('2016-01-18 21:00:00'), Timestamp('2016-01-18 22:00:00'), Timestamp('2016-01-18 23:00:00'), Timestamp('2016-01-19 00:00:00'), Timestamp('2016-01-19 01:00:00'), Timestamp('2016-01-19 02:00:00'), Timestamp('2016-01-19 03:00:00'), Timestamp('2016-01-19 04:00:00'), Timestamp('2016-01-19 05:00:00'), Timestamp('2016-01-19 06:00:00'), Timestamp('2016-01-19 07:00:00'), Timestamp('2016-01-19 08:00:00'), Timestamp('2016-01-19 09:00:00'), Timestamp('2016-01-19 10:00:00'), Timestamp('2016-01-19 11:00:00'), Timestamp('2016-01-19 12:00:00'), Timestamp('2016-01-19 13:00:00'), Timestamp('2016-01-19 14:00:00'), Timestamp('2016-01-19 15:00:00'), Timestamp('2016-01-19 16:00:00'), Timestamp('2016-01-19 17:00:00'), Timestamp('2016-01-19 18:00:00'), Timestamp('2016-01-19 19:00:00'), Timestamp('2016-01-19 20:00:00'), Timestamp('2016-01-19 21:00:00'), Timestamp('2016-01-19 22:00:00'), Timestamp('2016-01-19 23:00:00'), Timestamp('2016-01-20 00:00:00'), Timestamp('2016-01-20 01:00:00'), Timestamp('2016-01-20 02:00:00'), Timestamp('2016-01-20 03:00:00'), Timestamp('2016-01-20 04:00:00'), Timestamp('2016-01-20 05:00:00'), Timestamp('2016-01-20 06:00:00'), Timestamp('2016-01-20 07:00:00'), Timestamp('2016-01-20 08:00:00'), Timestamp('2016-01-20 09:00:00'), Timestamp('2016-01-20 10:00:00'), Timestamp('2016-01-20 11:00:00'), Timestamp('2016-01-20 12:00:00'), Timestamp('2016-01-20 13:00:00'), Timestamp('2016-01-20 14:00:00'), Timestamp('2016-01-20 15:00:00'), Timestamp('2016-01-20 16:00:00'), Timestamp('2016-01-20 17:00:00'), Timestamp('2016-01-20 18:00:00'), Timestamp('2016-01-20 19:00:00'), Timestamp('2016-01-20 20:00:00'), Timestamp('2016-01-20 21:00:00'), Timestamp('2016-01-20 22:00:00'), Timestamp('2016-01-20 23:00:00'), Timestamp('2016-01-21 00:00:00'), Timestamp('2016-01-21 01:00:00'), Timestamp('2016-01-21 02:00:00'), Timestamp('2016-01-21 03:00:00'), Timestamp('2016-01-21 04:00:00'), Timestamp('2016-01-21 05:00:00'), Timestamp('2016-01-21 06:00:00'), Timestamp('2016-01-21 07:00:00'), Timestamp('2016-01-21 08:00:00'), Timestamp('2016-01-21 09:00:00'), Timestamp('2016-01-21 10:00:00'), Timestamp('2016-01-21 11:00:00'), Timestamp('2016-01-21 12:00:00'), Timestamp('2016-01-21 13:00:00'), Timestamp('2016-01-21 14:00:00'), Timestamp('2016-01-21 15:00:00'), Timestamp('2016-01-21 16:00:00'), Timestamp('2016-01-21 17:00:00'), Timestamp('2016-01-21 18:00:00'), Timestamp('2016-01-21 19:00:00'), Timestamp('2016-01-21 20:00:00'), Timestamp('2016-01-21 21:00:00'), Timestamp('2016-01-21 22:00:00'), Timestamp('2016-01-21 23:00:00'), Timestamp('2016-01-22 00:00:00'), Timestamp('2016-01-22 01:00:00'), Timestamp('2016-01-22 02:00:00'), Timestamp('2016-01-22 03:00:00'), Timestamp('2016-01-22 04:00:00'), Timestamp('2016-01-22 05:00:00'), Timestamp('2016-01-22 06:00:00'), Timestamp('2016-01-22 07:00:00'), Timestamp('2016-01-22 08:00:00'), Timestamp('2016-01-22 09:00:00'), Timestamp('2016-01-22 10:00:00'), Timestamp('2016-01-22 11:00:00'), Timestamp('2016-01-22 12:00:00'), Timestamp('2016-01-22 13:00:00'), Timestamp('2016-01-22 14:00:00'), Timestamp('2016-01-22 15:00:00'), Timestamp('2016-01-22 16:00:00'), Timestamp('2016-01-22 17:00:00'), Timestamp('2016-01-22 18:00:00'), Timestamp('2016-01-22 19:00:00'), Timestamp('2016-01-22 20:00:00'), Timestamp('2016-01-22 21:00:00'), Timestamp('2016-01-22 22:00:00'), Timestamp('2016-01-22 23:00:00'), Timestamp('2016-01-23 00:00:00'), Timestamp('2016-01-23 01:00:00'), Timestamp('2016-01-23 02:00:00'), Timestamp('2016-01-23 03:00:00'), Timestamp('2016-01-23 04:00:00'), Timestamp('2016-01-23 05:00:00'), Timestamp('2016-01-23 06:00:00'), Timestamp('2016-01-23 07:00:00'), Timestamp('2016-01-23 08:00:00'), Timestamp('2016-01-23 09:00:00'), Timestamp('2016-01-23 10:00:00'), Timestamp('2016-01-23 11:00:00'), Timestamp('2016-01-23 12:00:00'), Timestamp('2016-01-23 13:00:00'), Timestamp('2016-01-23 14:00:00'), Timestamp('2016-01-23 15:00:00'), Timestamp('2016-01-23 16:00:00'), Timestamp('2016-01-23 17:00:00'), Timestamp('2016-01-23 18:00:00'), Timestamp('2016-01-23 19:00:00'), Timestamp('2016-01-23 20:00:00'), Timestamp('2016-01-23 21:00:00'), Timestamp('2016-01-23 22:00:00'), Timestamp('2016-01-23 23:00:00'), Timestamp('2016-01-24 00:00:00'), Timestamp('2016-01-24 01:00:00'), Timestamp('2016-01-24 02:00:00'), Timestamp('2016-01-24 03:00:00'), Timestamp('2016-01-24 04:00:00'), Timestamp('2016-01-24 05:00:00'), Timestamp('2016-01-24 06:00:00'), Timestamp('2016-01-24 07:00:00'), Timestamp('2016-01-24 08:00:00'), Timestamp('2016-01-24 09:00:00'), Timestamp('2016-01-24 10:00:00'), Timestamp('2016-01-24 11:00:00'), Timestamp('2016-01-24 12:00:00'), Timestamp('2016-01-24 13:00:00'), Timestamp('2016-01-24 14:00:00'), Timestamp('2016-01-24 15:00:00'), Timestamp('2016-01-24 16:00:00'), Timestamp('2016-01-24 17:00:00'), Timestamp('2016-01-24 18:00:00'), Timestamp('2016-01-24 19:00:00'), Timestamp('2016-01-24 20:00:00'), Timestamp('2016-01-24 21:00:00'), Timestamp('2016-01-24 22:00:00'), Timestamp('2016-01-24 23:00:00'), Timestamp('2016-01-25 00:00:00'), Timestamp('2016-01-25 01:00:00'), Timestamp('2016-01-25 02:00:00'), Timestamp('2016-01-25 03:00:00'), Timestamp('2016-01-25 04:00:00'), Timestamp('2016-01-25 05:00:00'), Timestamp('2016-01-25 06:00:00'), Timestamp('2016-01-25 07:00:00'), Timestamp('2016-01-25 08:00:00'), Timestamp('2016-01-25 09:00:00'), Timestamp('2016-01-25 10:00:00'), Timestamp('2016-01-25 11:00:00'), Timestamp('2016-01-25 12:00:00'), Timestamp('2016-01-25 13:00:00'), Timestamp('2016-01-25 14:00:00'), Timestamp('2016-01-25 15:00:00'), Timestamp('2016-01-25 16:00:00'), Timestamp('2016-01-25 17:00:00'), Timestamp('2016-01-25 18:00:00'), Timestamp('2016-01-25 19:00:00'), Timestamp('2016-01-25 20:00:00'), Timestamp('2016-01-25 21:00:00'), Timestamp('2016-01-25 22:00:00'), Timestamp('2016-01-25 23:00:00'), Timestamp('2016-01-26 00:00:00'), Timestamp('2016-01-26 01:00:00'), Timestamp('2016-01-26 02:00:00'), Timestamp('2016-01-26 03:00:00'), Timestamp('2016-01-26 04:00:00'), Timestamp('2016-01-26 05:00:00'), Timestamp('2016-01-26 06:00:00'), Timestamp('2016-01-26 07:00:00'), Timestamp('2016-01-26 08:00:00'), Timestamp('2016-01-26 09:00:00'), Timestamp('2016-01-26 10:00:00'), Timestamp('2016-01-26 11:00:00'), Timestamp('2016-01-26 12:00:00'), Timestamp('2016-01-26 13:00:00'), Timestamp('2016-01-26 14:00:00'), Timestamp('2016-01-26 15:00:00'), Timestamp('2016-01-26 16:00:00'), Timestamp('2016-01-26 17:00:00'), Timestamp('2016-01-26 18:00:00'), Timestamp('2016-01-26 19:00:00'), Timestamp('2016-01-26 20:00:00'), Timestamp('2016-01-26 21:00:00'), Timestamp('2016-01-26 22:00:00'), Timestamp('2016-01-26 23:00:00'), Timestamp('2016-01-27 00:00:00'), Timestamp('2016-01-27 01:00:00'), Timestamp('2016-01-27 02:00:00'), Timestamp('2016-01-27 03:00:00'), Timestamp('2016-01-27 04:00:00'), Timestamp('2016-01-27 05:00:00'), Timestamp('2016-01-27 06:00:00'), Timestamp('2016-01-27 07:00:00'), Timestamp('2016-01-27 08:00:00'), Timestamp('2016-01-27 09:00:00'), Timestamp('2016-01-27 10:00:00'), Timestamp('2016-01-27 11:00:00'), Timestamp('2016-01-27 12:00:00'), Timestamp('2016-01-27 13:00:00'), Timestamp('2016-01-27 14:00:00'), Timestamp('2016-01-27 15:00:00'), Timestamp('2016-01-27 16:00:00'), Timestamp('2016-01-27 17:00:00'), Timestamp('2016-01-27 18:00:00'), Timestamp('2016-01-27 19:00:00'), Timestamp('2016-01-27 20:00:00'), Timestamp('2016-01-27 21:00:00'), Timestamp('2016-01-27 22:00:00'), Timestamp('2016-01-27 23:00:00'), Timestamp('2016-01-28 00:00:00'), Timestamp('2016-01-28 01:00:00'), Timestamp('2016-01-28 02:00:00'), Timestamp('2016-01-28 03:00:00'), Timestamp('2016-01-28 04:00:00'), Timestamp('2016-01-28 05:00:00'), Timestamp('2016-01-28 06:00:00'), Timestamp('2016-01-28 07:00:00'), Timestamp('2016-01-28 08:00:00'), Timestamp('2016-01-28 09:00:00'), Timestamp('2016-01-28 10:00:00'), Timestamp('2016-01-28 11:00:00'), Timestamp('2016-01-28 12:00:00'), Timestamp('2016-01-28 13:00:00'), Timestamp('2016-01-28 14:00:00'), Timestamp('2016-01-28 15:00:00'), Timestamp('2016-01-28 16:00:00'), Timestamp('2016-01-28 17:00:00'), Timestamp('2016-01-28 18:00:00'), Timestamp('2016-01-28 19:00:00'), Timestamp('2016-01-28 20:00:00'), Timestamp('2016-01-28 21:00:00'), Timestamp('2016-01-28 22:00:00'), Timestamp('2016-01-28 23:00:00'), Timestamp('2016-01-29 00:00:00'), Timestamp('2016-01-29 01:00:00'), Timestamp('2016-01-29 02:00:00'), Timestamp('2016-01-29 03:00:00'), Timestamp('2016-01-29 04:00:00'), Timestamp('2016-01-29 05:00:00'), Timestamp('2016-01-29 06:00:00'), Timestamp('2016-01-29 07:00:00'), Timestamp('2016-01-29 08:00:00'), Timestamp('2016-01-29 09:00:00'), Timestamp('2016-01-29 10:00:00'), Timestamp('2016-01-29 11:00:00'), Timestamp('2016-01-29 12:00:00'), Timestamp('2016-01-29 13:00:00'), Timestamp('2016-01-29 14:00:00'), Timestamp('2016-01-29 15:00:00'), Timestamp('2016-01-29 16:00:00'), Timestamp('2016-01-29 17:00:00'), Timestamp('2016-01-29 18:00:00'), Timestamp('2016-01-29 19:00:00'), Timestamp('2016-01-29 20:00:00'), Timestamp('2016-01-29 21:00:00'), Timestamp('2016-01-29 22:00:00'), Timestamp('2016-01-29 23:00:00'), Timestamp('2016-01-30 00:00:00'), Timestamp('2016-01-30 01:00:00'), Timestamp('2016-01-30 02:00:00'), Timestamp('2016-01-30 03:00:00'), Timestamp('2016-01-30 04:00:00'), Timestamp('2016-01-30 05:00:00'), Timestamp('2016-01-30 06:00:00'), Timestamp('2016-01-30 07:00:00'), Timestamp('2016-01-30 08:00:00'), Timestamp('2016-01-30 09:00:00'), Timestamp('2016-01-30 10:00:00'), Timestamp('2016-01-30 11:00:00'), Timestamp('2016-01-30 12:00:00'), Timestamp('2016-01-30 13:00:00'), Timestamp('2016-01-30 14:00:00'), Timestamp('2016-01-30 15:00:00'), Timestamp('2016-01-30 16:00:00'), Timestamp('2016-01-30 17:00:00'), Timestamp('2016-01-30 18:00:00'), Timestamp('2016-01-30 19:00:00'), Timestamp('2016-01-30 20:00:00'), Timestamp('2016-01-30 21:00:00'), Timestamp('2016-01-30 22:00:00'), Timestamp('2016-01-30 23:00:00'), Timestamp('2016-01-31 00:00:00'), Timestamp('2016-01-31 01:00:00'), Timestamp('2016-01-31 02:00:00'), Timestamp('2016-01-31 03:00:00'), Timestamp('2016-01-31 04:00:00'), Timestamp('2016-01-31 05:00:00'), Timestamp('2016-01-31 06:00:00'), Timestamp('2016-01-31 07:00:00'), Timestamp('2016-01-31 08:00:00'), Timestamp('2016-01-31 09:00:00'), Timestamp('2016-01-31 10:00:00'), Timestamp('2016-01-31 11:00:00'), Timestamp('2016-01-31 12:00:00'), Timestamp('2016-01-31 13:00:00'), Timestamp('2016-01-31 14:00:00'), Timestamp('2016-01-31 15:00:00'), Timestamp('2016-01-31 16:00:00'), Timestamp('2016-01-31 17:00:00'), Timestamp('2016-01-31 18:00:00'), Timestamp('2016-01-31 19:00:00'), Timestamp('2016-01-31 20:00:00'), Timestamp('2016-01-31 21:00:00'), Timestamp('2016-01-31 22:00:00'), Timestamp('2016-01-31 23:00:00'), Timestamp('2016-02-01 00:00:00'), Timestamp('2016-02-01 01:00:00'), Timestamp('2016-02-01 02:00:00'), Timestamp('2016-02-01 03:00:00'), Timestamp('2016-02-01 04:00:00'), Timestamp('2016-02-01 05:00:00'), Timestamp('2016-02-01 06:00:00'), Timestamp('2016-02-01 07:00:00'), Timestamp('2016-02-01 08:00:00'), Timestamp('2016-02-01 09:00:00'), Timestamp('2016-02-01 10:00:00'), Timestamp('2016-02-01 11:00:00'), Timestamp('2016-02-01 12:00:00'), Timestamp('2016-02-01 13:00:00'), Timestamp('2016-02-01 14:00:00'), Timestamp('2016-02-01 15:00:00'), Timestamp('2016-02-01 16:00:00'), Timestamp('2016-02-01 17:00:00'), Timestamp('2016-02-01 18:00:00'), Timestamp('2016-02-01 19:00:00'), Timestamp('2016-02-01 20:00:00'), Timestamp('2016-02-01 21:00:00'), Timestamp('2016-02-01 22:00:00'), Timestamp('2016-02-01 23:00:00'), Timestamp('2016-02-02 00:00:00'), Timestamp('2016-02-02 01:00:00'), Timestamp('2016-02-02 02:00:00'), Timestamp('2016-02-02 03:00:00'), Timestamp('2016-02-02 04:00:00'), Timestamp('2016-02-02 05:00:00'), Timestamp('2016-02-02 06:00:00'), Timestamp('2016-02-02 07:00:00'), Timestamp('2016-02-02 08:00:00'), Timestamp('2016-02-02 09:00:00'), Timestamp('2016-02-02 10:00:00'), Timestamp('2016-02-02 11:00:00'), Timestamp('2016-02-02 12:00:00'), Timestamp('2016-02-02 13:00:00'), Timestamp('2016-02-02 14:00:00'), Timestamp('2016-02-02 15:00:00'), Timestamp('2016-02-02 16:00:00'), Timestamp('2016-02-02 17:00:00'), Timestamp('2016-02-02 18:00:00'), Timestamp('2016-02-02 19:00:00'), Timestamp('2016-02-02 20:00:00'), Timestamp('2016-02-02 21:00:00'), Timestamp('2016-02-02 22:00:00'), Timestamp('2016-02-02 23:00:00'), Timestamp('2016-02-03 00:00:00'), Timestamp('2016-02-03 01:00:00'), Timestamp('2016-02-03 02:00:00'), Timestamp('2016-02-03 03:00:00'), Timestamp('2016-02-03 04:00:00'), Timestamp('2016-02-03 05:00:00'), Timestamp('2016-02-03 06:00:00'), Timestamp('2016-02-03 07:00:00'), Timestamp('2016-02-03 08:00:00'), Timestamp('2016-02-03 09:00:00'), Timestamp('2016-02-03 10:00:00'), Timestamp('2016-02-03 11:00:00'), Timestamp('2016-02-03 12:00:00'), Timestamp('2016-02-03 13:00:00'), Timestamp('2016-02-03 14:00:00'), Timestamp('2016-02-03 15:00:00'), Timestamp('2016-02-03 16:00:00'), Timestamp('2016-02-03 17:00:00'), Timestamp('2016-02-03 18:00:00'), Timestamp('2016-02-03 19:00:00'), Timestamp('2016-02-03 20:00:00'), Timestamp('2016-02-03 21:00:00'), Timestamp('2016-02-03 22:00:00'), Timestamp('2016-02-03 23:00:00'), Timestamp('2016-02-04 00:00:00'), Timestamp('2016-02-04 01:00:00'), Timestamp('2016-02-04 02:00:00'), Timestamp('2016-02-04 03:00:00'), Timestamp('2016-02-04 04:00:00'), Timestamp('2016-02-04 05:00:00'), Timestamp('2016-02-04 06:00:00'), Timestamp('2016-02-04 07:00:00'), Timestamp('2016-02-04 08:00:00'), Timestamp('2016-02-04 09:00:00'), Timestamp('2016-02-04 10:00:00'), Timestamp('2016-02-04 11:00:00'), Timestamp('2016-02-04 12:00:00'), Timestamp('2016-02-04 13:00:00'), Timestamp('2016-02-04 14:00:00'), Timestamp('2016-02-04 15:00:00'), Timestamp('2016-02-04 16:00:00'), Timestamp('2016-02-04 17:00:00'), Timestamp('2016-02-04 18:00:00'), Timestamp('2016-02-04 19:00:00'), Timestamp('2016-02-04 20:00:00'), Timestamp('2016-02-04 21:00:00'), Timestamp('2016-02-04 22:00:00'), Timestamp('2016-02-04 23:00:00'), Timestamp('2016-02-05 00:00:00'), Timestamp('2016-02-05 01:00:00'), Timestamp('2016-02-05 02:00:00'), Timestamp('2016-02-05 03:00:00'), Timestamp('2016-02-05 04:00:00'), Timestamp('2016-02-05 05:00:00'), Timestamp('2016-02-05 06:00:00'), Timestamp('2016-02-05 07:00:00'), Timestamp('2016-02-05 08:00:00'), Timestamp('2016-02-05 09:00:00'), Timestamp('2016-02-05 10:00:00'), Timestamp('2016-02-05 11:00:00'), Timestamp('2016-02-05 12:00:00'), Timestamp('2016-02-05 13:00:00'), Timestamp('2016-02-05 14:00:00'), Timestamp('2016-02-05 15:00:00'), Timestamp('2016-02-05 16:00:00'), Timestamp('2016-02-05 17:00:00'), Timestamp('2016-02-05 18:00:00'), Timestamp('2016-02-05 19:00:00'), Timestamp('2016-02-05 20:00:00'), Timestamp('2016-02-05 21:00:00'), Timestamp('2016-02-05 22:00:00'), Timestamp('2016-02-05 23:00:00'), Timestamp('2016-02-06 00:00:00'), Timestamp('2016-02-06 01:00:00'), Timestamp('2016-02-06 02:00:00'), Timestamp('2016-02-06 03:00:00'), Timestamp('2016-02-06 04:00:00'), Timestamp('2016-02-06 05:00:00'), Timestamp('2016-02-06 06:00:00'), Timestamp('2016-02-06 07:00:00'), Timestamp('2016-02-06 08:00:00'), Timestamp('2016-02-06 09:00:00'), Timestamp('2016-02-06 10:00:00'), Timestamp('2016-02-06 11:00:00'), Timestamp('2016-02-06 12:00:00'), Timestamp('2016-02-06 13:00:00'), Timestamp('2016-02-06 14:00:00'), Timestamp('2016-02-06 15:00:00'), Timestamp('2016-02-06 16:00:00'), Timestamp('2016-02-06 17:00:00'), Timestamp('2016-02-06 18:00:00'), Timestamp('2016-02-06 19:00:00'), Timestamp('2016-02-06 20:00:00'), Timestamp('2016-02-06 21:00:00'), Timestamp('2016-02-06 22:00:00'), Timestamp('2016-02-06 23:00:00'), Timestamp('2016-02-07 00:00:00'), Timestamp('2016-02-07 01:00:00'), Timestamp('2016-02-07 02:00:00'), Timestamp('2016-02-07 03:00:00'), Timestamp('2016-02-07 04:00:00'), Timestamp('2016-02-07 05:00:00'), Timestamp('2016-02-07 06:00:00'), Timestamp('2016-02-07 07:00:00'), Timestamp('2016-02-07 08:00:00'), Timestamp('2016-02-07 09:00:00'), Timestamp('2016-02-07 10:00:00'), Timestamp('2016-02-07 11:00:00'), Timestamp('2016-02-07 12:00:00'), Timestamp('2016-02-07 13:00:00'), Timestamp('2016-02-07 14:00:00'), Timestamp('2016-02-07 15:00:00'), Timestamp('2016-02-07 16:00:00'), Timestamp('2016-02-07 17:00:00'), Timestamp('2016-02-07 18:00:00'), Timestamp('2016-02-07 19:00:00'), Timestamp('2016-02-07 20:00:00'), Timestamp('2016-02-07 21:00:00'), Timestamp('2016-02-07 22:00:00'), Timestamp('2016-02-07 23:00:00'), Timestamp('2016-02-08 00:00:00'), Timestamp('2016-02-08 01:00:00'), Timestamp('2016-02-08 02:00:00'), Timestamp('2016-02-08 03:00:00'), Timestamp('2016-02-08 04:00:00'), Timestamp('2016-02-08 05:00:00'), Timestamp('2016-02-08 06:00:00'), Timestamp('2016-02-08 07:00:00'), Timestamp('2016-02-08 08:00:00'), Timestamp('2016-02-08 09:00:00'), Timestamp('2016-02-08 10:00:00'), Timestamp('2016-02-08 11:00:00'), Timestamp('2016-02-08 12:00:00'), Timestamp('2016-02-08 13:00:00'), Timestamp('2016-02-08 14:00:00'), Timestamp('2016-02-08 15:00:00'), Timestamp('2016-02-08 16:00:00'), Timestamp('2016-02-08 17:00:00'), Timestamp('2016-02-08 18:00:00'), Timestamp('2016-02-08 19:00:00'), Timestamp('2016-02-08 20:00:00'), Timestamp('2016-02-08 21:00:00'), Timestamp('2016-02-08 22:00:00'), Timestamp('2016-02-08 23:00:00'), Timestamp('2016-02-09 00:00:00'), Timestamp('2016-02-09 01:00:00'), Timestamp('2016-02-09 02:00:00'), Timestamp('2016-02-09 03:00:00'), Timestamp('2016-02-09 04:00:00'), Timestamp('2016-02-09 05:00:00'), Timestamp('2016-02-09 06:00:00'), Timestamp('2016-02-09 07:00:00'), Timestamp('2016-02-09 08:00:00'), Timestamp('2016-02-09 09:00:00'), Timestamp('2016-02-09 10:00:00'), Timestamp('2016-02-09 11:00:00'), Timesta

In [1333]:
# Ausgabe der Listen um auf Länge zu testen 2022
print(len(zeitraum))
print(len(bruehler_straße))
print(len(estermannufer))
print(len(kennedybruecke))
print(len(nordbruecke))
print(len(suedbruecke))
print(len(rhenusallee))
print(len(von_sandt_ufer))
print(len(weg_auf_dem_damm))
print(len(wilhelm_spiritus_ufer))

60985
60985
60985
60985
60985
60985
60985
60985
60985
60985

In [1334]:
# Daten laden 2023
df = pd.read_csv("../Projektdatensaetze_angepasst/2023/Fahrradzaehlstellen2023_stuendlich.csv")


# time Eigenschaften geben
df['time'] = pd.to_datetime(df['time'])
df['time'] = pd.to_datetime(df['time'], format = '%Y-%m-%d %H:%M:%S')



# Index setzen
df = df.set_index('time')


# in Liste speichern
zeitraum = zeitraum + df.index.tolist()
bruehler_straße = bruehler_straße + df[('Bruehler Straße')].values.tolist()
estermannufer = estermannufer + df[('Estermannufer')].values.tolist()
kennedybruecke = kennedybruecke + df[('Kennedybruecke')].values.tolist()
nordbruecke = nordbruecke + df[('Nordbruecke')].values.tolist()
suedbruecke = suedbruecke + df[('Suedbruecke')].values.tolist()
rhenusallee = rhenusallee + df[('Rhenusallee')].values.tolist()
von_sandt_ufer = von_sandt_ufer + df[('Von-Sandt-Ufer')].values.tolist()
weg_auf_dem_damm = weg_auf_dem_damm + df[('Weg auf Damm Neil')].values.tolist()
wilhelm_spiritus_ufer = wilhelm_spiritus_ufer + df[('Wilhelm-Spiritus-Ufer')].values.tolist()
print(zeitraum)

[Timestamp('2016-01-16 00:00:00'), Timestamp('2016-01-16 01:00:00'), Timestamp('2016-01-16 02:00:00'), Timestamp('2016-01-16 03:00:00'), Timestamp('2016-01-16 04:00:00'), Timestamp('2016-01-16 05:00:00'), Timestamp('2016-01-16 06:00:00'), Timestamp('2016-01-16 07:00:00'), Timestamp('2016-01-16 08:00:00'), Timestamp('2016-01-16 09:00:00'), Timestamp('2016-01-16 10:00:00'), Timestamp('2016-01-16 11:00:00'), Timestamp('2016-01-16 12:00:00'), Timestamp('2016-01-16 13:00:00'), Timestamp('2016-01-16 14:00:00'), Timestamp('2016-01-16 15:00:00'), Timestamp('2016-01-16 16:00:00'), Timestamp('2016-01-16 17:00:00'), Timestamp('2016-01-16 18:00:00'), Timestamp('2016-01-16 19:00:00'), Timestamp('2016-01-16 20:00:00'), Timestamp('2016-01-16 21:00:00'), Timestamp('2016-01-16 22:00:00'), Timestamp('2016-01-16 23:00:00'), Timestamp('2016-01-17 00:00:00'), Timestamp('2016-01-17 01:00:00'), Timestamp('2016-01-17 02:00:00'), Timestamp('2016-01-17 03:00:00'), Timestamp('2016-01-17 04:00:00'), Timestamp('2016-01-17 05:00:00'), Timestamp('2016-01-17 06:00:00'), Timestamp('2016-01-17 07:00:00'), Timestamp('2016-01-17 08:00:00'), Timestamp('2016-01-17 09:00:00'), Timestamp('2016-01-17 10:00:00'), Timestamp('2016-01-17 11:00:00'), Timestamp('2016-01-17 12:00:00'), Timestamp('2016-01-17 13:00:00'), Timestamp('2016-01-17 14:00:00'), Timestamp('2016-01-17 15:00:00'), Timestamp('2016-01-17 16:00:00'), Timestamp('2016-01-17 17:00:00'), Timestamp('2016-01-17 18:00:00'), Timestamp('2016-01-17 19:00:00'), Timestamp('2016-01-17 20:00:00'), Timestamp('2016-01-17 21:00:00'), Timestamp('2016-01-17 22:00:00'), Timestamp('2016-01-17 23:00:00'), Timestamp('2016-01-18 00:00:00'), Timestamp('2016-01-18 01:00:00'), Timestamp('2016-01-18 02:00:00'), Timestamp('2016-01-18 03:00:00'), Timestamp('2016-01-18 04:00:00'), Timestamp('2016-01-18 05:00:00'), Timestamp('2016-01-18 06:00:00'), Timestamp('2016-01-18 07:00:00'), Timestamp('2016-01-18 08:00:00'), Timestamp('2016-01-18 09:00:00'), Timestamp('2016-01-18 10:00:00'), Timestamp('2016-01-18 11:00:00'), Timestamp('2016-01-18 12:00:00'), Timestamp('2016-01-18 13:00:00'), Timestamp('2016-01-18 14:00:00'), Timestamp('2016-01-18 15:00:00'), Timestamp('2016-01-18 16:00:00'), Timestamp('2016-01-18 17:00:00'), Timestamp('2016-01-18 18:00:00'), Timestamp('2016-01-18 19:00:00'), Timestamp('2016-01-18 20:00:00'), Timestamp('2016-01-18 21:00:00'), Timestamp('2016-01-18 22:00:00'), Timestamp('2016-01-18 23:00:00'), Timestamp('2016-01-19 00:00:00'), Timestamp('2016-01-19 01:00:00'), Timestamp('2016-01-19 02:00:00'), Timestamp('2016-01-19 03:00:00'), Timestamp('2016-01-19 04:00:00'), Timestamp('2016-01-19 05:00:00'), Timestamp('2016-01-19 06:00:00'), Timestamp('2016-01-19 07:00:00'), Timestamp('2016-01-19 08:00:00'), Timestamp('2016-01-19 09:00:00'), Timestamp('2016-01-19 10:00:00'), Timestamp('2016-01-19 11:00:00'), Timestamp('2016-01-19 12:00:00'), Timestamp('2016-01-19 13:00:00'), Timestamp('2016-01-19 14:00:00'), Timestamp('2016-01-19 15:00:00'), Timestamp('2016-01-19 16:00:00'), Timestamp('2016-01-19 17:00:00'), Timestamp('2016-01-19 18:00:00'), Timestamp('2016-01-19 19:00:00'), Timestamp('2016-01-19 20:00:00'), Timestamp('2016-01-19 21:00:00'), Timestamp('2016-01-19 22:00:00'), Timestamp('2016-01-19 23:00:00'), Timestamp('2016-01-20 00:00:00'), Timestamp('2016-01-20 01:00:00'), Timestamp('2016-01-20 02:00:00'), Timestamp('2016-01-20 03:00:00'), Timestamp('2016-01-20 04:00:00'), Timestamp('2016-01-20 05:00:00'), Timestamp('2016-01-20 06:00:00'), Timestamp('2016-01-20 07:00:00'), Timestamp('2016-01-20 08:00:00'), Timestamp('2016-01-20 09:00:00'), Timestamp('2016-01-20 10:00:00'), Timestamp('2016-01-20 11:00:00'), Timestamp('2016-01-20 12:00:00'), Timestamp('2016-01-20 13:00:00'), Timestamp('2016-01-20 14:00:00'), Timestamp('2016-01-20 15:00:00'), Timestamp('2016-01-20 16:00:00'), Timestamp('2016-01-20 17:00:00'), Timestamp('2016-01-20 18:00:00'), Timestamp('2016-01-20 19:00:00'), Timestamp('2016-01-20 20:00:00'), Timestamp('2016-01-20 21:00:00'), Timestamp('2016-01-20 22:00:00'), Timestamp('2016-01-20 23:00:00'), Timestamp('2016-01-21 00:00:00'), Timestamp('2016-01-21 01:00:00'), Timestamp('2016-01-21 02:00:00'), Timestamp('2016-01-21 03:00:00'), Timestamp('2016-01-21 04:00:00'), Timestamp('2016-01-21 05:00:00'), Timestamp('2016-01-21 06:00:00'), Timestamp('2016-01-21 07:00:00'), Timestamp('2016-01-21 08:00:00'), Timestamp('2016-01-21 09:00:00'), Timestamp('2016-01-21 10:00:00'), Timestamp('2016-01-21 11:00:00'), Timestamp('2016-01-21 12:00:00'), Timestamp('2016-01-21 13:00:00'), Timestamp('2016-01-21 14:00:00'), Timestamp('2016-01-21 15:00:00'), Timestamp('2016-01-21 16:00:00'), Timestamp('2016-01-21 17:00:00'), Timestamp('2016-01-21 18:00:00'), Timestamp('2016-01-21 19:00:00'), Timestamp('2016-01-21 20:00:00'), Timestamp('2016-01-21 21:00:00'), Timestamp('2016-01-21 22:00:00'), Timestamp('2016-01-21 23:00:00'), Timestamp('2016-01-22 00:00:00'), Timestamp('2016-01-22 01:00:00'), Timestamp('2016-01-22 02:00:00'), Timestamp('2016-01-22 03:00:00'), Timestamp('2016-01-22 04:00:00'), Timestamp('2016-01-22 05:00:00'), Timestamp('2016-01-22 06:00:00'), Timestamp('2016-01-22 07:00:00'), Timestamp('2016-01-22 08:00:00'), Timestamp('2016-01-22 09:00:00'), Timestamp('2016-01-22 10:00:00'), Timestamp('2016-01-22 11:00:00'), Timestamp('2016-01-22 12:00:00'), Timestamp('2016-01-22 13:00:00'), Timestamp('2016-01-22 14:00:00'), Timestamp('2016-01-22 15:00:00'), Timestamp('2016-01-22 16:00:00'), Timestamp('2016-01-22 17:00:00'), Timestamp('2016-01-22 18:00:00'), Timestamp('2016-01-22 19:00:00'), Timestamp('2016-01-22 20:00:00'), Timestamp('2016-01-22 21:00:00'), Timestamp('2016-01-22 22:00:00'), Timestamp('2016-01-22 23:00:00'), Timestamp('2016-01-23 00:00:00'), Timestamp('2016-01-23 01:00:00'), Timestamp('2016-01-23 02:00:00'), Timestamp('2016-01-23 03:00:00'), Timestamp('2016-01-23 04:00:00'), Timestamp('2016-01-23 05:00:00'), Timestamp('2016-01-23 06:00:00'), Timestamp('2016-01-23 07:00:00'), Timestamp('2016-01-23 08:00:00'), Timestamp('2016-01-23 09:00:00'), Timestamp('2016-01-23 10:00:00'), Timestamp('2016-01-23 11:00:00'), Timestamp('2016-01-23 12:00:00'), Timestamp('2016-01-23 13:00:00'), Timestamp('2016-01-23 14:00:00'), Timestamp('2016-01-23 15:00:00'), Timestamp('2016-01-23 16:00:00'), Timestamp('2016-01-23 17:00:00'), Timestamp('2016-01-23 18:00:00'), Timestamp('2016-01-23 19:00:00'), Timestamp('2016-01-23 20:00:00'), Timestamp('2016-01-23 21:00:00'), Timestamp('2016-01-23 22:00:00'), Timestamp('2016-01-23 23:00:00'), Timestamp('2016-01-24 00:00:00'), Timestamp('2016-01-24 01:00:00'), Timestamp('2016-01-24 02:00:00'), Timestamp('2016-01-24 03:00:00'), Timestamp('2016-01-24 04:00:00'), Timestamp('2016-01-24 05:00:00'), Timestamp('2016-01-24 06:00:00'), Timestamp('2016-01-24 07:00:00'), Timestamp('2016-01-24 08:00:00'), Timestamp('2016-01-24 09:00:00'), Timestamp('2016-01-24 10:00:00'), Timestamp('2016-01-24 11:00:00'), Timestamp('2016-01-24 12:00:00'), Timestamp('2016-01-24 13:00:00'), Timestamp('2016-01-24 14:00:00'), Timestamp('2016-01-24 15:00:00'), Timestamp('2016-01-24 16:00:00'), Timestamp('2016-01-24 17:00:00'), Timestamp('2016-01-24 18:00:00'), Timestamp('2016-01-24 19:00:00'), Timestamp('2016-01-24 20:00:00'), Timestamp('2016-01-24 21:00:00'), Timestamp('2016-01-24 22:00:00'), Timestamp('2016-01-24 23:00:00'), Timestamp('2016-01-25 00:00:00'), Timestamp('2016-01-25 01:00:00'), Timestamp('2016-01-25 02:00:00'), Timestamp('2016-01-25 03:00:00'), Timestamp('2016-01-25 04:00:00'), Timestamp('2016-01-25 05:00:00'), Timestamp('2016-01-25 06:00:00'), Timestamp('2016-01-25 07:00:00'), Timestamp('2016-01-25 08:00:00'), Timestamp('2016-01-25 09:00:00'), Timestamp('2016-01-25 10:00:00'), Timestamp('2016-01-25 11:00:00'), Timestamp('2016-01-25 12:00:00'), Timestamp('2016-01-25 13:00:00'), Timestamp('2016-01-25 14:00:00'), Timestamp('2016-01-25 15:00:00'), Timestamp('2016-01-25 16:00:00'), Timestamp('2016-01-25 17:00:00'), Timestamp('2016-01-25 18:00:00'), Timestamp('2016-01-25 19:00:00'), Timestamp('2016-01-25 20:00:00'), Timestamp('2016-01-25 21:00:00'), Timestamp('2016-01-25 22:00:00'), Timestamp('2016-01-25 23:00:00'), Timestamp('2016-01-26 00:00:00'), Timestamp('2016-01-26 01:00:00'), Timestamp('2016-01-26 02:00:00'), Timestamp('2016-01-26 03:00:00'), Timestamp('2016-01-26 04:00:00'), Timestamp('2016-01-26 05:00:00'), Timestamp('2016-01-26 06:00:00'), Timestamp('2016-01-26 07:00:00'), Timestamp('2016-01-26 08:00:00'), Timestamp('2016-01-26 09:00:00'), Timestamp('2016-01-26 10:00:00'), Timestamp('2016-01-26 11:00:00'), Timestamp('2016-01-26 12:00:00'), Timestamp('2016-01-26 13:00:00'), Timestamp('2016-01-26 14:00:00'), Timestamp('2016-01-26 15:00:00'), Timestamp('2016-01-26 16:00:00'), Timestamp('2016-01-26 17:00:00'), Timestamp('2016-01-26 18:00:00'), Timestamp('2016-01-26 19:00:00'), Timestamp('2016-01-26 20:00:00'), Timestamp('2016-01-26 21:00:00'), Timestamp('2016-01-26 22:00:00'), Timestamp('2016-01-26 23:00:00'), Timestamp('2016-01-27 00:00:00'), Timestamp('2016-01-27 01:00:00'), Timestamp('2016-01-27 02:00:00'), Timestamp('2016-01-27 03:00:00'), Timestamp('2016-01-27 04:00:00'), Timestamp('2016-01-27 05:00:00'), Timestamp('2016-01-27 06:00:00'), Timestamp('2016-01-27 07:00:00'), Timestamp('2016-01-27 08:00:00'), Timestamp('2016-01-27 09:00:00'), Timestamp('2016-01-27 10:00:00'), Timestamp('2016-01-27 11:00:00'), Timestamp('2016-01-27 12:00:00'), Timestamp('2016-01-27 13:00:00'), Timestamp('2016-01-27 14:00:00'), Timestamp('2016-01-27 15:00:00'), Timestamp('2016-01-27 16:00:00'), Timestamp('2016-01-27 17:00:00'), Timestamp('2016-01-27 18:00:00'), Timestamp('2016-01-27 19:00:00'), Timestamp('2016-01-27 20:00:00'), Timestamp('2016-01-27 21:00:00'), Timestamp('2016-01-27 22:00:00'), Timestamp('2016-01-27 23:00:00'), Timestamp('2016-01-28 00:00:00'), Timestamp('2016-01-28 01:00:00'), Timestamp('2016-01-28 02:00:00'), Timestamp('2016-01-28 03:00:00'), Timestamp('2016-01-28 04:00:00'), Timestamp('2016-01-28 05:00:00'), Timestamp('2016-01-28 06:00:00'), Timestamp('2016-01-28 07:00:00'), Timestamp('2016-01-28 08:00:00'), Timestamp('2016-01-28 09:00:00'), Timestamp('2016-01-28 10:00:00'), Timestamp('2016-01-28 11:00:00'), Timestamp('2016-01-28 12:00:00'), Timestamp('2016-01-28 13:00:00'), Timestamp('2016-01-28 14:00:00'), Timestamp('2016-01-28 15:00:00'), Timestamp('2016-01-28 16:00:00'), Timestamp('2016-01-28 17:00:00'), Timestamp('2016-01-28 18:00:00'), Timestamp('2016-01-28 19:00:00'), Timestamp('2016-01-28 20:00:00'), Timestamp('2016-01-28 21:00:00'), Timestamp('2016-01-28 22:00:00'), Timestamp('2016-01-28 23:00:00'), Timestamp('2016-01-29 00:00:00'), Timestamp('2016-01-29 01:00:00'), Timestamp('2016-01-29 02:00:00'), Timestamp('2016-01-29 03:00:00'), Timestamp('2016-01-29 04:00:00'), Timestamp('2016-01-29 05:00:00'), Timestamp('2016-01-29 06:00:00'), Timestamp('2016-01-29 07:00:00'), Timestamp('2016-01-29 08:00:00'), Timestamp('2016-01-29 09:00:00'), Timestamp('2016-01-29 10:00:00'), Timestamp('2016-01-29 11:00:00'), Timestamp('2016-01-29 12:00:00'), Timestamp('2016-01-29 13:00:00'), Timestamp('2016-01-29 14:00:00'), Timestamp('2016-01-29 15:00:00'), Timestamp('2016-01-29 16:00:00'), Timestamp('2016-01-29 17:00:00'), Timestamp('2016-01-29 18:00:00'), Timestamp('2016-01-29 19:00:00'), Timestamp('2016-01-29 20:00:00'), Timestamp('2016-01-29 21:00:00'), Timestamp('2016-01-29 22:00:00'), Timestamp('2016-01-29 23:00:00'), Timestamp('2016-01-30 00:00:00'), Timestamp('2016-01-30 01:00:00'), Timestamp('2016-01-30 02:00:00'), Timestamp('2016-01-30 03:00:00'), Timestamp('2016-01-30 04:00:00'), Timestamp('2016-01-30 05:00:00'), Timestamp('2016-01-30 06:00:00'), Timestamp('2016-01-30 07:00:00'), Timestamp('2016-01-30 08:00:00'), Timestamp('2016-01-30 09:00:00'), Timestamp('2016-01-30 10:00:00'), Timestamp('2016-01-30 11:00:00'), Timestamp('2016-01-30 12:00:00'), Timestamp('2016-01-30 13:00:00'), Timestamp('2016-01-30 14:00:00'), Timestamp('2016-01-30 15:00:00'), Timestamp('2016-01-30 16:00:00'), Timestamp('2016-01-30 17:00:00'), Timestamp('2016-01-30 18:00:00'), Timestamp('2016-01-30 19:00:00'), Timestamp('2016-01-30 20:00:00'), Timestamp('2016-01-30 21:00:00'), Timestamp('2016-01-30 22:00:00'), Timestamp('2016-01-30 23:00:00'), Timestamp('2016-01-31 00:00:00'), Timestamp('2016-01-31 01:00:00'), Timestamp('2016-01-31 02:00:00'), Timestamp('2016-01-31 03:00:00'), Timestamp('2016-01-31 04:00:00'), Timestamp('2016-01-31 05:00:00'), Timestamp('2016-01-31 06:00:00'), Timestamp('2016-01-31 07:00:00'), Timestamp('2016-01-31 08:00:00'), Timestamp('2016-01-31 09:00:00'), Timestamp('2016-01-31 10:00:00'), Timestamp('2016-01-31 11:00:00'), Timestamp('2016-01-31 12:00:00'), Timestamp('2016-01-31 13:00:00'), Timestamp('2016-01-31 14:00:00'), Timestamp('2016-01-31 15:00:00'), Timestamp('2016-01-31 16:00:00'), Timestamp('2016-01-31 17:00:00'), Timestamp('2016-01-31 18:00:00'), Timestamp('2016-01-31 19:00:00'), Timestamp('2016-01-31 20:00:00'), Timestamp('2016-01-31 21:00:00'), Timestamp('2016-01-31 22:00:00'), Timestamp('2016-01-31 23:00:00'), Timestamp('2016-02-01 00:00:00'), Timestamp('2016-02-01 01:00:00'), Timestamp('2016-02-01 02:00:00'), Timestamp('2016-02-01 03:00:00'), Timestamp('2016-02-01 04:00:00'), Timestamp('2016-02-01 05:00:00'), Timestamp('2016-02-01 06:00:00'), Timestamp('2016-02-01 07:00:00'), Timestamp('2016-02-01 08:00:00'), Timestamp('2016-02-01 09:00:00'), Timestamp('2016-02-01 10:00:00'), Timestamp('2016-02-01 11:00:00'), Timestamp('2016-02-01 12:00:00'), Timestamp('2016-02-01 13:00:00'), Timestamp('2016-02-01 14:00:00'), Timestamp('2016-02-01 15:00:00'), Timestamp('2016-02-01 16:00:00'), Timestamp('2016-02-01 17:00:00'), Timestamp('2016-02-01 18:00:00'), Timestamp('2016-02-01 19:00:00'), Timestamp('2016-02-01 20:00:00'), Timestamp('2016-02-01 21:00:00'), Timestamp('2016-02-01 22:00:00'), Timestamp('2016-02-01 23:00:00'), Timestamp('2016-02-02 00:00:00'), Timestamp('2016-02-02 01:00:00'), Timestamp('2016-02-02 02:00:00'), Timestamp('2016-02-02 03:00:00'), Timestamp('2016-02-02 04:00:00'), Timestamp('2016-02-02 05:00:00'), Timestamp('2016-02-02 06:00:00'), Timestamp('2016-02-02 07:00:00'), Timestamp('2016-02-02 08:00:00'), Timestamp('2016-02-02 09:00:00'), Timestamp('2016-02-02 10:00:00'), Timestamp('2016-02-02 11:00:00'), Timestamp('2016-02-02 12:00:00'), Timestamp('2016-02-02 13:00:00'), Timestamp('2016-02-02 14:00:00'), Timestamp('2016-02-02 15:00:00'), Timestamp('2016-02-02 16:00:00'), Timestamp('2016-02-02 17:00:00'), Timestamp('2016-02-02 18:00:00'), Timestamp('2016-02-02 19:00:00'), Timestamp('2016-02-02 20:00:00'), Timestamp('2016-02-02 21:00:00'), Timestamp('2016-02-02 22:00:00'), Timestamp('2016-02-02 23:00:00'), Timestamp('2016-02-03 00:00:00'), Timestamp('2016-02-03 01:00:00'), Timestamp('2016-02-03 02:00:00'), Timestamp('2016-02-03 03:00:00'), Timestamp('2016-02-03 04:00:00'), Timestamp('2016-02-03 05:00:00'), Timestamp('2016-02-03 06:00:00'), Timestamp('2016-02-03 07:00:00'), Timestamp('2016-02-03 08:00:00'), Timestamp('2016-02-03 09:00:00'), Timestamp('2016-02-03 10:00:00'), Timestamp('2016-02-03 11:00:00'), Timestamp('2016-02-03 12:00:00'), Timestamp('2016-02-03 13:00:00'), Timestamp('2016-02-03 14:00:00'), Timestamp('2016-02-03 15:00:00'), Timestamp('2016-02-03 16:00:00'), Timestamp('2016-02-03 17:00:00'), Timestamp('2016-02-03 18:00:00'), Timestamp('2016-02-03 19:00:00'), Timestamp('2016-02-03 20:00:00'), Timestamp('2016-02-03 21:00:00'), Timestamp('2016-02-03 22:00:00'), Timestamp('2016-02-03 23:00:00'), Timestamp('2016-02-04 00:00:00'), Timestamp('2016-02-04 01:00:00'), Timestamp('2016-02-04 02:00:00'), Timestamp('2016-02-04 03:00:00'), Timestamp('2016-02-04 04:00:00'), Timestamp('2016-02-04 05:00:00'), Timestamp('2016-02-04 06:00:00'), Timestamp('2016-02-04 07:00:00'), Timestamp('2016-02-04 08:00:00'), Timestamp('2016-02-04 09:00:00'), Timestamp('2016-02-04 10:00:00'), Timestamp('2016-02-04 11:00:00'), Timestamp('2016-02-04 12:00:00'), Timestamp('2016-02-04 13:00:00'), Timestamp('2016-02-04 14:00:00'), Timestamp('2016-02-04 15:00:00'), Timestamp('2016-02-04 16:00:00'), Timestamp('2016-02-04 17:00:00'), Timestamp('2016-02-04 18:00:00'), Timestamp('2016-02-04 19:00:00'), Timestamp('2016-02-04 20:00:00'), Timestamp('2016-02-04 21:00:00'), Timestamp('2016-02-04 22:00:00'), Timestamp('2016-02-04 23:00:00'), Timestamp('2016-02-05 00:00:00'), Timestamp('2016-02-05 01:00:00'), Timestamp('2016-02-05 02:00:00'), Timestamp('2016-02-05 03:00:00'), Timestamp('2016-02-05 04:00:00'), Timestamp('2016-02-05 05:00:00'), Timestamp('2016-02-05 06:00:00'), Timestamp('2016-02-05 07:00:00'), Timestamp('2016-02-05 08:00:00'), Timestamp('2016-02-05 09:00:00'), Timestamp('2016-02-05 10:00:00'), Timestamp('2016-02-05 11:00:00'), Timestamp('2016-02-05 12:00:00'), Timestamp('2016-02-05 13:00:00'), Timestamp('2016-02-05 14:00:00'), Timestamp('2016-02-05 15:00:00'), Timestamp('2016-02-05 16:00:00'), Timestamp('2016-02-05 17:00:00'), Timestamp('2016-02-05 18:00:00'), Timestamp('2016-02-05 19:00:00'), Timestamp('2016-02-05 20:00:00'), Timestamp('2016-02-05 21:00:00'), Timestamp('2016-02-05 22:00:00'), Timestamp('2016-02-05 23:00:00'), Timestamp('2016-02-06 00:00:00'), Timestamp('2016-02-06 01:00:00'), Timestamp('2016-02-06 02:00:00'), Timestamp('2016-02-06 03:00:00'), Timestamp('2016-02-06 04:00:00'), Timestamp('2016-02-06 05:00:00'), Timestamp('2016-02-06 06:00:00'), Timestamp('2016-02-06 07:00:00'), Timestamp('2016-02-06 08:00:00'), Timestamp('2016-02-06 09:00:00'), Timestamp('2016-02-06 10:00:00'), Timestamp('2016-02-06 11:00:00'), Timestamp('2016-02-06 12:00:00'), Timestamp('2016-02-06 13:00:00'), Timestamp('2016-02-06 14:00:00'), Timestamp('2016-02-06 15:00:00'), Timestamp('2016-02-06 16:00:00'), Timestamp('2016-02-06 17:00:00'), Timestamp('2016-02-06 18:00:00'), Timestamp('2016-02-06 19:00:00'), Timestamp('2016-02-06 20:00:00'), Timestamp('2016-02-06 21:00:00'), Timestamp('2016-02-06 22:00:00'), Timestamp('2016-02-06 23:00:00'), Timestamp('2016-02-07 00:00:00'), Timestamp('2016-02-07 01:00:00'), Timestamp('2016-02-07 02:00:00'), Timestamp('2016-02-07 03:00:00'), Timestamp('2016-02-07 04:00:00'), Timestamp('2016-02-07 05:00:00'), Timestamp('2016-02-07 06:00:00'), Timestamp('2016-02-07 07:00:00'), Timestamp('2016-02-07 08:00:00'), Timestamp('2016-02-07 09:00:00'), Timestamp('2016-02-07 10:00:00'), Timestamp('2016-02-07 11:00:00'), Timestamp('2016-02-07 12:00:00'), Timestamp('2016-02-07 13:00:00'), Timestamp('2016-02-07 14:00:00'), Timestamp('2016-02-07 15:00:00'), Timestamp('2016-02-07 16:00:00'), Timestamp('2016-02-07 17:00:00'), Timestamp('2016-02-07 18:00:00'), Timestamp('2016-02-07 19:00:00'), Timestamp('2016-02-07 20:00:00'), Timestamp('2016-02-07 21:00:00'), Timestamp('2016-02-07 22:00:00'), Timestamp('2016-02-07 23:00:00'), Timestamp('2016-02-08 00:00:00'), Timestamp('2016-02-08 01:00:00'), Timestamp('2016-02-08 02:00:00'), Timestamp('2016-02-08 03:00:00'), Timestamp('2016-02-08 04:00:00'), Timestamp('2016-02-08 05:00:00'), Timestamp('2016-02-08 06:00:00'), Timestamp('2016-02-08 07:00:00'), Timestamp('2016-02-08 08:00:00'), Timestamp('2016-02-08 09:00:00'), Timestamp('2016-02-08 10:00:00'), Timestamp('2016-02-08 11:00:00'), Timestamp('2016-02-08 12:00:00'), Timestamp('2016-02-08 13:00:00'), Timestamp('2016-02-08 14:00:00'), Timestamp('2016-02-08 15:00:00'), Timestamp('2016-02-08 16:00:00'), Timestamp('2016-02-08 17:00:00'), Timestamp('2016-02-08 18:00:00'), Timestamp('2016-02-08 19:00:00'), Timestamp('2016-02-08 20:00:00'), Timestamp('2016-02-08 21:00:00'), Timestamp('2016-02-08 22:00:00'), Timestamp('2016-02-08 23:00:00'), Timestamp('2016-02-09 00:00:00'), Timestamp('2016-02-09 01:00:00'), Timestamp('2016-02-09 02:00:00'), Timestamp('2016-02-09 03:00:00'), Timestamp('2016-02-09 04:00:00'), Timestamp('2016-02-09 05:00:00'), Timestamp('2016-02-09 06:00:00'), Timestamp('2016-02-09 07:00:00'), Timestamp('2016-02-09 08:00:00'), Timestamp('2016-02-09 09:00:00'), Timestamp('2016-02-09 10:00:00'), Timestamp('2016-02-09 11:00:00'), Timesta

In [1335]:
# Ausgabe der Listen um auf Länge zu testen 2023
print(len(zeitraum))
print(len(bruehler_straße))
print(len(estermannufer))
print(len(kennedybruecke))
print(len(nordbruecke))
print(len(suedbruecke))
print(len(rhenusallee))
print(len(von_sandt_ufer))
print(len(weg_auf_dem_damm))
print(len(wilhelm_spiritus_ufer))

69745
69745
69745
69745
69745
69745
69745
69745
69745
69745

In [1336]:
# Zusammenfügen des Dataframe
df_gesamt['time'] = zeitraum
df_gesamt['bruehler_straße'] = bruehler_straße
df_gesamt['estermannufer'] = estermannufer
df_gesamt['kennedybruecke'] = kennedybruecke
df_gesamt['nordbruecke'] = nordbruecke
df_gesamt['suedbruecke'] = suedbruecke
df_gesamt['rhenusallee'] = rhenusallee
df_gesamt['von_sandt_ufer'] = von_sandt_ufer
df_gesamt['weg_auf_dem_damm'] = weg_auf_dem_damm
df_gesamt['wilhelm_spiritus_ufer'] = wilhelm_spiritus_ufer
df_gesamt['time'] = pd.to_datetime(df_gesamt['time'])
df_gesamt['time'] = pd.to_datetime(df_gesamt['time'], format='%Y-%m-%d %H:%M:%S')
df_gesamt = df_gesamt.set_index('time')
df_gesamt.sort_index(inplace=True)
df_gesamt

,bruehler_straße,estermannufer,kennedybruecke,nordbruecke,suedbruecke,rhenusallee,von_sandt_ufer,weg_auf_dem_damm,wilhelm_spiritus_ufer
time,,,,,,,,,
2016-01-16 00:00:00,5.0,0.0,36.0,1.0,3.0,5.0,2.0,3.0,1.0
2016-01-16 01:00:00,4.0,0.0,44.0,3.0,4.0,4.0,2.0,3.0,4.0
2016-01-16 02:00:00,0.0,0.0,26.0,3.0,3.0,3.0,0.0,3.0,2.0
2016-01-16 03:00:00,3.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0
2016-01-16 04:00:00,1.0,0.0,22.0,3.0,1.0,2.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
2023-12-31 19:00:00,NaN,0.0,146.0,12.0,22.0,NaN,5.0,18.0,11.0
2023-12-31 20:00:00,NaN,0.0,99.0,15.0,10.0,NaN,2.0,10.0,13.0
2023-12-31 21:00:00,NaN,0.0,69.0,5.0,9.0,NaN,6.0,12.0,13.0
2023-12-31 22:00:00,NaN,0.0,46.0,0.0,13.0,NaN,1.0,5.0,11.0
2023-12-31 23:00:00,NaN,0.0,50.0,11.0,9.0,NaN,8.0,10.0,24.0

In [1337]:
# Speichern der Fahhradzaehlung_komplett
filepath = Path('../Neuronales_Netz/Fahrradzaehlung_komplett.csv')
filepath.parent.mkdir(parents=True, exist_ok=True)
df_gesamt.to_csv(filepath)

In [1338]:
# Anzeigen der NaN
df_gesamt[df_gesamt.isna().any(axis=1)]

,bruehler_straße,estermannufer,kennedybruecke,nordbruecke,suedbruecke,rhenusallee,von_sandt_ufer,weg_auf_dem_damm,wilhelm_spiritus_ufer
time,,,,,,,,,
2021-01-02 00:00:00,0.0,NaN,9.0,0.0,0.0,0.0,0.0,1.0,0.0
2021-01-02 01:00:00,1.0,NaN,1.0,0.0,1.0,1.0,0.0,0.0,0.0
2021-01-02 02:00:00,0.0,NaN,3.0,0.0,2.0,1.0,0.0,0.0,0.0
2021-01-02 03:00:00,3.0,NaN,8.0,0.0,1.0,0.0,0.0,1.0,0.0
2021-01-02 04:00:00,7.0,NaN,8.0,3.0,4.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
2023-12-31 19:00:00,NaN,0.0,146.0,12.0,22.0,NaN,5.0,18.0,11.0
2023-12-31 20:00:00,NaN,0.0,99.0,15.0,10.0,NaN,2.0,10.0,13.0
2023-12-31 21:00:00,NaN,0.0,69.0,5.0,9.0,NaN,6.0,12.0,13.0
2023-12-31 22:00:00,NaN,0.0,46.0,0.0,13.0,NaN,1.0,5.0,11.0
2023-12-31 23:00:00,NaN,0.0,50.0,11.0,9.0,NaN,8.0,10.0,24.0

In [1339]:
# Anzeigen der Summe der NaN
df.isna().sum()

Kennedybruecke (Nord)              1417
Kennedybruecke (Sued) Barometer       1
Nordbruecke (Sued)                    1
Nordbruecke (Nord)                    1
Suedbruecke (Sued)                    1
Suedbruecke (Nord)                    1
Estermannufer                         1
Von-Sandt-Ufer                        1
Rhenusallee                        3505
Broehltalweg                          1
Bruehler Straße                    4957
Wilhelm-Spiritus-Ufer                 1
Mc Cloy Weg                           1
Weg auf Damm Neil                     1
Kennedybruecke                        1
Nordbruecke                           1
Suedbruecke                           1
days                                  0
dtype: int64

In [1340]:
# Berechnung des Weekly_Mean
bruecken = df_gesamt.columns.values
time_train_gesamt = df_gesamt.index
X1 = df_gesamt[bruecken].values
week_means1 = pd.DataFrame(X1, index=time_train_gesamt, columns=bruecken)
week_means1 = week_means1.groupby(week_means1.index.isocalendar().week)[week_means1.columns].mean()
df_weekly_mean = pd.DataFrame(week_means1)
df_weekly_mean

,bruehler_straße,estermannufer,kennedybruecke,nordbruecke,suedbruecke,rhenusallee,von_sandt_ufer,weg_auf_dem_damm,wilhelm_spiritus_ufer
week,,,,,,,,,
1,24.463652,20.829082,209.364796,37.896259,73.471088,62.532313,53.074830,63.185374,74.998299
2,26.530142,18.570261,222.387255,35.992647,69.584150,54.657801,48.876634,58.697712,70.214869
3,25.270089,8.333333,219.068452,25.993304,68.594494,35.420387,28.700893,40.149554,53.796131
4,25.574405,8.148920,213.601190,26.569196,69.115327,34.738095,26.722470,39.639137,49.059524
5,26.573661,11.845455,216.764137,30.656994,76.375000,44.755208,35.826637,47.212054,60.295387
6,33.894167,26.197917,272.352679,46.122024,95.307292,78.015224,66.868304,78.034226,96.848214
7,27.395089,14.705357,229.733631,34.795387,80.210565,49.406994,41.747024,57.250000,64.456101
8,27.200149,15.608631,235.552083,36.002976,84.470238,51.636905,43.422619,59.043155,67.239583
9,27.467262,15.677273,239.721726,34.633929,81.018601,50.101190,42.086310,55.078869,66.180060
10,34.619048,28.942708,279.501488,49.915179,99.517857,83.495994,71.108631,84.226935,100.325893
11,29.593006,15.507440,243.663690,35.966518,84.757440,56.988839,44.866071,57.595982,70.302827
12,34.336066,24.861401,286.732489,50.149776,104.575261,84.423994,64.518629,83.152012,93.588674
13,32.101935,26.571212,259.852679,48.569940,89.918155,80.517113,63.350446,80.578125,89.430060
14,35.703791,28.765625,288.840030,50.105655,106.517857,84.075758,71.255208,83.755952,106.336310
15,34.753931,29.622024,280.473958,47.505208,102.943452,83.477987,70.648810,80.151042,98.666667
16,38.320685,42.074405,309.862351,66.004464,117.715030,115.555060,93.642113,113.573661,129.389137
17,39.348214,34.234091,305.369792,57.543155,101.364583,96.648065,78.421875,97.046875,112.180060
18,37.145027,31.382440,298.869792,52.181548,113.895089,94.318452,77.369048,95.313988,113.502976
19,41.617647,38.190476,333.577381,61.335565,122.123512,102.089744,90.258185,102.511161,122.375000
20,41.716518,42.982143,322.026042,64.384673,125.847470,112.409226,95.904018,113.707589,135.239583
21,39.886905,51.021577,314.959077,67.944196,116.447173,112.668899,109.743304,121.062500,140.904762
22,41.452381,38.050000,321.003720,61.090030,107.034226,89.194940,89.862351,103.049107,122.106399
23,41.278232,40.354167,337.921131,63.092262,131.845982,98.805818,98.421875,112.315476,134.828869
24,41.172619,42.522321,333.328869,70.687500,138.845982,101.456061,106.645833,116.897321,140.256696
25,45.824830,42.925595,352.894345,70.386161,131.155506,106.522321,109.872768,120.026786,149.280506
26,44.071078,40.966667,346.938244,68.423363,124.572917,95.186756,99.963542,113.530506,138.457589
27,42.261218,41.453869,346.354167,63.972470,131.234375,97.890909,96.914435,111.168155,134.035714
28,38.369048,37.302827,313.363839,58.165179,122.329613,87.705189,89.192708,101.736607,121.385417
29,41.999150,51.778274,338.170387,73.321429,140.210565,118.730655,120.623512,126.630952,165.075149
30,39.320578,46.435268,295.093750,62.159970,112.563988,94.142113,103.574405,103.892857,138.677827
31,38.206019,42.877273,286.575893,59.166667,121.172619,85.817708,94.361607,100.616815,122.976190
32,39.854592,44.049107,302.133929,64.848214,123.241815,90.085833,101.973958,108.116815,128.950893
33,39.997449,46.671131,312.813244,64.129464,142.554315,93.393707,109.281994,112.901042,144.827381
34,45.131803,53.377976,356.970982,75.000744,159.476935,112.321429,126.456101,128.406250,161.783482
35,44.538462,40.703030,340.977679,64.513393,135.372024,89.310096,99.005208,108.666667,133.534226
36,41.931373,39.125744,315.539435,61.580357,116.843750,89.602987,94.203125,103.322173,128.652530
37,39.691327,34.823661,308.301339,55.273810,115.206845,83.802721,86.732887,96.055060,119.234375
38,46.199830,41.088542,350.730655,64.063988,135.629464,102.926020,99.924851,115.607887,137.590774
39,40.843333,27.450336,313.183036,49.468006,111.488839,70.703333,71.692708,85.295387,107.444196
40,36.777519,27.930060,255.251488,48.016369,93.286458,63.800758,67.934524,79.550595,96.316220
41,38.440476,30.568452,290.953869,49.963542,101.318452,79.401361,74.297619,87.695685,107.290179
42,36.085884,21.569196,274.395089,41.183780,92.848958,59.080782,55.571429,69.819940,89.340030
43,38.600340,21.148065,284.757440,42.599702,91.577381,57.203231,56.997024,70.492560,87.403274
44,32.969907,18.946429,267.852679,39.871280,85.362351,51.234568,49.938988,62.868304,78.409970
45,36.524167,27.923363,295.050595,49.842262,94.660714,67.370098,69.113839,80.061756,102.187500
46,34.048469,14.040179,269.445685,35.689732,83.281250,48.022109,41.790923,55.261905,71.284970
47,33.475340,11.043899,264.626488,33.459821,77.218006,42.528061,36.513393,50.491071,65.119792
48,30.752404,10.427083,240.421875,29.904018,70.787946,37.305288,31.620536,44.372768,59.863095
49,33.424020,25.435268,267.051339,45.658482,89.029018,70.072327,62.241071,74.104167,95.476190
50,29.539116,13.031994,240.974702,31.375000,69.042411,46.674320,38.457589,51.266369,65.971726
51,24.835884,7.953125,208.845238,24.444196,54.899554,33.357993,25.367560,37.825149,47.515625
52,13.401361,7.269345,119.162946,20.428571,33.787946,25.635204,21.846726,31.154018,29.127976
53,19.744828,17.057851,159.034483,37.517241,66.055172,56.331034,39.386207,56.220690,53.641379

In [1341]:
# Rolling Mean durchführen
woche=[]
for i in range(52):
    tmp = df_weekly_mean[bruecken][df_weekly_mean.index==i+1].values.tolist()
    woche.append(tmp)

for i in range(52):
    for j in range(len(bruecken)):
        start = df_gesamt[bruecken][df_gesamt.index.isocalendar().week==i+1].index
        anfang = start[0]
        ende = start[-1]
        df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)

/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_gesamt[bruecken[j]][anfang:ende].fillna(value=woche[i][0][j], inplace=True)
/tmp/ipykernel_19033/2390384683.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.


In [1342]:
# Anzeige der Summe der NaN
print(df_gesamt.isna().sum())

bruehler_straße          0
estermannufer            0
kennedybruecke           0
nordbruecke              0
suedbruecke              0
rhenusallee              0
von_sandt_ufer           0
weg_auf_dem_damm         0
wilhelm_spiritus_ufer    0
dtype: int64

In [1343]:
# Speichern der Fahhradzaehlung_komplett_rolling_mean
filepath = Path('../Neuronales_Netz/Fahrradzaehlung_komplett_rolling_mean.csv')
filepath.parent.mkdir(parents=True, exist_ok=True)
df_gesamt.to_csv(filepath)

In [1344]:
df_gesamt = df_gesamt.astype(int)
df_gesamt.dtypes

bruehler_straße          int64
estermannufer            int64
kennedybruecke           int64
nordbruecke              int64
suedbruecke              int64
rhenusallee              int64
von_sandt_ufer           int64
weg_auf_dem_damm         int64
wilhelm_spiritus_ufer    int64
dtype: object

In [1345]:
# Speichern der Fahhradzaehlung_komplett_rolling_mean_int
filepath = Path('../Neuronales_Netz/Fahrradzaehlung_komplett_rolling_mean_int.csv')
filepath.parent.mkdir(parents=True, exist_ok=True)
df_gesamt.to_csv(filepath)